[VCDA-2648] Fix NFS node addition to TKG cluster
vmware/container-service-extension pull request #1132
Opened 2021-07-20 17:33 UTC by rocknes

Users are unable to add NFS node to TKG clusters based on Ubuntu 20.04. The reason behind the failure is due to how CSE executes the nfsd.sh file on the newly created VM. Typically by the time CSE tries to run the script, the VM guest customization is over and the root password is set properly. However in case of Ubuntu 20.04, guest customization is taking way longer than usual and as a result the root password is not set properly by the time CSE tries to run the script. This leads to a failure in the `vsphere-guest-run` library and CSE can't recover from it.

Addition of worker nodes don't face the same issue, because CSE executes a script on master node to fetch its IP, before it tries to run any script on the worker VM. This gives the guest customization process on the worker VM enough time to run to completion.

As a fix, we are adding some extra sleep in the NFS node creation workflow to allow the VM to finish guest customization properly before trying to run nfsd.sh on it.

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

2021-07-20 18:03 UTC, Anirudh9794 requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1132)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/def_/cluster_service.py, line 1148 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf416YP5zgyCUZ333s9:-Mf416YP5zgyCUZ333sA:b-1nhtj0) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L1148)):*
> ```Python
>                 _enable_nfs(
>                     self.context.sysadmin_client, vapp,
>                     template, target_nodes
> ```

as `target_nodes` is kwargs
```
target_nodes=target_nodes
```
___
*[container_service_extension/def_/cluster_service.py, line 2266 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf43-UT3NJ022vY5E5D:-Mf43-UT3NJ022vY5E5E:batj0js) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L2266)):*
> ```Python
>         vapp,
>         template,
>         target_nodes=None):
> ```

`target_nodes` -> `target_nfs_nodes`
as the code ignores other types of nodes silently.

or should log and raise error if nodes other than nfs nodes are passed.
___
*[container_service_extension/def_/cluster_service.py, line 2280 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf43QC_9R8eo-Xz9j47:-Mf43QC_9R8eo-Xz9j48:b-xfnik6) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L2280)):*
> ```Python
>             template[LocalTemplateKey.REVISION],
>             ScriptFile.NFSD)
>         script = utils.read_data_file(script_filepath, logger=LOGGER)  # noqa: E501
> ```

`noqa: E501` can be removed from this line
___
*[container_service_extension/def_/cluster_service.py, line 2283 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf43elEERQQzia6SA-M:-Mf43elEERQQzia6SA-N:b-2ftweo) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L2283)):*
> ```Python
>         exec_results = _execute_script_in_nodes(
>             sysadmin_client, vapp=vapp, node_names=node_names,
>             script=script,use_ubuntu_20_sleep=True)
> ```

space after comma is missing.


<!-- Sent from Reviewable.io -->

2021-07-22 00:23 UTC, rocknes reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1132)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/def_/cluster_service.py, line 1148 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf416YP5zgyCUZ333s9:-Mf6kRTW7SJMoWCHnYar:b-1l9ea) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L1148)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

as `target_nodes` is kwargs
```
target_nodes=target_nodes
```
</blockquote></details>

addressed
___
*[container_service_extension/def_/cluster_service.py, line 2266 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf43-UT3NJ022vY5E5D:-Mf6kVRLArrO_ak1TEBl:bp6cfly) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L2266)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`target_nodes` -> `target_nfs_nodes`
as the code ignores other types of nodes silently.

or should log and raise error if nodes other than nfs nodes are passed.
</blockquote></details>

This method's job is to just run the script in a given vm. The restriction that the vm has to be of NFS type in the responsibility of the caller.
I understand where the confusion is coming from, I will remove the default value for the target_nodes , the default logic is kinda bad imo.
___
*[container_service_extension/def_/cluster_service.py, line 2280 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf43QC_9R8eo-Xz9j47:-Mf6mOrV9XAg1QOMYGOL:b-hfpv0l) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L2280)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`noqa: E501` can be removed from this line
</blockquote></details>

removed
___
*[container_service_extension/def_/cluster_service.py, line 2283 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1132#-Mf43elEERQQzia6SA-M:-Mf6mPr82co1YeHZ_s0P:b-1l9ea) ([raw file](https://github.com/vmware/container-service-extension/blob/12d66a833170a763b8a8a8ab9426f8c2ab8455fd/container_service_extension/def_/cluster_service.py#L2283)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

space after comma is missing.
</blockquote></details>

addressed


<!-- Sent from Reviewable.io -->

2021-07-22 00:34 UTC, sakthisunda approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1132)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/def_/cluster_service.py, line 637 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1132#-MfAcIUADvYXdSD2SJSd:-MfAcIUADvYXdSD2SJSe:b7p44l) ([raw file](https://github.com/vmware/container-service-extension/blob/a9b3fba68b6cb25f4c8e660d4a7c5ce5e4cd8b9c/container_service_extension/def_/cluster_service.py#L637)):*
> ```Python
>             self._update_task(vcd_client.TaskStatus.RUNNING, message=msg)
>             vapp.reload()
>             is_ubuntu_20 = UBUNTU_20_TEMPLATE_NAME_FRAGMENT in template_name
> ```

UBUNTU_20_TEMPLATE_NAME_FRAGMENT - is this defined ? Please ignore this if it is defined


<!-- Sent from Reviewable.io -->

2021-07-22 00:42 UTC, sakthisunda approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1132)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-07-22 03:58 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1132#-:-MfBMOmG30AIR63enpAh:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-07-22 17:45 UTC, merged