[VCDA-2701] Prevent authentication failures by adding sleeps
vmware/container-service-extension pull request #1136
Opened 2021-07-21 16:18 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Sometimes, guest agent fails to authenticate with the guest os because the newly deployed VM has not reached 'gc-complete' status. To overcome this issue with Ubuntu 20.04, some sleep calls were added. This PR generalizes the sleep calls to all the operating systems.

Testing done:
- Create template
- Create cluster
- Resize cluster (Add worker and nfs nodes)

@rocknes @ltimothy7

2021-07-21 16:30 UTC, ltimothy7 requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1136)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/def_/cluster_service.py, line 636 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1136#-Mf8tQ3G4tY1xf-ECAHp:-Mf8tQ3G4tY1xf-ECAHq:bnlu6j1) ([raw file](https://github.com/vmware/container-service-extension/blob/47be723e28cd749b3e72881c21cfd828738aaf26/container_service_extension/def_/cluster_service.py#L636)):*
> ```Python
>             control_plane_ip = _get_control_plane_ip(
>                 self.context.sysadmin_client, vapp, check_tools=True,
>                 use_ubuntu_20_sleep=True)
> ```

Since we are generalizing this sleep to all versions of ubuntu for 3.0.4, I think we could remove this parameter and just sleep unconditionaly. Alternatively, we could also rename this variable to something like `use_authentication_sleep`


<!-- Sent from Reviewable.io -->

2021-07-21 18:25 UTC, Anirudh9794 commented
___
*[container_service_extension/def_/cluster_service.py, line 636 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1136#-Mf8tQ3G4tY1xf-ECAHp:-Mf9J8xr05XTWK-LhCUz:bjgqro2) ([raw file](https://github.com/vmware/container-service-extension/blob/47be723e28cd749b3e72881c21cfd828738aaf26/container_service_extension/def_/cluster_service.py#L636)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Since we are generalizing this sleep to all versions of ubuntu for 3.0.4, I think we could remove this parameter and just sleep unconditionaly. Alternatively, we could also rename this variable to something like `use_authentication_sleep`
</blockquote></details>

Done. Changed the parameter to `use_authentication_sleep`


<!-- Sent from Reviewable.io -->

2021-07-21 20:14 UTC, ltimothy7 approved these changes

2021-07-22 20:39 UTC, rocknes approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1136#-:-MfEwLrn5P_7WVgJ-QFS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)



<!-- Sent from Reviewable.io -->

2021-07-22 21:11 UTC, merged