Port [VCDA-2691] Fix upgrade failure when OLM pods are present to master
vmware/container-service-extension pull request #1145
Opened 2021-07-26 14:57 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 
`kubectl drain ...` command which is executed when upgrading cluster and deleting cluster fails when OLM is present as reported by the issue 
https://github.com/vmware/container-service-extension/issues/1102.
This PR adds `--force` parameter to the `kubectl drain` command so that the node can be drained.

Testing:
cluster upgrade

@rocknes @sakthisunda

2021-07-26 17:24 UTC, sakthisunda requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1145)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2179 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1145#-MfYpvnG4LjRMT7OJQY_:-MfYpvnG4LjRMT7OJQYa:b2nj0b4) ([raw file](https://github.com/vmware/container-service-extension/blob/f192ccfaa1059a73782d46c1c7925d408a697af7/container_service_extension/rde/backend/cluster_service_2_x.py#L2179)):*
> ```
> -ignore-daemonsets
> ```
--ignore-daemonsets  


<!-- Sent from Reviewable.io -->

2021-07-30 16:44 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1145)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2179 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1145#-MfYpvnG4LjRMT7OJQY_:-MfsIJWiBpX5keYgO3DT:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/f192ccfaa1059a73782d46c1c7925d408a697af7/container_service_extension/rde/backend/cluster_service_2_x.py#L2179)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> -ignore-daemonsets
> ```
--ignore-daemonsets  
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 18:09 UTC, sakthisunda approved these changes
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-08-02 18:15 UTC, ltimothy7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1145#-:-Mg73xEj9GybpBdN6MeV:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-08-02 18:19 UTC, merged