Port Fix upgrade failure when OLM pods are present to CSE 3-1 updates
vmware/container-service-extension pull request #1146
Opened 2021-07-26 15:00 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 
`kubectl drain ...` command which is executed when upgrading cluster and deleting cluster fails when OLM is present as reported by the issue 
https://github.com/vmware/container-service-extension/issues/1102.
This PR adds `--force` parameter to the `kubectl drain` command so that the node can be drained.

Testing:
cluster upgrade

@rocknes @sakthisunda

2021-07-26 17:24 UTC, sakthisunda requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1146)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2176 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1146#-MfYqCGN4oJaKPEKdnCd:-MfYqCGN4oJaKPEKdnCe:b2nj0b4) ([raw file](https://github.com/vmware/container-service-extension/blob/4be59d531b385bce44ce366f9b1bc08df00d6fd9/container_service_extension/rde/backend/cluster_service_2_x.py#L2176)):*
> ```
> -ignore-daemonsets
> ```
--ignore-daemonsets  


<!-- Sent from Reviewable.io -->

2021-07-26 20:40 UTC, Anirudh9794 commented
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2176 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1146#-MfYqCGN4oJaKPEKdnCd:-MfZXFAjCOwym25yua2e:b-zf1baa) ([raw file](https://github.com/vmware/container-service-extension/blob/4be59d531b385bce44ce366f9b1bc08df00d6fd9/container_service_extension/rde/backend/cluster_service_2_x.py#L2176)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> -ignore-daemonsets
> ```
--ignore-daemonsets  
</blockquote></details>

good catch, Thanks sakthi


<!-- Sent from Reviewable.io -->

2021-07-27 00:54 UTC, sakthisunda approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-08-02 18:14 UTC, ltimothy7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1146#-:-Mg73mew8MM-_58r7vTS:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-08-02 18:17 UTC, merged