[VCDA-2737] store kube config, kubeadm token in rde
vmware/container-service-extension pull request #1164
Opened 2021-08-18 16:26 UTC by sakthisunda

- Base 64 encoded value of kubeconfig in vm extra config
- Read kubeconfig from vm extra config and store in RDE 
- Read kubeadm token from vm extra config in RDE
- worker node creation, resize use RDE stored values
- Updated kubeconfig based on expose cluster logic stored back in RDE
- Entity update - Replace sysadmin only check with user role with cse:nativeCluster full access rights
- Tested create with and without worker node, resize cluster with worker node, delete cluster
- Testing in progress

@arunmk @rocknes @sahithi

2021-08-20 17:42 UTC, ltimothy7 approved these changes
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1164)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sakthisunda)

___
*[cluster_scripts/v2_x/control_plane_customization.sh, line 55 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhZbFn77_Im8srIGQ51:-MhZSQtO6L1hVd_0RufE:b8ra3z1) ([raw file](https://github.com/vmware/container-service-extension/blob/834117ea1d5750e2524fd7ac961be4cf9134c7de/cluster_scripts/v2_x/control_plane_customization.sh#L55)):*
> ```Shell
>     chown $(id -u):$(id -g) /root/.kube/config
>     export KUBECONFIG=/etc/kubernetes/admin.conf
>     vmtoolsd --cmd "info-set guestinfo.kubeconfig $(cat /etc/kubernetes/admin.conf | base64 | tr -d '\n')"
> ```

To double check, should trimming the '\n' character come before the base64 conversion?


<!-- Sent from Reviewable.io -->

2021-08-20 18:06 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1164)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x/control_plane_customization.sh, line 55 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhZbFn77_Im8srIGQ51:-MhZhlNS2U0t5VvHh2n-:bzeklzs) ([raw file](https://github.com/vmware/container-service-extension/blob/834117ea1d5750e2524fd7ac961be4cf9134c7de/cluster_scripts/v2_x/control_plane_customization.sh#L55)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

To double check, should trimming the '\n' character come before the base64 conversion?
</blockquote></details>

No. Doing that before will cause loosing the original text format (yaml).  base64 encoding wraps the result after every 76 characters. <b>tr -d removes the new line and make it to one string.</b> In fact <b>base64 --wrap=0</b> does the same thing.  

At CSE end, verified the decoded string for being the original file back.  


<!-- Sent from Reviewable.io -->

2021-08-20 18:36 UTC, ltimothy7 approved these changes

2021-08-23 20:43 UTC, arunmk requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1164)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 906 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhoinVi9OWz1jYWOA7F:-MhoinVi9OWz1jYWOA7G:bf4rcry) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L906)):*
> ```Python
>                 api_version=DEFAULT_API_VERSION)
>             # Extra config elements of VApp are visible only for admin client
>             vapp = vcd_vapp.VApp(sysadmin_client_v36,
> ```

For which exact operation do we need the `vapp` with a sysadmin client? Can we have two objects: 
```
vapp = vcd_vapp.VApp(client_v36, href=vapp_resource.get('href'))
sysadmin_vapp = vcd_vapp.VApp(sysadmin_client_v36, href=vapp_resource.get('href'))
```

and use the right object as required by the operation?
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 926 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhoiWmP6tDB9w3sAfJJ:-MhoiWmP6tDB9w3sAfJK:b5cj3wh) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L926)):*
> ```Python
>             try:
>                 _add_control_plane_nodes(
>                     sysadmin_client_v36,
> ```

This should use the ClusterAuthor client. This looks like an existing bug. If you see the VMs for a cluster created using CSE, who is the owner?
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 947 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhojWIp7BGOu81Z6cpN:-MhojWIp7BGOu81Z6cpO:b-jab4z) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L947)):*
> ```Python
>             vapp.reload()
> 
>             control_plane_join_cmd = _get_join_cmd(
> ```

This is the one which actually needs the privileges, correct?
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1234 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhojfcO63jt5bdAw2ne:-MhojfcO63jt5bdAw2nf:bq7osa9) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L1234)):*
> ```Python
> 
>                     # update kubeconfig with internal ip
>                     updated_kube_config = self._replace_kubeconfig_expose_ip(
> ```

@ltimothy7 what is the use of this?

I think the KUBECONFIG should still use the external exposed IP itself. What intra-cluster operation needs the kubeconfig?


<!-- Sent from Reviewable.io -->

2021-08-23 20:58 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1164)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 926 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhoiWmP6tDB9w3sAfJJ:-Mhomsu2BmqTUFSZRDb-:bp4aoaf) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L926)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should use the ClusterAuthor client. This looks like an existing bug. If you see the VMs for a cluster created using CSE, who is the owner?
</blockquote></details>

we have the logic of checking status of different post customization phases here. For which, we need admin_client to get vm extra config
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 947 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhojWIp7BGOu81Z6cpN:-Mhon8Md7YmCgVfJ35tj:b-evyq08) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L947)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This is the one which actually needs the privileges, correct?
</blockquote></details>

Here also, we need for pol


<!-- Sent from Reviewable.io -->

2021-08-23 22:33 UTC, arunmk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1164#-:-Mhp8OZo3DT-_bgWTYOD:bg7igkv)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sakthisunda)



<!-- Sent from Reviewable.io -->

2021-08-23 22:57 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1164)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 906 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhoinVi9OWz1jYWOA7F:-MhpAIMGBmNLNpvrykzw:bsszd3x) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L906)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

For which exact operation do we need the `vapp` with a sysadmin client? Can we have two objects: 
```
vapp = vcd_vapp.VApp(client_v36, href=vapp_resource.get('href'))
sysadmin_vapp = vcd_vapp.VApp(sysadmin_client_v36, href=vapp_resource.get('href'))
```

and use the right object as required by the operation?
</blockquote></details>

As agreed, this will be TODO for future R2 task with complete testing on using just-right vs admin previleged 
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1234 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1164#-MhojfcO63jt5bdAw2ne:-MhpDvXVA4dbz2PCq5SX:b-h56e5) ([raw file](https://github.com/vmware/container-service-extension/blob/ccd0e6a77ba1136863d4d5f7a853b8d6b6376730/container_service_extension/rde/backend/cluster_service_2_x.py#L1234)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

@ltimothy7 what is the use of this?

I think the KUBECONFIG should still use the external exposed IP itself. What intra-cluster operation needs the kubeconfig?
</blockquote></details>

Separate thread of discussion is opened for this


<!-- Sent from Reviewable.io -->

2021-08-23 22:58 UTC, merged