TKGm with @sakthisunda changes for removal of guest customization libraries
vmware/container-service-extension pull request #1179
Opened 2021-09-01 03:36 UTC by arunmk

There is a series of changes here geared towards TKGm effort. Since @sakthisunda's changes diverged quite a bit from @ltimothy7 's codebase, I took all of @ltimothy7 's code and overwrote the cluster_service_tkgm file with the cluster_service_2_x file and began to make changes to get things working. While doing that some of @ltimothy7 's changes were re-applied while a few ones were added.

The overall changes made over @sakthisunda 's code are:
1. some isolated locations where the TKGm constants need to be added in order to get basic things like `vcd cse cluster list` working and `cse server run`
2. some changes needed to get template using only name and not revision; additional changes to use template name rather than catalog_item_name while creating a vm
3. removal of upgrade codepaths, nfs codepaths, docker related content
4. Merging scripts of @sakthisunda and @ltimothy7
5. Addition of google nameservers to resolv.conf
6. Addition of some states to script execution.

In addition to the above, there was a serious vSphere (7.0.2) bug which affected ubuntu 20.04.2. The issue was the deployPkg scripts of vSphere do not wait for dbus service to be started before using hostnamectl, and hence they fail. However the precustomization script is executed correctly, and the postcustomization script is installed correctly into the post-customize.service. There needs to be a reboot triggered after this, but it is not don because the deployPkg script failed due to the dbus issue. In order to work around this, we use the following workaround:
1. In precustomization, set a vmtools variable to indicate that precustomization is completed.
2. In the CSE server code, look for this variable and wait for 60s after this, in order to let the rest of deployPkg to complete. This is important since it involves network setup.
3. After the timeout, CSE server reboots the node. This triggers run of the post-customize.service which executes the postcustomization section of the script.

There is one more detail to this bug: the hostnamectl was supposed to set the hostname of the VM. However, since it failed, the hostname remains as localhost and kubeadm does not like it. Hence there were code changes made in order to supply the `target_vm_name` into the postcustomization script and set this value as part of postcustomization. This works because the dbus service and hostnamectl are started correctly after the reboot (in fact, even before the reboot at the end of the timeout).

2021-09-01 18:36 UTC, ltimothy7 requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: all files reviewed, 13 unresolved discussions (waiting on @arunmk, @rocknes, and @sakthisunda)

___
*[cluster_scripts/v2_x/control_plane_customization.sh, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXFggn9QjL8MyhVID4:-MiXFggn9QjL8MyhVID5:b-vx999h) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x/control_plane_customization.sh#L73)):*
> ```Shell
> echo "$(date) post customization script execution completed" &>> /var/log/cse/customization/status.log
> 
> exit 0
> ```

nit: I think there is a missing newline because the UI here shows two rectangles
___
*[cluster_scripts/v2_x/node.sh, line 16 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXFqVP7AsxwGpcMVI6:-MiXFqVP7AsxwGpcMVI7:blz7xh7) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x/node.sh#L16)):*
> ```Shell
> set -e
> 
> if [[ x$1 != x"postcustomization" ]];
> ```

@arunmk If the phase is not postcustomization, will this node script or the control plane script get executed?
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXGm8J6egvlKQG0a4H:-MiXGm8J6egvlKQG0a4I:b-vdwn2t) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L48)):*
> ```Shell
> 
> vmtoolsd --cmd "info-set guestinfo.postcustomization.store.sshkey.status in_progress"
>   ssh_key="{ssh_key}"
> ```

Should this section be indented back?
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 59 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXGuzd9Q1hOcbgikH4:-MiXGuzd9Q1hOcbgikH5:br2e8u9) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L59)):*
> ```Shell
> 
> vmtoolsd --cmd "info-set guestinfo.postcustomization.nameserverconfig.resolvconf.status in_progress"
>   echo 'nameserver 8.8.8.8
> ```

Should this also be indented back?
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 68 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXHEmk549SQCBIukDt:-MiXHEmk549SQCBIukDu:bh6j6hn) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L68)):*
> ```Shell
> vmtoolsd --cmd "info-set guestinfo.postcustomization.kubeinit.status in_progress"
>   # tag images
>   coredns_image_version=""
> ```

indenting may also be off here and elsewhere in the script. 
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 88 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXHcjTDUH0c12p8aeK:-MiXHcjU79ySmcRR_Sv0:bhq29sg) ([raw file](https://github.com/vmware/container-service-extension/blob/2532c5cf3084abdb14eab207f53c603a1c8bd47c/cluster_scripts/v2_x_tkgm/control_plane.sh#L88)):*
> ```Shell
> 
> # TODO: look into if not https vcd host
> sed -i 's/BASE64_USERNAME/{base64_username}/; s/BASE64_PASSWORD/{base64_password}/' $vcloud_basic_auth_path
> ```

shouldn't we still be using these 2 sed commands to set the auth and configmap files?
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 159 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiX_jVL3AZWK-Q4UNEZ:-MiX_jVM7LDRRGsf2UtS:b-kafk7l) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L159)):*
> ```Shell
> 
> echo "$(date) post customization script execution completed" &>> /var/log/cse/customization/status.log
> exit 0
> ```

Should there be logic that handles if there is an exposed ip?
___
*[cluster_scripts/v2_x_tkgm/node.sh, line 75 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXHtZZ-j8_jOq2_8jH:-MiXHtZZ-j8_jOq2_8jI:bydhe8r) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/node.sh#L75)):*
> ```Shell
> echo "$(date) post customization script execution completed" &>> /var/log/cse/customization/status.log
> 
> exit 0
> ```

nit: newline needed
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 566 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXYN1p861nWXoKR6j-:-MiXYN1p861nWXoKR6j0:b-vcp39q) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L566)):*
> ```Python
>         desired_template_revision = input_native_entity.spec.distribution.template_revision  # noqa: E501
>         if current_template_name != desired_template_name or current_template_revision != desired_template_revision:  # noqa: E501
>             raise Exception("Looks like an upgrade is required. Upgrades not supported in this version of CSE")
> ```

Since upgrades should still be supported for native clusters and we are in the TKGm service, could we change the message to say that upgrades are not supported for TKGm clusters?
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1926 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiX_H4P5gFPs6MdkAL4:-MiX_H4P5gFPs6MdkAL5:bebh5cn) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1926)):*
> ```Python
>                 pod_cidr=TKGM_DEFAULT_POD_NETWORK_CIDR,
>                 cluster_kind=template[LocalTemplateKey.KIND],
>                 k8s_version=template[LocalTemplateKey.KUBERNETES_VERSION],
> ```

The control plane customization script doesn't have cluster_kind, k8s_version, and cni_version
Note: expose_ip is not currently in the control plane customization script
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1962 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXaJD9-oeaPlm0QrF2:-MiXaJD9-oeaPlm0QrF3:b-y25wdw) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1962)):*
> ```Python
>                     service_cidr=TKGM_DEFAULT_SERVICE_CIDR,
>                     pod_cidr=TKGM_DEFAULT_POD_NETWORK_CIDR,
>                     cluster_kind=template[LocalTemplateKey.KIND],
> ```

cluster_kind, k8s_version, and cni_version are also not used here
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1994 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXapA51TOUMcGXA3Ju:-MiXapA51TOUMcGXA3Jv:b-yxcq3i) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1994)):*
> ```Python
> 
>             # once precustomization is done, wait for a minute and reboot the node
>             time.sleep(60)
> ```

is there another condition we can poll here? or is sleep the only solution?
___
*[cse_def_schema/schema_2_0_0.json, line 36 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXdUGE2Z8BRu5FtJwY:-MiXdUGE2Z8BRu5FtJwZ:b-7kqfuo) ([raw file](https://github.com/vmware/container-service-extension/blob/2532c5cf3084abdb14eab207f53c603a1c8bd47c/cse_def_schema/schema_2_0_0.json#L36)):*
> ```JSON
>             "required":[ [...]

2021-09-01 19:18 UTC, sakthisunda reviewed
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: all files reviewed, 17 unresolved discussions (waiting on @arunmk and @rocknes)

*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXhNFN5dAnSOC7zVDm:-MiXhNFN5dAnSOC7zVDn:b133ry8) (no related file):*
v2_x/*.sh should not be ignored for merge as they are reverted to work with old way of customization by running scripts thru vsphere guest tools.

---
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 94 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXmi0p0Oc_KQZSwq8Q:-MiXiL7U9H3pqI1H2fxk:bqa2tdh) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L94)):*
> ```Python
>             api_version=DEFAULT_API_VERSION)
>         self.entity_svc = def_entity_svc.DefEntityService(
>             cloudapi_client=cloudapi_client_v36, vcd_client=client_v36)
> ```

This requires <b>entity_service.py</b> changes as part of this review. 
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 202 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXiuTf8xAUzZubMqdO:-MiXiuTf8xAUzZubMqdP:b-giuavd) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L202)):*
> ```
> # Get kube config from RDE else fallback to control plane vm
this comment is not valid anymore as we decided not to fallback
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1970 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXliuE1ADtQBUeO7bL:-MiXliuE1ADtQBUeO7bM:biabxuf) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1970)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>                 task = vm.update_guest_customization_section(
>                     enabled=True,
>                     customization_script=cust_script)
>                 sysadmin_client.get_task_monitor().wait_for_status(
>                     task,
>                     callback=wait_for_update_customization
>                 )
> ```
</details>

Since <b>expose_ip</b> is no more used in control_plane.sh,  update_guest_customization_sectioon may be redundant.  


<!-- Sent from Reviewable.io -->

2021-09-02 21:06 UTC, sakthisunda requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: 7 of 12 files reviewed, 18 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sakthisunda)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 130 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MicJ-581uLPF-I3OEb4:-MicJ-581uLPF-I3OEb5:b-bsphdt) ([raw file](https://github.com/vmware/container-service-extension/blob/8336a5edc8ad046d2e2725b7b5fed523907ba172/cluster_scripts/v2_x_tkgm/control_plane.sh#L130)):*
> ```Shell
> kubernetesVersion: $kubernetes_version
> ---" > /root/kubeadm-defaults.conf
>   kubeadm init --config $kubeadm_config_path > /root/kubeadm-init.out
> ```

This logic is missing:
if [[ ! -z "$control_plane_end_point" ]];
        kubeadm init --control-plane-endpoint=

Please click on this to refer:<a href="https://github.com/vmware/container-service-extension/blob/f8ede1b07f3731c5d4a9b698cc580cb4de43ea34/cluster_scripts/v2_x/control_plane_customization.sh">control_plane_customization-before-revert</a>


<!-- Sent from Reviewable.io -->

2021-09-02 21:10 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: 7 of 12 files reviewed, 18 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sakthisunda)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 130 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MicJ-581uLPF-I3OEb4:-MicKx4J2KiyTZKhbBHI:bi1w850) ([raw file](https://github.com/vmware/container-service-extension/blob/8336a5edc8ad046d2e2725b7b5fed523907ba172/cluster_scripts/v2_x_tkgm/control_plane.sh#L130)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

This logic is missing:
if [[ ! -z "$control_plane_end_point" ]];
        kubeadm init --control-plane-endpoint=

Please click on this to refer:<a href="https://github.com/vmware/container-service-extension/blob/f8ede1b07f3731c5d4a9b698cc580cb4de43ea34/cluster_scripts/v2_x/control_plane_customization.sh">control_plane_customization-before-revert</a>
</blockquote></details>

Please click on this to refer: <a href="https://github.com/sakthisunda/container-service-extension/blob/97af42547e0541fac7cf4b24626e113de75b9ad8/cluster_scripts/v2_x/control_plane_customization.sh">control_plane_customization_before_revert</a>


<!-- Sent from Reviewable.io -->

2021-09-03 17:27 UTC, sakthisunda reviewed
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: 7 of 12 files reviewed, 16 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sakthisunda)



<!-- Sent from Reviewable.io -->

2021-09-03 18:24 UTC, arunmk commented
*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXnNxx4OKv2rdhGdt1:-Migtr4EE7jdC0O6kwJV:b-896fix) (no related file):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Sorry for the typo:
v2_x/*.sh <b>should be ignored</b> for merge as they are reverted to work with old way of customization by running scripts thru vsphere guest tools.

</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-09-03 18:24 UTC, arunmk commented
*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXhNFN5dAnSOC7zVDm:-MigtucNEeLDY9RtJfYN:bwvyox4) (no related file):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

v2_x/*.sh should not be ignored for merge as they are reverted to work with old way of customization by running scripts thru vsphere guest tools.
</blockquote></details>

Reverted

---


<!-- Sent from Reviewable.io -->

2021-09-03 18:25 UTC, arunmk commented
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXGm8J6egvlKQG0a4H:-Migu-5H3dRXQ-aeBZq5:b1scd9c) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L48)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should this section be indented back?
</blockquote></details>

I have used this common pattern to help code readability:
vmtoolsd set start status
    <indented code>
vmtoolsd set end status

This should help us know where the section starts and ends cleanly.


<!-- Sent from Reviewable.io -->

2021-09-03 18:26 UTC, arunmk commented
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 68 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXHEmk549SQCBIukDt:-MiguFjxBQfEvqH_WI6J:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L68)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

indenting may also be off here and elsewhere in the script. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 18:26 UTC, arunmk commented
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 130 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MicJ-581uLPF-I3OEb4:-MiguHnt1F_-Jpuuyqzj:bvlxzoy) ([raw file](https://github.com/vmware/container-service-extension/blob/8336a5edc8ad046d2e2725b7b5fed523907ba172/cluster_scripts/v2_x_tkgm/control_plane.sh#L130)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Please click on this to refer: <a href="https://github.com/sakthisunda/container-service-extension/blob/97af42547e0541fac7cf4b24626e113de75b9ad8/cluster_scripts/v2_x/control_plane_customization.sh">control_plane_customization_before_revert</a>
</blockquote></details>

Thanks @sakthisunda . I have added changes to handle expose cleanly.


<!-- Sent from Reviewable.io -->

2021-09-03 18:27 UTC, arunmk commented
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 88 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXHcjTDUH0c12p8aeK:-MiguNCRE2aqZDlJXUk5:b-wnnutp) ([raw file](https://github.com/vmware/container-service-extension/blob/2532c5cf3084abdb14eab207f53c603a1c8bd47c/cluster_scripts/v2_x_tkgm/control_plane.sh#L88)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

shouldn't we still be using these 2 sed commands to set the auth and configmap files?
</blockquote></details>

For beta, we will not set the auth files since they will need to be done by the cluster creator later (plan B). For R1, we will use the auth in order to set the machine user token. 


<!-- Sent from Reviewable.io -->

2021-09-03 18:28 UTC, arunmk commented
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 159 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiX_jVL3AZWK-Q4UNEZ:-MiguiY764rKUOYun5u6:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L159)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should there be logic that handles if there is an exposed ip?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 18:29 UTC, arunmk commented
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 94 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXmi0p0Oc_KQZSwq8Q:-MiguvTi5U4uc9JA7kd6:b-xfxv13) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L94)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

This requires <b>entity_service.py</b> changes as part of this review. 
</blockquote></details>

hmm...I will ensure that it is picked up as part of rebase.


<!-- Sent from Reviewable.io -->

2021-09-03 18:29 UTC, arunmk commented
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 202 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXiuTf8xAUzZubMqdO:-Migv8Ib9oXVrdqJ59GS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L202)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> # Get kube config from RDE else fallback to control plane vm
this comment is not valid anymore as we decided not to fallback

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 18:30 UTC, arunmk commented
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 566 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXYN1p861nWXoKR6j-:-MigvJlL0Ug_ibriox_3:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L566)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Since upgrades should still be supported for native clusters and we are in the TKGm service, could we change the message to say that upgrades are not supported for TKGm clusters?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 18:32 UTC, arunmk commented
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1994 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXapA51TOUMcGXA3Ju:-MigvX1i5dVEYXdp-bFf:b49xuh0) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1994)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

is there another condition we can poll here? or is sleep the only solution?
</blockquote></details>

I have changed this mechanism to poll for a future state. After that as well a sleep is needed but it is much smaller and more reliable.


<!-- Sent from Reviewable.io -->

2021-09-03 18:32 UTC, arunmk commented
___
*[cse_def_schema/schema_2_0_0.json, line 36 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXdUGE2Z8BRu5FtJwY:-MigviC58oZvjVy0RVLj:bd66gl9) ([raw file](https://github.com/vmware/container-service-extension/blob/2532c5cf3084abdb14eab207f53c603a1c8bd47c/cse_def_schema/schema_2_0_0.json#L36)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

should this still be used for native templates?
</blockquote></details>

I have reverted this change.


<!-- Sent from Reviewable.io -->

2021-09-03 18:32 UTC, arunmk commented
___
*[cluster_scripts/v2_x/control_plane_customization.sh, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXFggn9QjL8MyhVID4:-Migvmh-CTI11Xr-rOT4:b509rdd) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x/control_plane_customization.sh#L73)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: I think there is a missing newline because the UI here shows two rectangles
</blockquote></details>

I have reverted this change


<!-- Sent from Reviewable.io -->

2021-09-03 18:32 UTC, arunmk commented
___
*[cluster_scripts/v2_x/node.sh, line 16 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXFqVP7AsxwGpcMVI6:-Migvpke12Sql5qdV3zj:b509rdd) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x/node.sh#L16)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

@arunmk If the phase is not postcustomization, will this node script or the control plane script get executed?
</blockquote></details>

I have reverted this change


<!-- Sent from Reviewable.io -->

2021-09-03 18:33 UTC, arunmk commented
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 59 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXGuzd9Q1hOcbgikH4:-MiguEPL6Dbx0KT5gWDi:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/cluster_scripts/v2_x_tkgm/control_plane.sh#L59)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should this also be indented back?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 18:33 UTC, arunmk commented
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1970 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXliuE1ADtQBUeO7bL:-MigvQJn2SjP3OoaBsVs:b-4wuecv) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1970)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
>                 task = vm.update_guest_customization_section(
>                     enabled=True,
>                     customization_script=cust_script)
>                 sysadmin_client.get_task_monitor().wait_for_status(
>                     task,
>                     callback=wait_for_update_customization
>                 )
> ```
Since <b>expose_ip</b> is no more used in control_plane.sh,  update_guest_customization_sectioon may be redundant.  
</blockquote></details>

I have added it now.


<!-- Sent from Reviewable.io -->

2021-09-03 18:38 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: 4 of 13 files reviewed, 17 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 94 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXmi0p0Oc_KQZSwq8Q:-MigwuUQEMfHSfjKXWob:b-p8hjm1) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L94)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

hmm...I will ensure that it is picked up as part of rebase.
</blockquote></details>

Alternatively, this change may not be required for now. Because, we update the cluster still as sy admin. 
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 99 at r9](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MigxA5x3Fw-AYaWARaW:-MigxA5x3Fw-AYaWARaX:b-mar2c7) ([raw file](https://github.com/vmware/container-service-extension/blob/da7d78dfdcf0c7aba85dc9d5ab17552616c41ba0/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L99)):*
> ```Python
>             cloudapi_client=sysadmin_cloudapi_client_v36,
>             vcd_client=client_v36
>         )
> ```

Alternatively, this change may not be required for now. Because, we update the cluster still as sy admin. Alternatively, this change may not be required for now. Because, we update the cluster still as sy admin. 


<!-- Sent from Reviewable.io -->

2021-09-03 18:58 UTC, ltimothy7 approved these changes
> Reviewed 1 of 4 files at r2, 1 of 4 files at r4, 1 of 2 files at r5, 2 of 3 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: all files reviewed, 11 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sakthisunda)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 88 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXHcjTDUH0c12p8aeK:-Mih-b7-6H4wXumabWJZ:b-6ze8ts) ([raw file](https://github.com/vmware/container-service-extension/blob/2532c5cf3084abdb14eab207f53c603a1c8bd47c/cluster_scripts/v2_x_tkgm/control_plane.sh#L88)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

For beta, we will not set the auth files since they will need to be done by the cluster creator later (plan B). For R1, we will use the auth in order to set the machine user token. 
</blockquote></details>

That makes sense for `vcloud-basic-auth`
But  we will still need to pass in the parameters for the configmap, so I think that sed command should be left


<!-- Sent from Reviewable.io -->

2021-09-03 19:06 UTC, sakthisunda approved these changes
> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 1 of 3 files at r7, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: all files reviewed, 10 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sakthisunda)



<!-- Sent from Reviewable.io -->

2021-09-04 02:19 UTC, arunmk commented
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 88 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXHcjTDUH0c12p8aeK:-MiiaVgGBorBeKMkNXjs:b-v028li) ([raw file](https://github.com/vmware/container-service-extension/blob/2532c5cf3084abdb14eab207f53c603a1c8bd47c/cluster_scripts/v2_x_tkgm/control_plane.sh#L88)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

That makes sense for `vcloud-basic-auth`
But  we will still need to pass in the parameters for the configmap, so I think that sed command should be left
</blockquote></details>

Will add this with the CPI/CSI changes


<!-- Sent from Reviewable.io -->

2021-09-04 02:20 UTC, arunmk commented
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 94 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXmi0p0Oc_KQZSwq8Q:-Miiadv-82b1MaQC2ard:bxldedx) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L94)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Alternatively, this change may not be required for now. Because, we update the cluster still as sy admin. 
</blockquote></details>

I have rebased and taken the changes as needed.


<!-- Sent from Reviewable.io -->

2021-09-04 02:20 UTC, arunmk commented
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 99 at r9](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MigxA5x3Fw-AYaWARaW:-Miialoo9h26Gtjgjps9:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/da7d78dfdcf0c7aba85dc9d5ab17552616c41ba0/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L99)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Alternatively, this change may not be required for now. Because, we update the cluster still as sy admin. Alternatively, this change may not be required for now. Because, we update the cluster still as sy admin. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-04 02:24 UTC, arunmk reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1179)* status: 6 of 13 files reviewed, 9 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1926 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiX_H4P5gFPs6MdkAL4:-Miiap3v2dqIKN2ysfuJ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1926)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

The control plane customization script doesn't have cluster_kind, k8s_version, and cni_version
Note: expose_ip is not currently in the control plane customization script
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1962 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1179#-MiXaJD9-oeaPlm0QrF2:-MiiarN53M2EPjnuXHV2:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ee04e33098386750cf10ad74c0eea5544e7be6cc/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1962)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

cluster_kind, k8s_version, and cni_version are also not used here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-04 02:41 UTC, merged