[VCDA-2571] Use cpu/mem fields for native cluster operations
vmware/container-service-extension pull request #1181
Opened 2021-09-02 14:53 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

CPU and memory fields should be allowed only for native and TKG+
* User cannot specify both  cpu/ memory and sizing class during cluster deployment
* If cluster is created using cpu/memory, it cannot be resized using sizing class and vice-versa
* cse upgrade should add the cpu and memory fields in the spec section if the cluster is upgraded from legacy mode to non-legacy mode.

Testing done:
* create cluster
* resize cluster (up and down)
* cse upgrade with existing clusters

@sakthisunda @rocknes

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1181)

2021-09-02 16:12 UTC, sakthisunda approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1181)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 455 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1181#-MibGiqBBS1wrvxYZHBe:-MibGaA8CKrbkywyyXC0:b-tbi4f0) ([raw file](https://github.com/vmware/container-service-extension/blob/438f0ebce353951624829ef8daa8efd635c77bb8/container_service_extension/rde/models/rde_2_0_0.py#L455)):*
> ```Python
>             ssh_key='')
>         control_plane_nodes = cluster['master_nodes']
>         topology_contorl_plane = ControlPlane(
> ```


nit: topology_control_plane
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 466 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1181#-MibGpp4DG-YJgSIMLlQ:-MibGlOpDtBhIJENxtw_:behuwrq) ([raw file](https://github.com/vmware/container-service-extension/blob/438f0ebce353951624829ef8daa8efd635c77bb8/container_service_extension/rde/models/rde_2_0_0.py#L466)):*
> ```Python
>         if kind != shared_constants.ClusterEntityKind.TKG_M.value and len(workers) > 0:  # noqa: E501
>             topology_contorl_plane.cpu = control_plane_nodes[0]['numberOfCpus']
>             topology_contorl_plane.memory = control_plane_nodes[0]['memoryMB']
> ```


nit: topology_control_plane
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 471 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1181#-MibGsYI9k7L7cHH8WGj:-MibGsYI9k7L7cHH8WGk:b-nfkjlo) ([raw file](https://github.com/vmware/container-service-extension/blob/438f0ebce353951624829ef8daa8efd635c77bb8/container_service_extension/rde/models/rde_2_0_0.py#L471)):*
> ```Python
>         topology = Topology(
>             workers=topology_workers,
>             control_plane=topology_contorl_plane,
> ```

nit: topology_control_plane


<!-- Sent from Reviewable.io -->

2021-09-03 18:13 UTC, sahithi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1181#-:-MigrRKl6nz7lhM4oOoG:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2350 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Mignn4NBhJL9L5_7MUX:-Mignn4NBhJL9L5_7MUY:b-1hw3xe) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/backend/cluster_service_2_x.py#L2350)):*
> ```Python
> 
>     if (cpu_count or memory_mb) and sizing_class_name:
>         raise exceptions.BadRequestError("Cannot specify both cpu/memory and "
> ```

It is recommended to raise bad requests from the Handler layer. Raise Bad requests from the backend if and only if the handler doesn't have enough data to identify the bad request (or) if it's too logic-heavy at the handler layer.

I suggest adding this logic to the input spec validator in the handler? 
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 620 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Migptw64QJL0ZeSXOrg:-Migptw64QJL0ZeSXOrh:brtc7j) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/models/rde_2_0_0.py#L620)):*
> ```Python
>         del native_entity_dict['spec']['settings']['network']['services']
> 
>         if k8_runtime != shared_constants.ClusterEntityKind.TKG_M.value:
> ```

I suggest deleting the cpu and memory properties from the "vcd cse cluster sample -tkgm" output and the "vcd cse cluster info" output. of tkgm clusters. I know this requires conditional logic based on TKGm, but this would prevent any potential confusion for the users. 

@anirudh9794 See if this is straightforward.

@rocknes @arunmk  what do you both think? 
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 80 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-MigpSj63DpRtPU13wTZ:-MigpSj7A6es3kf5MG4E:b-m3d2zm) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/validators/validator_rde_2_x.py#L80)):*
> ```Python
>                     bad_request_msg = "Cannot specify both sizing class and cpu/memory for Control Plane nodes." # noqa: E501
>                 if bad_request_msg:
>                     raise BadRequestError(bad_request_msg)
> ```

I see that you are raising the Bad request in the validator. Ignore my comment earlier.


<!-- Sent from Reviewable.io -->

2021-09-03 18:53 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1181)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2350 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Mignn4NBhJL9L5_7MUX:-MigxZc-Awcj5PdY_tC9:b-kficy2) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/backend/cluster_service_2_x.py#L2350)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

It is recommended to raise bad requests from the Handler layer. Raise Bad requests from the backend if and only if the handler doesn't have enough data to identify the bad request (or) if it's too logic-heavy at the handler layer.

I suggest adding this logic to the input spec validator in the handler? 
</blockquote></details>

Bad request error will be thrown during cluster creation in the handler layer if both sizing policy and cpu/mem is used. During cluster resize, validators will make sure that the cluster created with cpu/mem are not being resized using sizing policy parameter.
I can remove this check but I felt it was okay to validate at two different places.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 620 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Migptw64QJL0ZeSXOrg:-MigyISvCmVDnIKKVGg3:brk724c) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/models/rde_2_0_0.py#L620)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest deleting the cpu and memory properties from the "vcd cse cluster sample -tkgm" output and the "vcd cse cluster info" output. of tkgm clusters. I know this requires conditional logic based on TKGm, but this would prevent any potential confusion for the users. 

@anirudh9794 See if this is straightforward.

@rocknes @arunmk  what do you both think? 
</blockquote></details>

Thanks for catching this, The logic seems to be wrong here . I intended to remove cpu/memory fields for TKGm clusters here.
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 80 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-MigpSj63DpRtPU13wTZ:-Migyc9Q7dMf-wARurPP:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/validators/validator_rde_2_x.py#L80)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I see that you are raising the Bad request in the validator. Ignore my comment earlier.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 19:00 UTC, rocknes requested changes
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1181)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2126 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Mih-zAx6OVx43d1BWhi:-Mih-zAy7rTOXPYWuzAt:b-lbv8ws) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/backend/cluster_service_2_x.py#L2126)):*
> ```Python
>                     get_cse_policy_display_name(policy_name)
>             vm_obj = vcd_vm.VM(sysadmin_client, resource=vm)
>             cpu_count = vm_obj.get_cpus()['num_cpus']
> ```

I think the cpu count and memory_mb field should be populated only if sizing_class is none.. 

This particular method is used to sync the rde with VApp, as a result after few sync's we will be unable to differentiate between clusters that were initialized with cpu + mem vs the ones initialized with sizing policy.
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 68 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Mih1-MjB1k2nOquyy1k:-Mih1-Mk9H3Xw1MS8WR1:blkx6s5) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/validators/validator_rde_2_x.py#L68)):*
> ```Python
> 
>         # Return True if the operation is not specified.
>         if operation == BehaviorOperation.CREATE_CLUSTER:
> ```

What if someone specifies both during cluster update?


<!-- Sent from Reviewable.io -->

2021-09-03 19:07 UTC, Anirudh9794 commented
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2126 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Mih-zAx6OVx43d1BWhi:-Mih1pUI2gSFFYC4n_cs:b53fcbc) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/backend/cluster_service_2_x.py#L2126)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think the cpu count and memory_mb field should be populated only if sizing_class is none.. 

This particular method is used to sync the rde with VApp, as a result after few sync's we will be unable to differentiate between clusters that were initialized with cpu + mem vs the ones initialized with sizing policy.
</blockquote></details>

This section only populates the status section. Andrew asked if its possible to populate cpu and memory because UI will be able to display more accurate information.
I think we decided that it is okay to populate both cpu+mem and sizing class.

While creating the spec from status section, if sizing class is used, CPU+ memory fields will be set to `None`. Likewise, if sizing class is not set, then CPU and memory fields will be populated.


<!-- Sent from Reviewable.io -->

2021-09-03 19:07 UTC, Anirudh9794 commented
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 68 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Mih1-MjB1k2nOquyy1k:-Mih1__tASsU2h4irxic:b-qq472f) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/validators/validator_rde_2_x.py#L68)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

What if someone specifies both during cluster update?
</blockquote></details>

If they specify both, the validator will complain that one of cpu/mem or sizing class is immutable.


<!-- Sent from Reviewable.io -->

2021-09-03 19:18 UTC, rocknes approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1181#-:-Mih59xJD_R8l10oAfPD:bnfp4nl)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2126 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Mih-zAx6OVx43d1BWhi:-Mih4xxP4HQNc4OUWfob:b2u4b1f) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/backend/cluster_service_2_x.py#L2126)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This section only populates the status section. Andrew asked if its possible to populate cpu and memory because UI will be able to display more accurate information.
I think we decided that it is okay to populate both cpu+mem and sizing class.

While creating the spec from status section, if sizing class is used, CPU+ memory fields will be set to `None`. Likewise, if sizing class is not set, then CPU and memory fields will be populated.
</blockquote></details>

Sounds good. thanks for the clarificaiton
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 620 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1181#-Migptw64QJL0ZeSXOrg:-Mih54CQAazctb39KP4t:b-fqkxj) ([raw file](https://github.com/vmware/container-service-extension/blob/ea8d24b46b75e835203a2255039c20796995bea6/container_service_extension/rde/models/rde_2_0_0.py#L620)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Thanks for catching this, The logic seems to be wrong here . I intended to remove cpu/memory fields for TKGm clusters here.
</blockquote></details>

the current logic will filter the fields for native :))


<!-- Sent from Reviewable.io -->

2021-09-03 22:36 UTC, merged