[VCDA-3192] Remove dependency on config file from the commands `cse template import`
vmware/container-service-extension pull request #1281
Opened 2022-01-10 16:48 UTC by rocknes

* Made the -c/--config param optional
* Added -x/--extra-option new param, this param takes two strings as input (key-value), this param can be repeated
* In case --config option is not provided by user, the -x params are used to create a dummy config dictionary in memory and passed onto the following methods
* Every method in the template import workflow that depends on config has been redesign to explicitly state the actual fields of config it uses. This helps immensely to narrow down the scope of the dummy config file.
* A minimum set of required fields have been defined, if all of them is not specified by -x option, CSE will prompt the user to enter them interactively.
* Additional care has been given to make sure that type-casting is done properly to the input key-value (str, str) pair received via -x option.

Testing Done:
Ran the command `cse template import`
1. without -c and -x options. Got prompted for all the required details
2. without -c and partial -x options. Got prompted for only the missing details
3. without -c and all required -x options. No prompt, command executed as normal.

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

2022-01-11 18:39 UTC, ltimothy7 requested changes
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/server/cli/server_cli.py, line 1605 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9QDTp477co1gB0TZY:-Mt9QDTp477co1gB0TZZ:bf6v9a0) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1605)):*
> ```Python
> 
>     # Prompt user for missing required options
>     for k, option in required_options.items():
> ```

I think it would be more straightforward if this function didn't also do the prompting. I think the caller function should check if all of the required options are added. Then, this function can just construct the config.

This would avoid adding the user input again after the additional values are retrieved.


<!-- Sent from Reviewable.io -->

2022-01-11 18:41 UTC, rocknes reviewed
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)

___
*[container_service_extension/server/cli/server_cli.py, line 1605 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9QDTp477co1gB0TZY:-Mt9RSByBuoXwSLqCnw-:bkry04c) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1605)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think it would be more straightforward if this function didn't also do the prompting. I think the caller function should check if all of the required options are added. Then, this function can just construct the config.

This would avoid adding the user input again after the additional values are retrieved.

</blockquote></details>

Makes sense, I will refactor. Thanks.


<!-- Sent from Reviewable.io -->

2022-01-11 20:26 UTC, sahithi reviewed
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @rocknes)

___
*[container_service_extension/server/cli/server_cli.py, line 1295 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9m2HpB4dEYwOUdMid:-Mt9m2HqEJQJ01EtWND0:bsfkr59) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1295)):*
> ```Python
>     type=(str, str),
>     multiple=True,
>     help='Extra options passed as -x key value'
> ```

Help string can be more descriptive on when/why this needs to be used? and with the combination of what other options?
___
*[container_service_extension/server/cli/server_cli.py, line 1303 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9l-Yo0OyAKdC1e6Q8:-Mt9l-Yo0OyAKdC1e6Q9:bv4anhs) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1303)):*
> ```Python
>         ova_file_path,
>         force_import,
>         extra_options
> ```

If "extra options" can prompt users with "required options" messages, then I suggest renaming.
How about "upload_options" ?
___
*[container_service_extension/server/cli/server_cli.py, line 1307 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9mkhx7Y1Lv1UDWAfG:-Mt9mkhx7Y1Lv1UDWAfH:b8h4inx) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1307)):*
> ```Python
>     """Upload TKGm OVA to CSE catalog.
> 
>     \b
> ```

Can you also add a few examples of the command usage?
___
*[container_service_extension/server/cli/server_cli.py, line 1312 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9g__c5zaQd5V3l_xn:-Mt9g__c5zaQd5V3l_xo:bhpximj) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1312)):*
> ```Python
>             imported.
>         broker.org: String: Name of the Organization where the OVA will be
>             imported.
> ```

I understand that you named the keys in such a way that we can construct the config dict out of it easily.
It is more user-intuitive to use the term "catalog" rather than "broker.catalog". Users may begin to wonder what the broker is all about.

Can we use simpler keys and let the code deal with the needed retrofitting?

Another option is to take a yaml input.  It becomes easier for users to populate the yaml all at once and reuse it. I know it's a bit late for this suggestion, but I think it is worth considering. We can provide the sample yaml either in the command help string (or) thru sample option

vcd:
..host:
..password:
..username:
..org:
..catalog:
ova_file:



_Code quote:_
```Python
        broker.catalog: String: Name of the catalog where the OVA will be
            imported.
        broker.org: String: Name of the Organization where the OVA will be
            imported.
        vcd.host: String: FQDN of VCD host.
        vcd.password: String: Password of CSE service account.
        vcd.username: String: Username of CSE service account.
```


<!-- Sent from Reviewable.io -->

2022-01-11 20:31 UTC, rocknes reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/server/cli/server_cli.py, line 1295 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9m2HpB4dEYwOUdMid:-Mt9ovsz2sTTZu0Ltk5Q:bebrt1w) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1295)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Help string can be more descriptive on when/why this needs to be used? and with the combination of what other options?
</blockquote></details>

Will do
___
*[container_service_extension/server/cli/server_cli.py, line 1303 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9l-Yo0OyAKdC1e6Q8:-Mt9p0leEZ_AvPdXNFLa:b9iziuv) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1303)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

If "extra options" can prompt users with "required options" messages, then I suggest renaming.
How about "upload_options" ?
</blockquote></details>

`extra options` is an industry standard though, generally used in bash.
___
*[container_service_extension/server/cli/server_cli.py, line 1307 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9mkhx7Y1Lv1UDWAfG:-Mt9p7gv7egUZAa2WPlN:bhy9ot6) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1307)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you also add a few examples of the command usage?
</blockquote></details>

Will do.
___
*[container_service_extension/server/cli/server_cli.py, line 1312 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9g__c5zaQd5V3l_xn:-Mt9pDZ_98S-8S4OQWXP:b-tz5ytc) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1312)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I understand that you named the keys in such a way that we can construct the config dict out of it easily.
It is more user-intuitive to use the term "catalog" rather than "broker.catalog". Users may begin to wonder what the broker is all about.

Can we use simpler keys and let the code deal with the needed retrofitting?

Another option is to take a yaml input.  It becomes easier for users to populate the yaml all at once and reuse it. I know it's a bit late for this suggestion, but I think it is worth considering. We can provide the sample yaml either in the command help string (or) thru sample option

vcd:
..host:
..password:
..username:
..org:
..catalog:
ova_file:



</blockquote></details>

I will add a second layer of display key to yaml key mapping, the change should be simple and straight forward. 
I really want to avoid accepting another yaml. It just makes the automation tedious and complicated.


<!-- Sent from Reviewable.io -->

2022-01-11 20:33 UTC, rocknes reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/server/cli/server_cli.py, line 1303 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9l-Yo0OyAKdC1e6Q8:-Mt9pmLXDe0a1ZUxMQLa:b4g6328) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1303)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

`extra options` is an industry standard though, generally used in bash.
</blockquote></details>

The use case is as follows,

If you don't specify the config file, you will get prompts but you want to automate the command, in that case, you specify the inputs via the --extra-option param.

The prompting is the primary behavior, extra options allows you to avoid the prompting.


<!-- Sent from Reviewable.io -->

2022-01-12 05:19 UTC, sahithi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> one question
What happens if the user misses out on providing all the required options using -x?

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281#-:-MtBha6H18NENlFLKorM:b-blx7an)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/server/cli/server_cli.py, line 1303 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9l-Yo0OyAKdC1e6Q8:-MtBCecc-jj67yOGKLry:bpdrd5k) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1303)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The use case is as follows,

If you don't specify the config file, you will get prompts but you want to automate the command, in that case, you specify the inputs via the --extra-option param.

The prompting is the primary behavior, extra options allows you to avoid the prompting.

</blockquote></details>

Got it. 
What happens if the user misses out on providing all the required options using -x?


<!-- Sent from Reviewable.io -->

2022-01-12 07:55 UTC, rocknes reviewed
The command will prompt and ask for the missing options.

> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281#-:-MtCGqJs4YoYMwDLs4Cq:b-x8utwp)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/server/cli/server_cli.py, line 1303 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1281#-Mt9l-Yo0OyAKdC1e6Q8:-MtCH0Ur4VJy2as9ZYIo:b-x8utwp) ([raw file](https://github.com/vmware/container-service-extension/blob/95b4b4cb2a0d1c08964b12cfdfd8c4c21bcddcbe/container_service_extension/server/cli/server_cli.py#L1303)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Got it. 
What happens if the user misses out on providing all the required options using -x?
</blockquote></details>

The command will prompt and ask for the missing options.


<!-- Sent from Reviewable.io -->

2022-01-12 17:27 UTC, ltimothy7 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1281)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)



<!-- Sent from Reviewable.io -->

2022-01-12 17:54 UTC, merged