Removed offensive terminology
vmware/container-service-extension pull request #735
Opened 2020-09-08 18:36 UTC by sahithi

Replaced below terms
master -> control_plane
abort -> cancel
kill -> stop

Script names, node names and cluster metadata are yet to be changed. Changing them would affect backward compatibility of Zeus release. Hence, these changes will be done post-zeus.

Signed-off-by: sahithi <sahithi.ayloo@gmail.com>

- (Optional) Names of reviewers using @ sign + name

2020-09-08 20:51 UTC, Anirudh9794 requested changes
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/735)* status: 11 of 12 files reviewed, 32 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/vcdbroker.py, line 777 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjMEOt2calwMJP5SSc:-MGjMEOt2calwMJP5SSd:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L777)):*
> ```Python
>             LOGGER.debug("No nodes specified to delete")
>             return {'body': {}}
>         # check that control_plane node is not in specified nodes
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 780 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjMDPJ43FJu91EQBz6:-MGjMDPJ43FJu91EQBz7:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L780)):*
> ```Python
>         for node in node_names_list:
>             if node.startswith(NodeType.CONTROL_PLANE):
>                 raise e.CseServerError(f"Can't delete control_plane node: '{node}'.")
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 867 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjMBUu0I78acx4e-_L:-MGjMBUu0I78acx4e-_M:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L867)):*
> ```Python
>             self.context.client.get_task_monitor().wait_for_status(task)
> 
>             msg = f"Creating control_plane node for cluster '{cluster_name}' " \
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 889 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjM6-P63_HEMocCAb2:-MGjM6-P63_HEMocCAb3:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L889)):*
> ```Python
>                            ssh_key=ssh_key)
>             except Exception as err:
>                 raise e.ControlPlaneNodeCreationError("Error adding control_plane node:",
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1177 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjLlSp4SAoa-TJozDu:-MGjLlSp4SAoa-TJozDv:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1177)):*
> ```Python
> 
>             if upgrade_k8s:
>                 msg = f"Draining control_plane node {control_plane_node_names}"
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1184 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjLie-3EBV0Sd3SQZS:-MGjLie0-Dc8OJTHXVr8:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1184)):*
> ```Python
> 
>                 msg = f"Upgrading Kubernetes ({c_k8s} -> {t_k8s}) " \
>                       f"in control_plane node {control_plane_node_names}"
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1195 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjLfYM9LqT8HlfkK9j:-MGjLfYM9LqT8HlfkK9k:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1195)):*
> ```Python
>                                      control_plane_node_names, script)
> 
>                 msg = f"Uncordoning control_plane node {control_plane_node_names}"
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1256 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjLcNF0z07tpgaUeGt:-MGjLcNF0z07tpgaUeGu:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1256)):*
> ```Python
>             if upgrade_cni:
>                 msg = f"Applying CNI ({cluster['cni']} {c_cni} -> {t_cni}) " \
>                       f"in control_plane node {control_plane_node_names}"
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1513 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjOl7B6IKi4CXhX6p1:-MGjOl7B6IKi4CXhX6p2:b-2zstkp) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1513)):*
> ```Python
> 
>         if vm_name.startswith(NodeType.CONTROL_PLANE):
>             cluster.get('master_nodes').append(node_info)
> ```

A constant can be used in place of this key to reduce the number of times this key is refereed.
___
*[container_service_extension/vcdbroker.py, line 1532 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjP4pZ3xfayPU4luUG:-MGjP4pZ3xfayPU4luUH:b1wqhel) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1532)):*
> ```Python
>     TODO define these cluster data dictionary keys better:
>         'name', 'vapp_id', 'vapp_href', 'vdc_name', 'vdc_href', 'vdc_id',
>         'leader_endpoint', 'control_plane_nodes', 'nodes', 'nfs_nodes',
> ```

this is still `master_nodes`
___
*[container_service_extension/vcdbroker.py, line 1818 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPE4_AC0ybHS4f1Hg:-MGjPE4_AC0ybHS4f1Hh:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1818)):*
> ```Python
>     vcd_utils.raise_error_if_not_sysadmin(sysadmin_client)
> 
>     LOGGER.debug(f"Getting control_plane IP for vapp: "
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1830 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPMCkAYyNmFf_rlkV:-MGjPMCkAYyNmFf_rlkW:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1830)):*
> ```Python
>     if errors:
>         raise e.ScriptExecutionError(f"Get control_plane IP script execution failed "
>                                      f"on control_plane node {node_names}:{errors}")
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1832 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPNgtB7Aq910FI02h:-MGjPNgtB7Aq910FI02i:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1832)):*
> ```Python
>                                      f"on control_plane node {node_names}:{errors}")
>     control_plane_ip = result[0][1].content.decode().split()[0]
>     LOGGER.debug(f"Retrieved control_plane IP for vapp: "
> ```

control_plane -> control plane
___
*[container_service_extension/vcdbroker.py, line 1875 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPfdp8Tad3st5Oc7O:-MGjPfdp8Tad3st5Oc7P:b-usf2cr) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1875)):*
> ```Pytho [...]

2020-09-09 20:32 UTC, sahithi reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/735)* status: 8 of 12 files reviewed, 32 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/vcdbroker.py, line 1195 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjLfYM9LqT8HlfkK9j:-MGoZ4CaDPsPAIE75Kyb:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1195)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/vcdbroker.py, line 1256 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjLcNF0z07tpgaUeGt:-MGoZ5lV2IUNPbSe_GBU:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1256)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/vcdbroker.py, line 1513 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjOl7B6IKi4CXhX6p1:-MGoQD953DefHPLOn3uk:brynli) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1513)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

A constant can be used in place of this key to reduce the number of times this key is refereed.
</blockquote></details>

Agreed. I prefer not to do this as part of this change-set.
___
*[container_service_extension/vcdbroker.py, line 1532 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjP4pZ3xfayPU4luUG:-MGoSiY47fE_9kFAQJ3r:b-sx0b7w) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1532)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

this is still `master_nodes`
</blockquote></details>

Thanks, good catch.
___
*[container_service_extension/vcdbroker.py, line 1818 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPE4_AC0ybHS4f1Hg:-MGoZ6R_8FAtXSNV1_df:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1818)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/vcdbroker.py, line 1830 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPMCkAYyNmFf_rlkV:-MGoZ7E5D2s8Tn5KYC-e:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1830)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/vcdbroker.py, line 1832 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPNgtB7Aq910FI02h:-MGoZ7iU0aOEK6Pj5nqz:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1832)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/vcdbroker.py, line 1875 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPfdp8Tad3st5Oc7O:-MGoZ8KO9NMTmqXb9Kh6:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/vcdbroker.py#L1875)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 484 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjPsBJ0LJh8wIlmzNf:-MGoZ8xF-VNCzMQ5slKn:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/def_/cluster_service.py#L484)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 1003 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjS_9f7KaOBKX6W0Bw:-MGoZA9a5dMYPcIikbDp:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/def_/cluster_service.py#L1003)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 1678 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjT-5R-Og7JrKHJmWS:-MGoZB0y0gOUPuVBpOcz:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/def_/cluster_service.py#L1678)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 1679 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjT3Tz-wqTz6n1RzHf:-MGoZBVa1BTQxwUq4yl5:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/def_/cluster_service.py#L1679)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 1681 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjT4UTCgzNjtt1_8q-:-MGoZBvp-WXeqRGhiVQy:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/def_/cluster_service.py#L1681)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 1724 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjT7Um9tL-CqnQ9owD:-MGoZCUp-ig90XwcnWQb:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/container_service_extension/def_/cluster_service.py#L1724)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

control_plane -> control plane
</blockquote></details>

Done.
___
*[cse_def_schema/api_v35/schema.json, line 69 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjTn7h8kbmXIsGc4W_:-MGoZDKx9uhZEgNeiKhu:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aaba7228fff60b9949be89846e1dbe560ca9367f/cse_def_schema/api_v35/schema.json#L69)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

master -> control_plane
</blockquote></details>

Done.
___
*[cse_def_schema/api_v35/schema.json, line 167 at r1](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGjTT-L9XJe6vneCpej:-MGoZDri3g96xWXbSiZy:b-896fix) ([raw file](https://githu [...]

2020-09-09 20:47 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/735)* status: 6 of 12 files reviewed, 34 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/vcdbroker.py, line 1185 at r3](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGobWvQ8m6hOaAH3W6c:-MGobWvQ8m6hOaAH3W6d:b-6di) ([raw file](https://github.com/vmware/container-service-extension/blob/18f4ffd85d1f08cc861466dc8ed89b58346dde8d/container_service_extension/vcdbroker.py#L1185)):*
> ```
>      f"in control planenode {control_plane_node_names}"
> ```
planenode - missing space
___
*[container_service_extension/vcdbroker.py, line 1256 at r3](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGobI25-jro36h4da6Y:-MGobI25-jro36h4da6Z:b-n3mnyc) ([raw file](https://github.com/vmware/container-service-extension/blob/18f4ffd85d1f08cc861466dc8ed89b58346dde8d/container_service_extension/vcdbroker.py#L1256)):*
> ```
>  f"incontrol planenode 
> ```
spaces appeared to be missing.


<!-- Sent from Reviewable.io -->

2020-09-09 21:01 UTC, sakthisunda reviewed
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/735)* status: 7 of 12 files reviewed, 35 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/vcdbroker.py, line 1819 at r3](https://reviewable.io/reviews/vmware/container-service-extension/735#-MGof4fx8s4_1oEtDy38:-MGof4fx8s4_1oEtDy39:b-1a8gua) ([raw file](https://github.com/vmware/container-service-extension/blob/18f4ffd85d1f08cc861466dc8ed89b58346dde8d/container_service_extension/vcdbroker.py#L1819)):*
> ```
> LOGGER.debug(f"Getting control planeIP for vapp: "
> ```
planeIP --> plane IP


<!-- Sent from Reviewable.io -->

2020-09-14 16:45 UTC, Anirudh9794 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 





<!-- Sent from Reviewable.io -->

2020-09-14 16:47 UTC, sakthisunda approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/735#-:-MHCVzmv2rVXzeErQICD:bnfp4nl)* status: 6 of 12 files reviewed, 35 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-09-15 18:39 UTC, merged