[VCDA-1794] Order-of-output-columns-fixed
vmware/container-service-extension pull request #745
Opened 2020-09-14 16:24 UTC by sakthisunda

-  Fixed order of output columns on CLI tabular results wherever it is not handled
-  Fixed ovdc list and node list having wrong column formats. 
----------
![image](https://user-images.githubusercontent.com/5530442/93108588-d727de00-f667-11ea-989d-aed08d6625a5.png)
---------------
Node list before fix:
![image](https://user-images.githubusercontent.com/5530442/93111848-0fc9b680-f66c-11ea-8ac6-8a1cf848eeae.png)

Node list after fix:
![image](https://user-images.githubusercontent.com/5530442/93108664-ef97f880-f667-11ea-8fa2-e78ba1c2b5bd.png)

@Anirudh9794 @rocknes @sahithi

2020-09-14 20:25 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I believe it is a good time to change the output keys to human readable format

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/745#-:-MHDHTsqDc-mxYbk13RG:b50ml7c)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/client/cse.py, line 91 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHOTl32vVszxfIKMM:-MHDHOTl32vVszxfIKMN:b-9y16qs) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L91)):*
> ```Python
>             'name': 'name',
>             'revision': 'revision',
>             'is_default': 'is_default',
> ```

default
___
*[container_service_extension/client/cse.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHRDc9oAj38JsQ6AK:-MHDHRDc9oAj38JsQ6AL:bbmumpr) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L93)):*
> ```Python
>             'is_default': 'is_default',
>             'catalog': 'catalog',
>             'catalog_item': 'catalog_item',
> ```

Catalog Item
___
*[container_service_extension/client/cse.py, line 94 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHSAKC_aktY7jPB7d:-MHDHSAKC_aktY7jPB7e:b-kmlah5) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L94)):*
> ```Python
>             'catalog': 'catalog',
>             'catalog_item': 'catalog_item',
>             'description': 'description'
> ```

Description
___
*[container_service_extension/client/cse.py, line 1223 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDH99a4Vwq7kOBcWf1:-MHDH99bC6IrLmB9BygT:b-gj584g) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L1223)):*
> ```Python
>         display_field_to_value_field = {
>             'name': 'name',
>             'ipAddress': 'ipAddress',
> ```

IP Address
___
*[container_service_extension/client/cse.py, line 1224 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHAc59BpsYvgOI1ov:-MHDHAc6DtD7BiaqHIaL:b-9fi2n2) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L1224)):*
> ```Python
>             'name': 'name',
>             'ipAddress': 'ipAddress',
>             'numberOfCpus': 'numberOfCpus',
> ```

Number of CPUs
___
*[container_service_extension/client/cse.py, line 1225 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHCLZ0t3xJztsTavk:-MHDHCLZ0t3xJztsTavl:b-nubtyp) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L1225)):*
> ```Python
>             'ipAddress': 'ipAddress',
>             'numberOfCpus': 'numberOfCpus',
>             'memoryMB': 'memoryMB'
> ```

Memory MB
___
*[container_service_extension/client/ovdc_policy.py, line 32 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHGxC2kCDA-txTT-Q:-MHDHGxC2kCDA-txTT-R:bb70qi8) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/ovdc_policy.py#L32)):*
> ```Python
>         result = process_response(response)
>         display_field_to_value_field = {
>             'ovdc_name': 'ovdc_name',
> ```

Name
___
*[container_service_extension/client/ovdc_policy.py, line 33 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHI962YqW2ff_wXTr:-MHDHI962YqW2ff_wXTs:b32vvk) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/ovdc_policy.py#L33)):*
> ```Python
>         display_field_to_value_field = {
>             'ovdc_name': 'ovdc_name',
>             'ovdc_id': 'ovdc_id',
> ```

ID
___
*[container_service_extension/client/ovdc_policy.py, line 34 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHKX97iA4qJAXet18:-MHDHKXA6qrD1uZiKYzE:b8i7tq1) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/ovdc_policy.py#L34)):*
> ```Python
>             'ovdc_name': 'ovdc_name',
>             'ovdc_id': 'ovdc_id',
>             'k8s_runtime': 'k8s_runtime'
> ```

K8s Runtime


<!-- Sent from Reviewable.io -->

2020-09-14 21:22 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/745)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/client/cse.py, line 91 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHOTl32vVszxfIKMM:-MHDUn6m-35-McQlUVUP:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L91)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

default
</blockquote></details>

Done.
___
*[container_service_extension/client/cse.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHRDc9oAj38JsQ6AK:-MHDUnMw6jo2LBXYyVmE:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L93)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Catalog Item
</blockquote></details>

Done.
___
*[container_service_extension/client/cse.py, line 94 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHSAKC_aktY7jPB7d:-MHDUnk0AmDA5eMd6VcM:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L94)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Description
</blockquote></details>

Done.
___
*[container_service_extension/client/cse.py, line 1223 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDH99a4Vwq7kOBcWf1:-MHDUo3PDNxvRhRADiMs:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L1223)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

IP Address
</blockquote></details>

Done.
___
*[container_service_extension/client/cse.py, line 1225 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHCLZ0t3xJztsTavk:-MHDUoO8A6N1biKiac3p:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L1225)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Memory MB
</blockquote></details>

Done.
___
*[container_service_extension/client/ovdc_policy.py, line 32 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHGxC2kCDA-txTT-Q:-MHDUp7m3kzuzWYElyar:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/ovdc_policy.py#L32)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Name
</blockquote></details>

Done.
___
*[container_service_extension/client/ovdc_policy.py, line 33 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHI962YqW2ff_wXTr:-MHDUpSL83bfxW-xNVmD:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/ovdc_policy.py#L33)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

ID
</blockquote></details>

Done.
___
*[container_service_extension/client/ovdc_policy.py, line 34 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHKX97iA4qJAXet18:-MHDUpk-DXnKs-QntH7Z:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/ovdc_policy.py#L34)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

K8s Runtime
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-14 23:38 UTC, rocknes requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/745)* status: all files reviewed, 10 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/client/utils.py, line 174 at r2](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDxIRX6reWJ4Bp9X-t:-MHDxIRY1l550ZjbbcGO:bkbrssw) ([raw file](https://github.com/vmware/container-service-extension/blob/5ce6121350486475179dfb7ce54a1044913b1170/container_service_extension/client/utils.py#L174)):*
> ```Python
> 
> 
> def filter_result_set(result_set, display_field_to_value_field):
> ```

I don't think the name of the method and the way it is being used highlight that the filtering is done not by pruning entire records but rather columns in a record.

Also the else part of this if block is concerning, are we saying that this function doesn't do anything if we don't get a list of dictionaries??

I think the over-arching idea is to have a function that prunes columns from a result set (list of dictionaries or just a single dictionary) and arrange the columns in a certain way with certain label.

Also we are calling the param result_set but it is supposed to be a list :??

I would prefer to have a generic method that takes in both lists and list of dictionaries and a list of columns to retain.

def filter_columns(result, value_field_to_display_field): <-- notice the second param has inverted the key-value pair. Not that it matters in the implementation but think of the operation we are performing here, viz. transforming some column to a different column name so the map source-> target makes more sense.


<!-- Sent from Reviewable.io -->

2020-09-15 18:35 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/745)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/client/cse.py, line 1224 at r1](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDHAc59BpsYvgOI1ov:-MHI23kk3SFyC8hilhmt:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/43c2663549100610ad67a5a31d2cab324321abd9/container_service_extension/client/cse.py#L1224)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Number of CPUs
</blockquote></details>

Done.
___
*[container_service_extension/client/utils.py, line 174 at r2](https://reviewable.io/reviews/vmware/container-service-extension/745#-MHDxIRX6reWJ4Bp9X-t:-MHI24ax18RwEZVnxWtL:b92dvfw) ([raw file](https://github.com/vmware/container-service-extension/blob/5ce6121350486475179dfb7ce54a1044913b1170/container_service_extension/client/utils.py#L174)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I don't think the name of the method and the way it is being used highlight that the filtering is done not by pruning entire records but rather columns in a record.

Also the else part of this if block is concerning, are we saying that this function doesn't do anything if we don't get a list of dictionaries??

I think the over-arching idea is to have a function that prunes columns from a result set (list of dictionaries or just a single dictionary) and arrange the columns in a certain way with certain label.

Also we are calling the param result_set but it is supposed to be a list :??

I would prefer to have a generic method that takes in both lists and list of dictionaries and a list of columns to retain.

def filter_columns(result, value_field_to_display_field): <-- notice the second param has inverted the key-value pair. Not that it matters in the implementation but think of the operation we are performing here, viz. transforming some column to a different column name so the map source-> target makes more sense.

</blockquote></details>

Thanks.  I updated the code as suggested in this review.


<!-- Sent from Reviewable.io -->

2020-09-17 07:05 UTC, rocknes approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/745#-:-MHPsT_SCMsLLnfH1OBz:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2020-09-17 16:06 UTC, merged