Server side changes to handle when TKG+ is swithced off
vmware/container-service-extension pull request #765
Opened 2020-10-01 21:18 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Some of the TKG+ operations can still be performed if the server is first installed with `enable_tkg_plus` option set to true and later disabled.
* Disable TKG+ operations from CSE server if TKG+ is not enabled in CSE server.

If TKG+ is not enabled
* Prevent loading of TKG+ template.
* Prevent TKG+ ovdc updates.
* Skip TKG+ in the output for OVDC list

Testing done:
* checked if ovdc list doesn't give TKG+ if there is already an OVDC enabled with TKG+ ( tkg+ disabled)
* checked if TKG+ templates are not being loaded during runtime (tkg+ disabled)
* checked if OVDC update operations throw exception if TKG+ policies are updated (tkg+ disabled)
* checked if the above operations work fine when the flag is switched back to `true`

@rocknes @sahithi @sakthisunda

2020-10-01 21:49 UTC, sakthisunda reviewed
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/765)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/local_template_manager.py, line 103 at r1](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIa7aU98vo83sy_pI0i:-MIa7aU98vo83sy_pI0j:btislxa) ([raw file](https://github.com/vmware/container-service-extension/blob/86339f212daceca6ee6d9effad2b0b8e350b6ca3/container_service_extension/local_template_manager.py#L103)):*
> ```Python
>             # TKG+ is not enabled in CSE config. Skip the template and log the
>             # relevant information.
>             msg = "Skipping loading template " \
> ```

Skipping loading template data ..


<!-- Sent from Reviewable.io -->

2020-10-02 02:16 UTC, sahithi requested changes
Can you document the behavior of all the workflows (install, upgrade, ovdc, template) when tkg+ is enabled and disabled, somewhere in the code - perhaps where the value from the config file is read for the first time (or) sample file? Same for the CLI side too.

Otherwise, we will soon forget the intended behavior.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/765#-:-MIb4JP08-hSVsejA_vZ:bc67kdd)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2020-10-02 03:23 UTC, rocknes requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/765)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/configure_cse.py, line 890 at r1](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIbImKV9k40z3JUobiV:-MIbImKV9k40z3JUobiW:b-nplv7p) ([raw file](https://github.com/vmware/container-service-extension/blob/86339f212daceca6ee6d9effad2b0b8e350b6ca3/container_service_extension/configure_cse.py#L890)):*
> ```Python
>             catalog_name=catalog_name,  # noqa: E501
>             org_name=org_name,
>             is_tkg_plus_enabled=is_tkg_plus_enabled,
> ```

I don't think local template manager should be made aware of tkg plus flag.

Infact this current change will revert your recent fix, for the tkg templates. i.e. templates will be left without being tagged with proper compute profile, neither any error would be raised.

I understand that by moving the filtering logic out of ltm, we would be duplicating the filtering logic in few places. But, we don't want to miss processing templates because the flag was turned off during upgrade.

Example scenario.
CSE server was upgrade to v3.0 at api v33.0, with tkg+ enabled. TKG+ template was created too.
During the upgrade to api v35.0, the flag is turned off. CSE skips the TKG+ templates, doesn;t raise error either. Next we start up the server with the flag turned on, and we will have untagged template :(
___
*[container_service_extension/def_/ovdc_service.py, line 67 at r1](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIbJUA3-MjSWyCyoxHq:-MIbJUA3-MjSWyCyoxHr:bz2atvc) ([raw file](https://github.com/vmware/container-service-extension/blob/86339f212daceca6ee6d9effad2b0b8e350b6ca3/container_service_extension/def_/ovdc_service.py#L67)):*
> ```Python
>     if ClusterEntityKind.TKG_PLUS.value in ovdc_spec.k8s_runtime and \
>             not utils.is_tkg_plus_enabled():
>         msg = "TKG+ is not enabled in CSE server. Please enable TKG+ in the " \
> ```

nit: enabled on


<!-- Sent from Reviewable.io -->

2020-10-02 21:21 UTC, rocknes approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/765#-:-MIfB6Vl7y8pgo2mFDas:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/configure_cse.py, line 1102 at r2](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIfAT4t0pixW4D3dVSg:-MIfAT4t0pixW4D3dVSh:b-o6afb9) ([raw file](https://github.com/vmware/container-service-extension/blob/2447d5c4b7de3d43bb93cff9f5b206a7500f485b/container_service_extension/configure_cse.py#L1102)):*
> ```Python
>         msg = "Found a TKG+ template." \
>               " However TKG+ is not enabled on CSE. " \
>               "Please enable TKG+ for CSE and re-run " \
> ```

Let's be a little clear here, by saying enable TKG+ for CSE via config file


<!-- Sent from Reviewable.io -->

2020-10-02 21:32 UTC, Anirudh9794 commented
___
*[container_service_extension/configure_cse.py, line 890 at r1](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIbImKV9k40z3JUobiV:-MIfDftK6CirM6paLlnt:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/86339f212daceca6ee6d9effad2b0b8e350b6ca3/container_service_extension/configure_cse.py#L890)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I don't think local template manager should be made aware of tkg plus flag.

Infact this current change will revert your recent fix, for the tkg templates. i.e. templates will be left without being tagged with proper compute profile, neither any error would be raised.

I understand that by moving the filtering logic out of ltm, we would be duplicating the filtering logic in few places. But, we don't want to miss processing templates because the flag was turned off during upgrade.

Example scenario.
CSE server was upgrade to v3.0 at api v33.0, with tkg+ enabled. TKG+ template was created too.
During the upgrade to api v35.0, the flag is turned off. CSE skips the TKG+ templates, doesn;t raise error either. Next we start up the server with the flag turned on, and we will have untagged template :(
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-02 21:33 UTC, Anirudh9794 commented
___
*[container_service_extension/local_template_manager.py, line 103 at r1](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIa7aU98vo83sy_pI0i:-MIfDr3aCKSL7x0mYJyw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/86339f212daceca6ee6d9effad2b0b8e350b6ca3/container_service_extension/local_template_manager.py#L103)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Skipping loading template data ..
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-02 21:33 UTC, Anirudh9794 commented
___
*[container_service_extension/def_/ovdc_service.py, line 67 at r1](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIbJUA3-MjSWyCyoxHq:-MIfDxrDAb5t3kToI-Q1:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/86339f212daceca6ee6d9effad2b0b8e350b6ca3/container_service_extension/def_/ovdc_service.py#L67)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: enabled on
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-02 22:02 UTC, Anirudh9794 commented
___
*[container_service_extension/configure_cse.py, line 1102 at r2](https://reviewable.io/reviews/vmware/container-service-extension/765#-MIfAT4t0pixW4D3dVSg:-MIfKgybBg3HNjw_MGPa:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2447d5c4b7de3d43bb93cff9f5b206a7500f485b/container_service_extension/configure_cse.py#L1102)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Let's be a little clear here, by saying enable TKG+ for CSE via config file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-02 22:24 UTC, sakthisunda approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/765#-:-MIfPiJz32bpi1V-UkpM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-10-02 23:18 UTC, sahithi approved these changes
Hi Aniruddh, thanks for adding those comments, they are helpful. What I was actually referring to was one large paragraph describing everything about TKG+ config flag and TKG+ CLI env variable - like the one Aritra posted in one of the threads in our channel - https://vca-bos.slack.com/archives/GD555K9J5/p1601580235248300?thread_ts=1601488175.201000&cid=GD555K9J5

LGTM after copy-pasting this content at the right place in the code-base. 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/765#-:-MIf_q-DErdodlAOYOVl:bm4mw0w)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-10-02 23:18 UTC, sahithi approved these changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/765)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-10-02 23:57 UTC, merged