[VCDA-1917] CSE Service Role creation cosmetic issues
vmware/container-service-extension pull request #821
Opened 2020-11-06 03:00 UTC by ChintanShahVMware

Cosmetic issues CSE service role creation
- Added better switch to accept VCD Host arg.
- Corrected command name from cse-service-role to create-service-role
- Hide password while accepting input
- Display msg to show progress in task
- Hide urllib3 error messages

Signed-off-by: Chintan Shah <schintan@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

2020-11-06 17:28 UTC, rocknes requested changes
Please fix flake8 errors, and there was one more cosmetic change in the create_cse_service_role method .. viz. extra space in the description.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/821#-:-MLTaHVm9eF8-KzkqbQx:beq1fkz)* status: all files reviewed, 1 unresolved discussion (waiting on @ChintanShahVMware)

___
*[container_service_extension/server_cli.py, line 349 at r1](https://reviewable.io/reviews/vmware/container-service-extension/821#-MLT_vuuAVthg3cGQAhw:-MLT_vuuAVthg3cGQAhx:b-5sk9m) ([raw file](https://github.com/vmware/container-service-extension/blob/aa50c230e3c6a4f442f30cd6935ab4b25d0a4b7b/container_service_extension/server_cli.py#L349)):*
> ```Python
> 
>     try:
>         client = vcd_client.Client(vcd_host, verify_ssl_certs=ssl_verify)
> ```

Please print a message here f"Connecting to vCD ({vdc_host})". This will inform the user that their input for password was successfully accepted.


<!-- Sent from Reviewable.io -->

2020-11-06 18:14 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/821#-:-MLTknjA9AaW04NTnFBC:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @ChintanShahVMware)

___
*[container_service_extension/server_cli.py, line 359 at r1](https://reviewable.io/reviews/vmware/container-service-extension/821#-MLTdoWO8Z298Rqnzonf:-MLTdoWO8Z298Rqnzong:b4gsq68) ([raw file](https://github.com/vmware/container-service-extension/blob/aa50c230e3c6a4f442f30cd6935ab4b25d0a4b7b/container_service_extension/server_cli.py#L359)):*
> ```Python
>         console_message_printer.general_no_color(msg)
>         msg = f"Creating CSE Service Role..."
>         console_message_printer.general_no_color(msg)
> ```

Please log messages into SERVER_CLI_LOGGER as well.


<!-- Sent from Reviewable.io -->

2020-11-07 00:49 UTC, ChintanShahVMware commented
___
*[container_service_extension/server_cli.py, line 359 at r1](https://reviewable.io/reviews/vmware/container-service-extension/821#-MLTdoWO8Z298Rqnzonf:-MLVAS4f8aPlPUlcgWIp:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aa50c230e3c6a4f442f30cd6935ab4b25d0a4b7b/container_service_extension/server_cli.py#L359)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Please log messages into SERVER_CLI_LOGGER as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-07 00:49 UTC, ChintanShahVMware commented
___
*[container_service_extension/server_cli.py, line 349 at r1](https://reviewable.io/reviews/vmware/container-service-extension/821#-MLT_vuuAVthg3cGQAhw:-MLVASs25sPsN-uQ_YRJ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aa50c230e3c6a4f442f30cd6935ab4b25d0a4b7b/container_service_extension/server_cli.py#L349)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please print a message here f"Connecting to vCD ({vdc_host})". This will inform the user that their input for password was successfully accepted.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-07 01:28 UTC, rocknes approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/821#-:-MLVJNq-D5nj6gNjXNFF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2020-11-07 01:53 UTC, rocknes approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/821)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2020-11-07 02:00 UTC, merged