[VCDA-1907] Run Client Tests As k8 author
vmware/container-service-extension pull request #837
Opened 2020-11-18 17:22 UTC by sakthisunda

- Remove sharing CSE catalog using ACL rules for test organization to access the catalog
- Run client tests as k8 author role => cloned vApp author role + view : catalog shared from other org right
- change vcdbroker cluster creation/resize: 
    -- removed accessing catalog via sys admin client during cluster creation/resize 
    -- Use the client instantiated with logged in persona's credentials. 
- Tested cluster creation and resize thru CLI
- Completed client system tests successfully
------------------------------
![image](https://user-images.githubusercontent.com/5530442/99493704-8c0a9f80-2924-11eb-8b2d-fe5ed6271109.png)

2020-11-20 16:46 UTC, rocknes requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/837)* status: all files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/system_test_framework/environment.py, line 282 at r1](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMaX1bM1wSChK8tlqct:-MMaX1bM1wSChK8tlqcu:b-gxp3jh) ([raw file](https://github.com/vmware/container-service-extension/blob/e830e639b3c59e2b4fbabc3a403bd547abeb3925/container_service_extension/system_test_framework/environment.py#L282)):*
> ```Python
> 
> def create_k8_author_role():
>     config = testutils.yaml_to_dict(BASE_CONFIG_FILEPATH)
> ```

Please pass the vcd section and test section of the config to this method instead of re-reading it.
___
*[container_service_extension/system_test_framework/environment.py, line 300 at r1](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMaXerj6ybHZlDHJxQH:-MMaXerj6ybHZlDHJxQI:b-nqckyz) ([raw file](https://github.com/vmware/container-service-extension/blob/e830e639b3c59e2b4fbabc3a403bd547abeb3925/container_service_extension/system_test_framework/environment.py#L300)):*
> ```Python
>     result = CLI_RUNNER.invoke(
>         vcd, ['role', 'add-right', K8_AUTHOR_ROLE_NAME,
>               'Catalog: View Published Catalogs'],
> ```

Please create a constant for this. It's ok to keep the constant local to this file.
___
*[system_tests/conftest.py, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMaXpJl2SqT2Sy-J3f6:-MMaXpJl2SqT2Sy-J3f7:bql9s93) ([raw file](https://github.com/vmware/container-service-extension/blob/e830e639b3c59e2b4fbabc3a403bd547abeb3925/system_tests/conftest.py#L48)):*
> ```Python
>     env.create_user(env.ORG_ADMIN_NAME, env.ORG_ADMIN_PASSWORD,
>                     env.ORG_ADMIN_ROLE_NAME)
>     env.create_user(env.VAPP_AUTHOR_NAME, env.VAPP_AUTHOR_PASSWORD,
> ```

We should rename VAPP_AUTHOR_NAME and VAP_AUTHOR_PASSWORD to it's K8 counterpart.


<!-- Sent from Reviewable.io -->

2020-11-20 23:00 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/837)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/system_test_framework/environment.py, line 282 at r1](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMaX1bM1wSChK8tlqct:-MMbsniRARlIJu9I0Qan:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/e830e639b3c59e2b4fbabc3a403bd547abeb3925/container_service_extension/system_test_framework/environment.py#L282)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please pass the vcd section and test section of the config to this method instead of re-reading it.
</blockquote></details>

Done.
___
*[container_service_extension/system_test_framework/environment.py, line 300 at r1](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMaXerj6ybHZlDHJxQH:-MMbsoT4EFVdAYAx_oxz:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/e830e639b3c59e2b4fbabc3a403bd547abeb3925/container_service_extension/system_test_framework/environment.py#L300)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please create a constant for this. It's ok to keep the constant local to this file.
</blockquote></details>

Done.
___
*[system_tests/conftest.py, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMaXpJl2SqT2Sy-J3f6:-MMbspbA07VYZJH3co0T:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/e830e639b3c59e2b4fbabc3a403bd547abeb3925/system_tests/conftest.py#L48)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should rename VAPP_AUTHOR_NAME and VAP_AUTHOR_PASSWORD to it's K8 counterpart.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-20 23:02 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/837)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @rocknes)

___
*[system_tests/conftest.py, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMaXpJl2SqT2Sy-J3f6:-MMbtF0ECw4zdlp-lh4V:b-wjk3sm) ([raw file](https://github.com/vmware/container-service-extension/blob/e830e639b3c59e2b4fbabc3a403bd547abeb3925/system_tests/conftest.py#L48)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Retested both server and client tests


<!-- Sent from Reviewable.io -->

2020-11-24 02:04 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> minor comment

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/837#-:-MMrzcFh4X6hgC4wtMSD:basp5ut)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/system_test_framework/environment.py, line 164 at r2](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMrythm9rmuKkKggfos:-MMrythm9rmuKkKggfot:b-mqw1jp) ([raw file](https://github.com/vmware/container-service-extension/blob/23210c6a5f2921f0c16439a2814e7cb0c5363f8c/container_service_extension/system_test_framework/environment.py#L164)):*
> ```Python
>     TEST_ORG_HREF = test_org.href
>     TEST_VDC_HREF = test_vdc.href
>     create_k8_author_role(config['vcd'])
> ```

Can this be done inside the pyfixture `vcd_users` where all the other users are initialized?


<!-- Sent from Reviewable.io -->

2020-11-25 17:28 UTC, rocknes approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/837#-:-MN-RgpH7W6Jf0pV6x8v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-11-30 17:19 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/837)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/system_test_framework/environment.py, line 164 at r2](https://reviewable.io/reviews/vmware/container-service-extension/837#-MMrythm9rmuKkKggfos:-MNP8aQpC22VxXfnoL-L:b-ifz1ac) ([raw file](https://github.com/vmware/container-service-extension/blob/23210c6a5f2921f0c16439a2814e7cb0c5363f8c/container_service_extension/system_test_framework/environment.py#L164)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can this be done inside the pyfixture `vcd_users` where all the other users are initialized?
</blockquote></details>

Here,  config dictionary is available. Moving to fixture requires config file processing repeat. For now, I am leaving it in this init() fixture call.
Also, this step (role creation) is mandatory before creating the user. 


<!-- Sent from Reviewable.io -->

2020-11-30 17:19 UTC, merged