[VCDA-1936] Cluster share command
vmware/container-service-extension pull request #842
Opened 2020-11-30 23:00 UTC by ltimothy7

Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Implemented `vcd cse cluster share` command to share a cluster with multiple users.

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Implemented GET and PUT endpoints for native clusters:  /cse/3.0/cluster/<cluster-id>/acl
Native and TKG clusters can be shared using this command.

I also tested sharing multiple native and TKG clusters including ensuring that downgrading a cluster access level (e.g., from full-control to read-only) is blocked. I also tested upgrading an access level for a cluster user and tested invalid inputs such as a user not existing.

- (Optional) Names of reviewers using @ sign + name
@ChintanShahVMware @rocknes @sahithi @andrew-ni

2020-12-01 17:28 UTC, sakthisunda requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/vcdbroker.py, line 584 at r1](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNUK_tPEUXDSnaXJHO4:-MNUK_tPEUXDSnaXJHO5:b-s8g4w7) ([raw file](https://github.com/vmware/container-service-extension/blob/649eec40a679541aed7315d12767ead81db166a8/container_service_extension/vcdbroker.py#L584)):*
> ```Python
>             record_user_action_details(
>                 cse_operation=CseOperation.CLUSTER_ACL_LIST,
>                 cse_params=copy.deepcopy(data))
> ```

record_user_action_details: this requires handler code registration in telemetry_handler.py and payload prepation in payload_generator.py 
___
*[container_service_extension/vcdbroker.py, line 643 at r1](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNULAcEAzw0Ce23UydR:-MNULAcEAzw0Ce23UydS:b-s8g4w7) ([raw file](https://github.com/vmware/container-service-extension/blob/649eec40a679541aed7315d12767ead81db166a8/container_service_extension/vcdbroker.py#L643)):*
> ```Python
>             record_user_action_details(
>                 cse_operation=CseOperation.CLUSTER_ACL_UPDATE,
>                 cse_params=copy.deepcopy(data))
> ```

record_user_action_details: this requires handler code registration in telemetry_handler.py and payload prepation in payload_generator.py 


<!-- Sent from Reviewable.io -->

2020-12-01 19:33 UTC, ltimothy7 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/vcdbroker.py, line 584 at r1](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNUK_tPEUXDSnaXJHO4:-MNUmljR1EE0S4P325LS:bysl61n) ([raw file](https://github.com/vmware/container-service-extension/blob/649eec40a679541aed7315d12767ead81db166a8/container_service_extension/vcdbroker.py#L584)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

record_user_action_details: this requires handler code registration in telemetry_handler.py and payload prepation in payload_generator.py 
</blockquote></details>

Done. Thank you, Sakthi, for catching this. My bad for overlooking this.
___
*[container_service_extension/vcdbroker.py, line 643 at r1](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNULAcEAzw0Ce23UydR:-MNUmsWD8mhv0KJpG4QJ:bs7wumx) ([raw file](https://github.com/vmware/container-service-extension/blob/649eec40a679541aed7315d12767ead81db166a8/container_service_extension/vcdbroker.py#L643)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

record_user_action_details: this requires handler code registration in telemetry_handler.py and payload prepation in payload_generator.py 
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2020-12-02 18:33 UTC, sahithi requested changes
> Reviewed 3 of 12 files at r1, 1 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 1 of 16 files reviewed, 7 unresolved discussions (waiting on @ltimothy7, @sahithi, and @sakthisunda)

___
*[container_service_extension/request_processor.py, line 95 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZgEUvD8S_pY49_ygZ:-MNZgEUvD8S_pY49_yg_:b-wyt4kd) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/request_processor.py#L95)):*
> ```
>     CseOperation.CLUSTER_ACL_LIST: native_cluster_handler.cluster_acl_info,
>     CseOperation.CLUSTER_ACL_UPDATE: native_cluster_handler.cluster_acl_update,
> ```

The API endpoint is _/cse/3.0/cluster/cluster-id/acl_ (targets >=35.0), the handlers added here are for legacy api versions (33 and 34).

This should have been
CseOperation.V35_CLUSTER_ACL_LIST: v35_cluster_handler.cluster_acl_info,
CseOperation.V35_CLUSTER_ACL_UPDATE: v35_cluster_handler.cluster_acl_update,
___
*[container_service_extension/request_processor.py, line 521 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZhDo8-q_IYRyTi4g1:-MNZhDo8-q_IYRyTi4g2:blei2wm) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/request_processor.py#L521)):*
> ```Python
>             if tokens[6] == 'acl':
>                 return {
>                     _OPERATION_KEY: CseOperation.CLUSTER_ACL_LIST,
> ```

CseOperation.V35_CLUSTER_ACL_LIST
___
*[container_service_extension/request_processor.py, line 527 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZhG5oAjSk2q1RTOeB:-MNZhG5oAjSk2q1RTOeC:b-qh13fj) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/request_processor.py#L527)):*
> ```Python
>             if tokens[6] == 'acl':
>                 return {
>                     _OPERATION_KEY: CseOperation.CLUSTER_ACL_UPDATE,
> ```

CseOperation.V35_CLUSTER_ACL_UPDATE
___
*[container_service_extension/vcdbroker.py, line 574 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZiBbICYqNTppqu-N2:-MNZiBbICYqNTppqu-N3:befgisf) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/vcdbroker.py#L574)):*
> ```Python
>         }
> 
>     def get_cluster_acl_info(self, **kwargs):
> ```

These ACL update methods can be removed from this file. This file _vcdbroker.py_ is meant for older API versions (33 and 34 only)
___
*[container_service_extension/request_handlers/native_cluster_handler.py, line 160 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZhnqc8yVxcpWKLNx5:-MNZhnqc8yVxcpWKLNx6:bpzhd50) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/request_handlers/native_cluster_handler.py#L160)):*
> ```Python
> def cluster_acl_update(request_data, op_ctx: ctx.OperationContext):
>     """Request handler for cluster acl update operation."""
>     vcd_broker = VcdBroker(op_ctx)
> ```

We don't need to implement these methods here. Any of the defined entity ACL stuff is not relevant to API versions 33 and 34.


<!-- Sent from Reviewable.io -->

2020-12-02 19:21 UTC, sahithi requested changes
Hi Tim,

I haven't yet reviewed client-side files.

Few things
1. Get in touch with @anirudh9794 on the client and server-side pagination.
2. Implement data class for ACL entry. Refer _entity_service.py_  and _def_/def_models.py_. A lot of the code you have will prove redundant. Data classes help us in easy serialization/deserialization. It also makes the data transfer across files easier and cleaner.
3. Let us follow this pattern at variable declaration - variable: type = <>. It improves readability. We need to do this, especially for classes.
4. Consolidate all the defined entity ACL stuff into one file _acl_service.py_.
5. Reuse the class CloudApiResource to add more constants.

Please address the above and I will review the code in its entirety again.

> Reviewed 2 of 12 files at r1, 7 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842#-:-MNZsHTG5WYeApFecxLk:b-81n5bj)* status: 8 of 16 files reviewed, 21 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/server_constants.py, line 94 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZkLLA3swugpnqQa9B:-MNZkLLA3swugpnqQa9C:bt4d1cs) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/server_constants.py#L94)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> ACCESS_CONTROLS_PATH = 'accessControls'
> ENTITIES_PATH = 'entities'
> ACCESS_LEVEL_URN_BEGIN = 'urn:vcloud:accessLevel:'
> ACTION_CONTROL_ACCESS_PATH = '/action/controlAccess/'
> CHANGE_ACCESS = 'Change'
> ```
</details>

All of these need to go into the class _CloudApiResource_.
___
*[container_service_extension/shared_constants.py, line 49 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZlhsICyBjYWTuU85-:-MNZlhsICyBjYWTuU850:b-nrmjhc) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/shared_constants.py#L49)):*
> ```Python
> 
> 
> # Access control constants
> ```

Add a comment that these variables are applicable only for API version >=35
___
*[container_service_extension/shared_constants.py, line 66 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZm5S60gXzCMqcnSGa:-MNZm5S60gXzCMqcnSGb:boaw6z4) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/shared_constants.py#L66)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> # Page parameters
> PAGE = 'page'
> PAGE_SIZE = 'pageSize'
> DEFAULT_PAGE = 1
> DEFAULT_PAGE_SZ = 25
> ```
</details>

Please sync with @anirudh9794 . He is also adding similar constants in his pagination review. Avoid duplicates.
___
*[container_service_extension/shared_constants.py, line 197 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZmZFxEU7-vfPOLYbl:-MNZmZFxEU7-vfPOLYbm:b4gypg4) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/shared_constants.py#L197)):*
> ```Python
> 
> @unique
> class PaginatedDataKey(str, Enum):
> ```

Same here sync with @anirudh9794 
___
*[container_service_extension/utils.py, line 473 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZreNs4Yd_Scm5EJ_-:-MNZreNs4Yd_Scm5EJ_0:bbslici) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L473)):*
> ```Python
> 
> 
> def form_cluster_acl_entry(user_urn, username, access_level_urn):
> ```

This can be replaced by a data class. Look at other comments.
___
*[container_service_extension/utils.py, line 489 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZrlp053uwY4vESYND:-MNZrlp053uwY4vESYNE:bpvajo9) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L489)):*
> ```Python
> 
> 
> def get_id_from_user_urn(user_urn_id):
> ```

Please consolidate all the defined ACL stuff into one file _acl_service.py_
Constants and methods seem a bit scattered.
___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 102 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZqr7l3zkgAO5oUY30:-MNZqr7l3zkgAO5oUY31:bvwa3ng) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L102)):*
> ```Python
>             **response_processor.process_response(response))
> 
>     def get_single_page_cluster_acl(self, cluster_id,
> ```

Please review @anirudh9794 's pagination review. 
@anirudh9794 You both should sync up to keep the code format consistent.

@ltimothy7 Once the data class has been implemented, you can do as simple as return def_models.DefEntity(
            **response_processor.process_response(response))
Refer to other cluster methods in this file.
___
*[container_service_extension/def_/cluster_service.py, line 446 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZjKvq456p1ub48YCs:-MNZjKvq456p1ub48YCt:bs8di5q) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/def_/cluster_service.py#L446)):*
> ```Python
>         cloudapi_client = vcd_utils.get_cloudapi_client_from_vcd_client(
>             self.context.client)
>         de = self.entity_svc.get_entity(cluster_id)
> ```

You can refer to other methods in this file for the naming pattern.
curr_entity: def_models.DefEntity = self.entity_svc.get_entity(cluster_id)
___
*[container_service_extension/def_/cluster_service.py, line 450 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZjgM88kdgkfV2cy-w:-MNZjgM88kdgkfV2cy-x:bz4mfua) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/def_/cluster_service.py#L450)):*
> ```Python
>         # Retrieve defined entity ACL
>         acl_path = f'{server_constants.ENTITIES_PATH}/' \
>                    f'{de.id}/{server_constants.ACCESS_CONTROLS_PATH}' \
> ```

de.id -> cluster_id
___
*[container_service_extension/def_/cluster_service.py, line 462 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZnB9wBiqn5eTWeQPD:-MNZnB9wBiqn5eTWeQPE:b460jtl) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/def_/cluster_service.py#L462)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         for de_acl_setting in de_acl_values:
>             user_id = de_acl_setting[shared_constants.AccessControlKey.MEMBER_ID]  # noqa: E501
>             acl_level_id = de_acl_setting[shared_constants.AccessControlKey.ACCESS_LEVEL_ID]  # noqa: E501
>             username = user_id_names_dict[user_id]
>             member_acl_entry = utils.form_cluster_acl_entry(user_id, username,
>                                                             acl_level_id)
>             member_acl_list.append(member_acl_entry)
> ```
</details>


Can you add a data class for ACLEntry? Refer to _def_/models.py_?
Serialization and deserialization will become easier with this - Refer to these methods _entity_service.get_entity()_, _entity_service.update_entity()_, _entity_service.list_entities_

Lot of the code here will become redundant then.
___
*[container_service_extension/def_/cluster_service.py, line 484 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN [...]

2020-12-02 23:35 UTC, Anirudh9794 requested changes
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 9 of 16 files reviewed, 28 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/utils.py, line 489 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_QVqa9nJPxhgQsDXG:-MN_QVqa9nJPxhgQsDXH:b5oml1y) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L489)):*
> ```Python
> 
> 
> def get_id_from_user_urn(user_urn_id):
> ```

There is an `extract_id()` function in `pyvcloud.vcd.utils`, which does the same thing. It can be used instead of creating a new function
___
*[container_service_extension/utils.py, line 495 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_R0TMABofS5VM0Qo7:-MN_R0TMABofS5VM0Qo8:b-e66q7b) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L495)):*
> ```Python
> 
> 
> def get_id_from_user_href(user_href):
> ```

A generic method instead of specifically for user is helpful. There are some other places where we have added similar methods for different resources but I feel we should be using a generic method here
___
*[container_service_extension/utils.py, line 501 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_Wd6k-JNzSiH4fxIr:-MN_Wd6k-JNzSiH4fxIs:b-ry65ah) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L501)):*
> ```Python
> 
> 
> def get_access_level_from_urn(access_level_urn):
> ```

You can use `extract_id()` instead of this method too
___
*[container_service_extension/utils.py, line 519 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_X1kc6AKEzWNvvFU0:-MN_X1kc6AKEzWNvvFU1:b70y4cs) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L519)):*
> ```Python
> 
> 
> def get_user_id_names_dict(cloudapi_client):
> ```

I feel `create_user_id_to_names_dict()` will be a better name
___
*[container_service_extension/utils.py, line 530 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_YKgvB6FJjN5y0By2:-MN_YKgvB6FJjN5y0By3:by7kuz9) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L530)):*
> ```Python
>         method=shared_constants.RequestMethod.GET,
>         cloudapi_version=cloudapi_constants.CloudApiVersion.VERSION_1_0_0,
>         resource_url_relative_path='users')
> ```

A constant can be added for the relative path in `cloudapi/constants.py`
___
*[container_service_extension/utils.py, line 532 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_YY_2CH2S_D9e1Kn1:-MN_YY_2CH2S_D9e1Kn2:bjuqbxi) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L532)):*
> ```Python
>         resource_url_relative_path='users')
>     if not response_body:
>         return None
> ```

Is it necessary to check this? If yes, I think raising an exception here will be better
___
*[container_service_extension/def_/cluster_service.py, line 453 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_b3815wjBaRlA-Ycp:-MN_b3815wjBaRlA-Ycq:b8yle1u) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/def_/cluster_service.py#L453)):*
> ```Python
>                    f'?{shared_constants.PAGE}={page}&' \
>                    f'{shared_constants.PAGE_SIZE}={page_sz}'
>         de_acl_response = cloudapi_client.do_request(
> ```

you can create a file `cloudapi_utils.py` and add the function to get the `de_acl_response` over there. 


<!-- Sent from Reviewable.io -->

2020-12-03 21:29 UTC, rocknes requested changes
> Reviewed 3 of 12 files at r1, 2 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 14 of 16 files reviewed, 31 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/client/de_cluster_native.py, line 277 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeT_8Z1ODTCJ-pICu1:-MNeT_8_7T1OIWeSPOe9:b-4x2xda) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/client/de_cluster_native.py#L277)):*
> ```Python
>     def share_cluster(self, cluster_id, users: list, access_level_id):
>         # parse user id info
>         users_to_ids = client_utils.get_user_ids(self._cloudapi_client, users)
> ```

We should limit the user search to the org where the cluster resides. In case of sys admin, they will be able to see all users across all orgs, and there is no restriction that we can't have namesake users across orgs.
___
*[container_service_extension/client/de_cluster_native.py, line 291 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeU2El55scSMODWPjI:-MNeU2El55scSMODWPjJ:b-tx6541) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/client/de_cluster_native.py#L291)):*
> ```Python
>         curr_acl_values = self._native_cluster_api.get_all_cluster_acl(cluster_id)  # noqa: E501
>         for entry in curr_acl_values:
>             if users_to_ids.get(entry[shared_constants.AccessControlKey.USERNAME]):  # noqa: E501
> ```

Does vCD complain if you reduce the access level of a user?
This means if we give full control access to a user, we can't reduce it to read write?


Also I think we should explicitly mention that this method doesn't deal with removing an ACL entry completely.
___
*[container_service_extension/client/utils.py, line 218 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeVE016dfsPVb4Awcq:-MNeVE022NvtY7qA0Qgw:b-i4dm9v) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/client/utils.py#L218)):*
> ```Python
>     :rtype: dict
>     """
>     response_body = cloudapi_client.do_request(
> ```

Is sys admin able to see all users across orgs using this query?
In the /api/ land, sys admins have to run the query for adminUsers to be able to look into other orgs than System.


<!-- Sent from Reviewable.io -->

2020-12-03 22:00 UTC, rocknes requested changes
> Reviewed 1 of 12 files at r1, 5 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: all files reviewed, 35 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/def_/cluster_service.py, line 433 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNe_wc0AhFkPZEGhsRM:-MNe_wc0AhFkPZEGhsRN:b-9f4eqq) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/def_/cluster_service.py#L433)):*
> ```Python
>         return curr_entity
> 
>     def get_cluster_acl_info(self, cluster_id, query: dict):
> ```

In my opinion the service layers shouldn't be really aware of query string.
We should just pass the params page and page_size into this method instead of the dictionary.
These params can have default value.
___
*[container_service_extension/def_/cluster_service.py, line 441 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNe_iqr4iIulxEXt6lV:-MNe_iqs3clkD_3q8aek:b-mof3h4) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/def_/cluster_service.py#L441)):*
> ```Python
>         # Get page params
>         page = query.get('page', shared_constants.DEFAULT_PAGE)
>         page_sz = query.get('pageSize', shared_constants.DEFAULT_PAGE_SZ)
> ```

Please don't abbreviate small words like size.
___
*[container_service_extension/def_/cluster_service.py, line 487 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeakXZ6Z2VY53GSMxg:-MNeakXZ6Z2VY53GSMxh:b-kot3xa) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/def_/cluster_service.py#L487)):*
> ```Python
>         telemetry_handler.record_user_action_details(
>             telemetry_constants.CseOperation.V35_CLUSTER_ACL_UPDATE,
>             cse_params=(cluster_id, update_acl_entries))
> ```

Is there any sensitive data in the update_acl_entries dict? e.g. user name ?
___
*[container_service_extension/telemetry/payload_generator.py, line 332 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNebdXTAuBU8NB0HXVW:-MNebdXTAuBU8NB0HXVX:bdbn4sg) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/telemetry/payload_generator.py#L332)):*
> ```Python
> 
> def get_payload_for_v35_cluster_acl_update(update_tuple):
>     cluster_id, update_acl_entries = update_tuple
> ```

I think dictionaries are better to use than tuples.


<!-- Sent from Reviewable.io -->

2020-12-03 22:02 UTC, rocknes reviewed
> Reviewed 2 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: all files reviewed, 35 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-12-09 01:07 UTC, ltimothy7 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 2 of 20 files reviewed, 35 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/request_processor.py, line 95 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZgEUvD8S_pY49_ygZ:-MN_9_XP9c5i1YpzCVSL:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/request_processor.py#L95)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>     CseOperation.CLUSTER_ACL_LIST: native_cluster_handler.cluster_acl_info,
>     CseOperation.CLUSTER_ACL_UPDATE: native_cluster_handler.cluster_acl_update,
> ```

The API endpoint is _/cse/3.0/cluster/cluster-id/acl_ (targets >=35.0), the handlers added here are for legacy api versions (33 and 34).

This should have been
CseOperation.V35_CLUSTER_ACL_LIST: v35_cluster_handler.cluster_acl_info,
CseOperation.V35_CLUSTER_ACL_UPDATE: v35_cluster_handler.cluster_acl_update,
</blockquote></details>

Done.
___
*[container_service_extension/request_processor.py, line 521 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZhDo8-q_IYRyTi4g1:-MN_9cE201jqCtQz8MLB:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/request_processor.py#L521)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

CseOperation.V35_CLUSTER_ACL_LIST
</blockquote></details>

Done.
___
*[container_service_extension/request_processor.py, line 527 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZhG5oAjSk2q1RTOeB:-MN_9d1XAfHtdkGBGbkc:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/request_processor.py#L527)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

CseOperation.V35_CLUSTER_ACL_UPDATE
</blockquote></details>

Done.
___
*[container_service_extension/server_constants.py, line 94 at r2](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZkLLA3swugpnqQa9B:-MN_Ev6UBG1wYXnwQsVu:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fae09de02a61f231bff776be9564f22da7d77d3b/container_service_extension/server_constants.py#L94)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
> ACCESS_CONTROLS_PATH = 'accessControls'
> ENTITIES_PATH = 'entities'
> ACCESS_LEVEL_URN_BEGIN = 'urn:vcloud:accessLevel:'
> ACTION_CONTROL_ACCESS_PATH = '/action/controlAccess/'
> CHANGE_ACCESS = 'Change'
> ```
All of these need to go into the class _CloudApiResource_.
</blockquote></details>

Done.
___
*[container_service_extension/shared_constants.py, line 49 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZlhsICyBjYWTuU85-:-MN_PEuVE-ziafVXK3xI:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/shared_constants.py#L49)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Add a comment that these variables are applicable only for API version >=35
</blockquote></details>

Done.
___
*[container_service_extension/shared_constants.py, line 66 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZm5S60gXzCMqcnSGa:-MN_PKVx-POtSrup8wWU:b-239pyl) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/shared_constants.py#L66)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
> # Page parameters
> PAGE = 'page'
> PAGE_SIZE = 'pageSize'
> DEFAULT_PAGE = 1
> DEFAULT_PAGE_SZ = 25
> ```
Please sync with @anirudh9794 . He is also adding similar constants in his pagination review. Avoid duplicates.
</blockquote></details>

Done. We have synced up; we will wait for @anirudh9794's PR to be checked in.
___
*[container_service_extension/shared_constants.py, line 197 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZmZFxEU7-vfPOLYbl:-MN_Pzpn9sLhI1136D0J:boushi1) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/shared_constants.py#L197)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same here sync with @anirudh9794 
</blockquote></details>

Done. We will wait for his PR to be checked in
___
*[container_service_extension/utils.py, line 473 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZreNs4Yd_Scm5EJ_-:-MN_bbwQEKPwmrY-J_xR:b-jg62i6) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L473)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This can be replaced by a data class. Look at other comments.
</blockquote></details>

This entry is part of the GET response, so the entry needs to be a dict.
___
*[container_service_extension/utils.py, line 489 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNZrlp053uwY4vESYND:-MN_h5zEDyHW_VfSci1R:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L489)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please consolidate all the defined ACL stuff into one file _acl_service.py_
Constants and methods seem a bit scattered.
</blockquote></details>

Done.
___
*[container_service_extension/utils.py, line 489 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_QVqa9nJPxhgQsDXG:-MNeHjx3-KTBKNaVwI8D:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L489)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

There is an `extract_id()` function in `pyvcloud.vcd.utils`, which does the same thing. It can be used instead of creating a new function
</blockquote></details>

Done.
___
*[container_service_extension/utils.py, line 495 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_R0TMABofS5VM0Qo7:-MNk2ypi2dGkj0X4QOtB:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L495)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

A generic method instead of specifically for user is helpful. There are some other places where we have added similar methods for different resources but I feel we should be using a generic method here
</blockquote></details>

Done.
___
*[container_service_extension/utils.py, line 501 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_Wd6k-JNzSiH4fxIr:-MNeIco5BdsVNfmv6eh3:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/560aa7c5ece5babc4f8fad8084631bf3b7a77bff/container_service_extension/utils.py#L501)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

You can use `extract_id()` instead of this method too
</blockquote></details>

Done.
___
*[container_service_extension/utils.py, line 519 at r3](https://reviewable.io/reviews/vmware/container-service-extension/842#-MN_X1kc6AKEzWNvvFU0:-MNjLjyw7GDKTpyrtvWU:b-896fix) ([raw file](https://github.com/vmware/ [...]

2020-12-09 21:05 UTC, Anirudh9794 commented
___
*[container_service_extension/client/cluster_commands.py, line 1069 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO88vdT6Tlzwo-K03EO:-MO88vdT6Tlzwo-K03EP:bvclv9b) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/cluster_commands.py#L1069)):*
> ```Python
>         # Determine cluster type and retrieve cluster id if needed
>         client = ctx.obj['client']
>         cloudapi_client = \
> ```

Please create a function in `de_cluster.py` for sharing clusters. Logic for extracting Access level, k8_runtime, client and org can be kept here. Rest of the logic can be moved to a function in `de_cluster.py`


<!-- Sent from Reviewable.io -->

2020-12-09 21:11 UTC, Anirudh9794 commented
___
*[container_service_extension/client/de_cluster_native.py, line 291 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeU2El55scSMODWPjI:-MO8KdJH7R68xBujfnPh:bcdrulf) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/client/de_cluster_native.py#L291)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

vCD will not complain if the access level is reduced; however, if a user has full control access to a defined entity, a request to lower the access to read-write will receive a successful response code, but the access will remain at full control. 

In the case of native clusters, vApps can have their access level reduced; since the defined entity won't get reduced, I thought we should block reducing the cluster access level to avoid putting the vApp and defined entity in inconsistent states.
</blockquote></details>

If the de access level can't be reduced after giving higher level access, then I think it is a bug in vCD


<!-- Sent from Reviewable.io -->

2020-12-09 21:18 UTC, Anirudh9794 commented
___
*[container_service_extension/def_/models.py, line 314 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8LWi66TvVUcprfQYN:-MO8LWi66TvVUcprfQYO:bdfb09) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/def_/models.py#L314)):*
> ```Python
>     username: str = None
> 
>     def get_filtered_dict(self, include=[]):
> ```

construct_filtered_dict*


<!-- Sent from Reviewable.io -->

2020-12-09 21:30 UTC, Anirudh9794 commented
___
*[container_service_extension/client/de_cluster_tkg.py, line 367 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8PC1Q4AQWNjUZBQMe:-MO8PC1R2i08azk-ssCJ:bj0rboo) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/de_cluster_tkg.py#L367)):*
> ```
> user_name_to_id_dict
> ```
I think the param name should be different here


<!-- Sent from Reviewable.io -->

2020-12-09 21:37 UTC, Anirudh9794 commented
___
*[container_service_extension/client/cluster_commands.py, line 1109 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8QjMkDLHbL03WjbFY:-MO8QjMkDLHbL03WjbFZ:bo6g2pm) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/cluster_commands.py#L1109)):*
> ```Python
>                        f'{share_response.status_code} and reason: '
>                        f'{share_response.reason}')
>                 return
> ```

This return should be removed as it will prevent printing the message in `stdout` below


<!-- Sent from Reviewable.io -->

2020-12-10 03:33 UTC, ltimothy7 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 2 of 20 files reviewed, 39 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/client/cluster_commands.py, line 1109 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8QjMkDLHbL03WjbFY:-MO9RKQh0mqcv4d-WA9_:b-dh2ka4) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/cluster_commands.py#L1109)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This return should be removed as it will prevent printing the message in `stdout` below
</blockquote></details>

The return is here so that the success message will not be printed.
___
*[container_service_extension/client/de_cluster_native.py, line 291 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeU2El55scSMODWPjI:-MO9TDkl1V-mpYO5kSts:b-ue68j6) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/client/de_cluster_native.py#L291)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If the de access level can't be reduced after giving higher level access, then I think it is a bug in vCD
</blockquote></details>

@rocknes Before filing a bug, do you also think this is a bug?
___
*[container_service_extension/client/de_cluster_tkg.py, line 367 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8PC1Q4AQWNjUZBQMe:-MO9Ri0j42ydXVvfimZc:bwxjgwk) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/de_cluster_tkg.py#L367)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

> ```
> user_name_to_id_dict
> ```
I think the param name should be different here
</blockquote></details>

@anirudh9794 do you mean that the name should be changed in the comment or that there should be a different name for the variable?


<!-- Sent from Reviewable.io -->

2020-12-10 17:56 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 2 of 20 files reviewed, 40 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/def_/cluster_service.py, line 506 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOCm_FzDw_hxmxOXKq0:-MOCm_FzDw_hxmxOXKq1:b-h2fysv) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/def_/cluster_service.py#L506)):*
> ```Python
>             shared_constants.ClusterAclKey.UPDATE_ACL_ENTRIES:
>                 update_acl_entries
>         }
> ```

Since update_acl_entries is a list, it should be flattened to a string (comma separated) before sending it to telemetry.


<!-- Sent from Reviewable.io -->

2020-12-10 23:49 UTC, Anirudh9794 commented
___
*[container_service_extension/client/de_cluster_tkg.py, line 367 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8PC1Q4AQWNjUZBQMe:-MOA2EsCCCnNe9NwqVca:bqs0bna) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/de_cluster_tkg.py#L367)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

@anirudh9794 do you mean that the name should be changed in the comment or that there should be a different name for the variable?
</blockquote></details>

Makes more sense to change the variable name.


<!-- Sent from Reviewable.io -->

2020-12-10 23:59 UTC, Anirudh9794 commented
___
*[container_service_extension/shared_constants.py, line 57 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOE55Jj3aJX6pjI-kCS:-MOE55Jj3aJX6pjI-kCT:b-zfmi2k) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/shared_constants.py#L57)):*
> ```Python
> FULL_CONTROL = 'FullControl'
> URN_VCLOUD_ACCESS = 'urn:vcloud:accessLevel'
> USER_URN_BEGIN = 'urn:vcloud:user:'
> ```

nit: USER_URN_BEGIN -> USER_URN_PREFIX


<!-- Sent from Reviewable.io -->

2020-12-11 00:08 UTC, Anirudh9794 commented
___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 143 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOE6EHjDi-dTtvzQlbz:-MOE6EHk4QDySGlpm0uj:bmb366u) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L143)):*
> ```Python
>             media_type='application/json',
>             accept_type='application/json')
>         return response
> ```

You can avoid checking the response code in `cluster_commands.py` and instead call `process_response(response)` here. You can make changes to `response_to_exception()` function if needed


<!-- Sent from Reviewable.io -->

2020-12-11 00:43 UTC, Anirudh9794 commented
___
*[container_service_extension/def_/cluster_service.py, line 488 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOEEtgDCDftce6_kbvE:-MOEEtgDCDftce6_kbvF:bvnrqe9) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/def_/cluster_service.py#L488)):*
> ```Python
>         prev_page_uri = f"{page_url_fragment}{page - 1}" if page_count > page > 1 else None  # noqa: E501
> 
>         list_paginated_response = utils.construct_paginated_response(
> ```

I think some of the code can be reduced by using `utils.create_links_and_construct_paginated_result()`


<!-- Sent from Reviewable.io -->

2020-12-11 00:47 UTC, Anirudh9794 commented
___
*[container_service_extension/request_handlers/v35/def_cluster_handler.py, line 178 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOEFhIW1X5PiETpgwGt:-MOEFhIW1X5PiETpgwGu:b-9fmpjl) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/request_handlers/v35/def_cluster_handler.py#L178)):*
> ```Python
>     cluster_id = data[RequestKey.CLUSTER_ID]
>     query = data.get(RequestKey.V35_QUERY, {})
>     page = query.get('page', shared_constants.CSE_PAGINATION_FIRST_PAGE_NUMBER)
> ```

You can use the constant PaginationKey here for 'page'.


<!-- Sent from Reviewable.io -->

2020-12-11 22:38 UTC, ltimothy7 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 2 of 22 files reviewed, 43 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/client/cluster_commands.py, line 1069 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO88vdT6Tlzwo-K03EO:-MOIPMlpB4PNVq1aspyz:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/cluster_commands.py#L1069)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Please create a function in `de_cluster.py` for sharing clusters. Logic for extracting Access level, k8_runtime, client and org can be kept here. Rest of the logic can be moved to a function in `de_cluster.py`
</blockquote></details>

Done.
___
*[container_service_extension/client/de_cluster_tkg.py, line 367 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8PC1Q4AQWNjUZBQMe:-MOI_aM08uCV5w-XG-xU:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/de_cluster_tkg.py#L367)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Makes more sense to change the variable name.
</blockquote></details>

Done.
___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 143 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOE6EHjDi-dTtvzQlbz:-MOIaG3X3_MLk-HN6Dej:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L143)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

You can avoid checking the response code in `cluster_commands.py` and instead call `process_response(response)` here. You can make changes to `response_to_exception()` function if needed
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 488 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOEEtgDCDftce6_kbvE:-MOIsEbA9Twjx1fF8D3k:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/def_/cluster_service.py#L488)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think some of the code can be reduced by using `utils.create_links_and_construct_paginated_result()`
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 506 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOCm_FzDw_hxmxOXKq0:-MOIPV3q0UDpndXJM5FY:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/def_/cluster_service.py#L506)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Since update_acl_entries is a list, it should be flattened to a string (comma separated) before sending it to telemetry.
</blockquote></details>

Done.
___
*[container_service_extension/def_/models.py, line 314 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO8LWi66TvVUcprfQYN:-MOIPXsJ3Tmqew834bbo:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/def_/models.py#L314)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

construct_filtered_dict*
</blockquote></details>

Done.
___
*[container_service_extension/request_handlers/v35/def_cluster_handler.py, line 178 at r6](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOEFhIW1X5PiETpgwGt:-MOIPabj5i603KTxbYgu:b-pt2ipc) ([raw file](https://github.com/vmware/container-service-extension/blob/60a66c679ca527dcf0137cc3229086e6f8d4f873/container_service_extension/request_handlers/v35/def_cluster_handler.py#L178)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

You can use the constant PaginationKey here for 'page'.
</blockquote></details>

Done. Thank you


<!-- Sent from Reviewable.io -->

2020-12-15 00:33 UTC, Anirudh9794 commented
___
*[container_service_extension/def_/cluster_service.py, line 474 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOYmDnr1e7V1NYgE9A1:-MOYmDnr1e7V1NYgE9A2:boi3rq0) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/def_/cluster_service.py#L474)):*
> ```Python
> 
>         # Form final response fields
>         base_uri = f"{self.context.client.get_api_uri()}/" \
> ```

The `api_path_format` added to `server_constants.CseOperation` can be used to construct this URL using the `%s` formatting of python. Please refer to `v35/ovdc_service.py`.

Also, as per current implementation, pagination of response is handled in `def_cluster_handler.py` instead of `cluster_service.py`. You can return a dictionary here which can be used by `def_cluster_handler.py` to paginate the response. This just helps separating the functionalities of different layers we have. You can refer to `list_clusters()` function for the implementation


<!-- Sent from Reviewable.io -->

2020-12-15 00:45 UTC, Anirudh9794 requested changes
> Reviewed 15 of 18 files at r6, 14 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: all files reviewed, 37 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-12-15 09:08 UTC, rocknes requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Take this with a grain of salt since this is a huge review :|

> Reviewed 1 of 1 files at r4, 1 of 7 files at r5, 6 of 18 files at r6, 14 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842#-:-MO_dxgx8-FZsqIY6yX8:b-5zckyz)* status: all files reviewed, 34 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, @sahithi, and @sakthisunda)

___
*[container_service_extension/utils.py, line 558 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO_car584tRXOEysRNP:-MO_car584tRXOEysRNQ:b-mp9obt) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/utils.py#L558)):*
> ```Python
>             next_page_uri += f"&{q}={query_params[q]}"
> 
>     extra_page = 1 if bool(result_total % page_size) else 0
> ```

nit: partial_result_page_count 
___
*[container_service_extension/utils.py, line 559 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO_cMms4jHli4bVw00E:-MO_cMmu6VT-mgkeWNxR:b-e6z9j0) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/utils.py#L559)):*
> ```Python
> 
>     extra_page = 1 if bool(result_total % page_size) else 0
>     page_count = result_total // page_size + extra_page
> ```

Couldn't  just use something like ceil()?
___
*[container_service_extension/utils.py, line 561 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO_d4LaBe_laS7F6QMC:-MO_d4LaBe_laS7F6QMD:b-kjc1j) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/utils.py#L561)):*
> ```Python
>     page_count = result_total // page_size + extra_page
>     prev_page_uri: str = None
>     if page_count + 1 > page_number > 1:
> ```

This is such an awkward expression. I mean it works in python but will throw off anyone familiar with java/C/C++

Instead of page_count + 1 > page_number
I think page_count >= page_number is easier to read and understand
___
*[container_service_extension/client/de_cluster_native.py, line 291 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeU2El55scSMODWPjI:-MO__rYv2q45ASh_mMsr:b-xew9fb) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/client/de_cluster_native.py#L291)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

@rocknes Before filing a bug, do you also think this is a bug?
</blockquote></details>

Yes, seems like a bug
___
*[container_service_extension/client/utils.py, line 239 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO_aO8N3TtbJ5zzPoil:-MO_aO8N3TtbJ5zzPoim:byxi9qc) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/client/utils.py#L239)):*
> ```Python
>             break
>     if len(own_users_set) > 0:
>         raise Exception(f"Not user id's found for: {own_users_set}")
> ```

nit: User ids not found for .. [x, y, z]


<!-- Sent from Reviewable.io -->

2020-12-15 19:50 UTC, ltimothy7 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 18 of 22 files reviewed, 31 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/utils.py, line 558 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO_car584tRXOEysRNP:-MObtLUr5x_666pIr77N:bcs9mmc) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/utils.py#L558)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: partial_result_page_count 
</blockquote></details>

The variable is no longer needed because of using ceil()
___
*[container_service_extension/utils.py, line 559 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO_cMms4jHli4bVw00E:-MObtPsL4kahUPn6uQja:b3jgwq0) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/utils.py#L559)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Couldn't  just use something like ceil()?
</blockquote></details>

Done. Thank you; that's better
___
*[container_service_extension/utils.py, line 561 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MO_d4LaBe_laS7F6QMC:-MObu6TBELOC-aBgCKBq:b21nld4) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/utils.py#L561)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This is such an awkward expression. I mean it works in python but will throw off anyone familiar with java/C/C++

Instead of page_count + 1 > page_number
I think page_count >= page_number is easier to read and understand


</blockquote></details>

I agree this expression is very specific to Python, but I think it's cleaner to use it.

Thank you, I changed the expression to make it easier to read.
___
*[container_service_extension/client/de_cluster_native.py, line 291 at r4](https://reviewable.io/reviews/vmware/container-service-extension/842#-MNeU2El55scSMODWPjI:-MObuLQT9qyejBi9_uTU:b-9fsjp9) ([raw file](https://github.com/vmware/container-service-extension/blob/2ca23f2eca325953cf0d2d27ed2b476e7b87963a/container_service_extension/client/de_cluster_native.py#L291)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Yes, seems like a bug
</blockquote></details>

I have filed a bug; I spoke with Aashima and I created a separate task for allowing the access level to be reduced so that this PR isn't blocked. As for now, we can block requests to lower the access level until the bug is resolved.
___
*[container_service_extension/def_/cluster_service.py, line 474 at r7](https://reviewable.io/reviews/vmware/container-service-extension/842#-MOYmDnr1e7V1NYgE9A1:-MObsZgfACzQYWpJYwe_:b-isojae) ([raw file](https://github.com/vmware/container-service-extension/blob/4c4ee1a9fc2c6592242cdf17eb099dcecda7ec4c/container_service_extension/def_/cluster_service.py#L474)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The `api_path_format` added to `server_constants.CseOperation` can be used to construct this URL using the `%s` formatting of python. Please refer to `v35/ovdc_service.py`.

Also, as per current implementation, pagination of response is handled in `def_cluster_handler.py` instead of `cluster_service.py`. You can return a dictionary here which can be used by `def_cluster_handler.py` to paginate the response. This just helps separating the functionalities of different layers we have. You can refer to `list_clusters()` function for the implementation
</blockquote></details>

Done. Thank you for this comment; I have updated the code organization


<!-- Sent from Reviewable.io -->

2020-12-15 20:17 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842#-:-MOc2FNk6lNfpsrR-oot:bg7igkv)* status: all files reviewed, 31 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)



<!-- Sent from Reviewable.io -->

2020-12-16 03:24 UTC, sakthisunda approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 21 of 22 files reviewed, 30 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)



<!-- Sent from Reviewable.io -->

2020-12-16 20:18 UTC, rocknes approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/842)* status: 21 of 22 files reviewed, 27 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)



<!-- Sent from Reviewable.io -->

2020-12-16 20:21 UTC, merged