[VCDA-2035] Fix ovdc list operation to support backward compatibility
vmware/container-service-extension pull request #871
Opened 2021-01-12 18:36 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Make CSE server response for ovdc list compatible with older 3.0.x clients by not paginating the response if pagination parameters are not set by the client.

Testing done:
* Check /api/cse/3.0/ovdcs endpoint with and without page and pageSize query params
* Check /api/cse/ovdcs endpoint with and without page and pageSize query params

@rocknes @sahithi @sakthisunda @arunmk @ChintanShahVMware @ltimothy7

2021-01-13 01:28 UTC, sakthisunda approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-01-13 20:50 UTC, sakthisunda requested changes
> Reviewed 8 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/cse_client/pks_ovdc_api.py, line 17 at r2](https://reviewable.io/reviews/vmware/container-service-extension/871#-MQxUoM97KW7INcovXAj:-MQxUoM97KW7INcovXAk:b35hwll) ([raw file](https://github.com/vmware/container-service-extension/blob/754c77cd390f8b324a67cb233e961fb8ff2cfa8f/container_service_extension/client/cse_client/pks_ovdc_api.py#L17)):*
 
>         self._ovdcs_uri = f"{self._uri}/ovdcs"
not in use anymore in the code.
___
*[container_service_extension/client/cse_client/api_33/ovdc_api.py, line 16 at r2](https://reviewable.io/reviews/vmware/container-service-extension/871#-MQxV7Sq1_3KBf2f_EOb:-MQxV7Sq1_3KBf2f_EOc:bsn1bqp) ([raw file](https://github.com/vmware/container-service-extension/blob/754c77cd390f8b324a67cb233e961fb8ff2cfa8f/container_service_extension/client/cse_client/api_33/ovdc_api.py#L16)):*
 
>         self._ovdcs_uri = f"{self._uri}/ovdcs"
           not in use anymore in the code.
___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 20 at r2](https://reviewable.io/reviews/vmware/container-service-extension/871#-MQxVEkT7wKaZWGdjjs5:-MQxVEkT7wKaZWGdjjs6:b35hwll) ([raw file](https://github.com/vmware/container-service-extension/blob/754c77cd390f8b324a67cb233e961fb8ff2cfa8f/container_service_extension/client/cse_client/api_35/ovdc_api.py#L20)):*
 
>         self._ovdcs_uri = f"{self._uri}/ovdcs"
not in use anymore in the code.


<!-- Sent from Reviewable.io -->

2021-01-14 19:45 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/client/cse_client/pks_ovdc_api.py, line 17 at r2](https://reviewable.io/reviews/vmware/container-service-extension/871#-MQxUoM97KW7INcovXAj:-MR1QIlTBpqyDmWT07fK:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/754c77cd390f8b324a67cb233e961fb8ff2cfa8f/container_service_extension/client/cse_client/pks_ovdc_api.py#L17)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

 
>         self._ovdcs_uri = f"{self._uri}/ovdcs"
not in use anymore in the code.

</blockquote></details>

Done.
___
*[container_service_extension/client/cse_client/api_33/ovdc_api.py, line 16 at r2](https://reviewable.io/reviews/vmware/container-service-extension/871#-MQxV7Sq1_3KBf2f_EOb:-MR1QJcL2bBAOyCu11c6:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/754c77cd390f8b324a67cb233e961fb8ff2cfa8f/container_service_extension/client/cse_client/api_33/ovdc_api.py#L16)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

 
>         self._ovdcs_uri = f"{self._uri}/ovdcs"
           not in use anymore in the code.

</blockquote></details>

Done.
___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 20 at r2](https://reviewable.io/reviews/vmware/container-service-extension/871#-MQxVEkT7wKaZWGdjjs5:-MR1QLNjBZigcYCFpOzE:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/754c77cd390f8b324a67cb233e961fb8ff2cfa8f/container_service_extension/client/cse_client/api_35/ovdc_api.py#L20)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

 
>         self._ovdcs_uri = f"{self._uri}/ovdcs"
not in use anymore in the code.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 20:08 UTC, sakthisunda approved these changes
> Reviewed 2 of 10 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-01-14 21:29 UTC, ltimothy7 requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871)* status: all files reviewed, 8 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/cse_client/pks_ovdc_api.py, line 20 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lVicAdPGQSQnOBgH:-MR1lVicAdPGQSQnOBgI:b-ho2gpc) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/pks_ovdc_api.py#L20)):*
> ```Python
> 
>     def get_all_ovdcs(self, filters={}):
>         url = f"{self._org_vdcs_uri}?pageSize={self._request_page_size}"
> ```

should use shared_constants.PaginationKey.PAGE_SIZE
___
*[container_service_extension/client/cse_client/api_33/ovdc_api.py, line 20 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lLis8uxDcW71Ho1Z:-MR1lLit1DtIXG8vEc3k:b-ho2gpc) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/api_33/ovdc_api.py#L20)):*
> ```Python
> 
>     def get_all_ovdcs(self):
>         url = f"{self._org_vdcs_uri}?pageSize={self._request_page_size}"
> ```

should use shared_constants.PaginationKey.PAGE_SIZE
___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 33 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lTQ5Ebk9kMjc4V7a:-MR1lTQ5Ebk9kMjc4V7b:b-ho2gpc) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/api_35/ovdc_api.py#L33)):*
> ```Python
>         :rtype: Generator[(List[dict], int), None, None]
>         """
>         url = f"{self._org_vdcs_uri}?pageSize={self._request_page_size}"
> ```

should use shared_constants.PaginationKey.PAGE_SIZE
___
*[container_service_extension/def_/ovdc_service.py, line 131 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1m1D31_Z_bvl6UJmj:-MR1m1D31_Z_bvl6UJmk:b-maspd3) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/def_/ovdc_service.py#L131)):*
> ```Python
>         if ClusterEntityKind.TKG_PLUS.value in ovdc_details['k8s_runtime'] \
>                 and not utils.is_tkg_plus_enabled():  # noqa: E501
>             ovdc_details['k8s_runtime'].remove(ClusterEntityKind.TKG_PLUS.value)  # noqa: E501
> ```

For my understanding, is it guaranteed that this TKG_PLUS.value will be present?
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 119 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1mTfQ-TkzQHxLXcxz:-MR1mTfQ-TkzQHxLXcy-:bvlev3g) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/ovdc_handler.py#L119)):*
> ```Python
>             'name': ovdc_name,
>             'org': org_name,
>             'k8s provider': k8s_provider
> ```

Can you make an enum for these constants?
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 142 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1menh73VJj-D428sh:-MR1menh73VJj-D428si:bgmmqbd) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/ovdc_handler.py#L142)):*
> ```Python
> @record_user_action_telemetry(cse_operation=CseOperation.OVDC_LIST)
> def org_vdc_list(request_data, op_ctx: ctx.OperationContext):
>     """Request handler ofr orgvdc list operation.
> ```

nit: ofr -> for
___
*[container_service_extension/request_handlers/pks_ovdc_handler.py, line 286 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1mp9lBuTcl9dAW8G3:-MR1mp9lBuTcl9dAW8G4:bmcpkz1) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/pks_ovdc_handler.py#L286)):*
> ```Python
>             'name': ovdc_name,
>             'org': org_name,
>             'k8s provider': k8s_provider
> ```

Similar as above; it would help to use an enum here
___
*[container_service_extension/request_handlers/pks_ovdc_handler.py, line 330 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1nNL0EtttOFIU87My:-MR1nNL0EtttOFIU87Mz:b-il6x64) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/pks_ovdc_handler.py#L330)):*
> ```
>             ovdc_dict['pks api server'] = pks_server
>             ovdc_dict['available pks plans'] = pks_plans
> ```
It would also help to make these keys enums


<!-- Sent from Reviewable.io -->

2021-01-15 01:22 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871)* status: all files reviewed, 7 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/client/cse_client/pks_ovdc_api.py, line 20 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lVicAdPGQSQnOBgH:-MR2VAAYBhacSFKzBCZ-:b-gavgxa) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/pks_ovdc_api.py#L20)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

should use shared_constants.PaginationKey.PAGE_SIZE
</blockquote></details>

Since `_request_page_size` is different for OVDCs in v35 ( because listing 5 ovdcs on an avg will take 10s, which is the default timeout of VCD) and it is different for other operations, hence I created a private variable `_request_page_size` in `cse_client`. This can be overridden as per requirement.
Also, shared_constants.PaginationKey.PAGE_SIZE is a key (pageSize). But we need to use an integer here.
Let me know if there is any issue with the design. We can discuss and change it.
___
*[container_service_extension/client/cse_client/api_33/ovdc_api.py, line 20 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lLis8uxDcW71Ho1Z:-MR2W7ydAxqruPrPh7Mq:bbxgkzp) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/api_33/ovdc_api.py#L20)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

should use shared_constants.PaginationKey.PAGE_SIZE
</blockquote></details>

Same comment as above
___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 33 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lTQ5Ebk9kMjc4V7a:-MR2WAAXC4mdshDGZqhG:bbxgkzp) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/api_35/ovdc_api.py#L33)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

should use shared_constants.PaginationKey.PAGE_SIZE
</blockquote></details>

Same comment as above
___
*[container_service_extension/def_/ovdc_service.py, line 131 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1m1D31_Z_bvl6UJmj:-MR2S9di6hMCAoksHAoE:blmn4nt) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/def_/ovdc_service.py#L131)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

For my understanding, is it guaranteed that this TKG_PLUS.value will be present?
</blockquote></details>

I think I didn't properly understand your question. If you are asking if  the array `ovdc_details['k8_runtime']` will contain `TKG_PLUS`, then yes, it should contain `TKG_PLUS` or else the if condition will fail
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 119 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1mTfQ-TkzQHxLXcxz:-MR2XuNZ-iRPYdmVN1rL:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/ovdc_handler.py#L119)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Can you make an enum for these constants?
</blockquote></details>

Done.
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 142 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1menh73VJj-D428sh:-MR2Xy_Z0xkIkIwYkUPD:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/ovdc_handler.py#L142)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: ofr -> for
</blockquote></details>

Done.
___
*[container_service_extension/request_handlers/pks_ovdc_handler.py, line 286 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1mp9lBuTcl9dAW8G3:-MR2XzcE1khaZG0AVQ-A:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/pks_ovdc_handler.py#L286)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Similar as above; it would help to use an enum here
</blockquote></details>

Done.
___
*[container_service_extension/request_handlers/pks_ovdc_handler.py, line 330 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1nNL0EtttOFIU87My:-MR2ZV6Z32J2abGTKDQz:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/pks_ovdc_handler.py#L330)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

> ```
>             ovdc_dict['pks api server'] = pks_server
>             ovdc_dict['available pks plans'] = pks_plans
> ```
It would also help to make these keys enums
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 01:34 UTC, ltimothy7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with minor comments

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871#-:-MR2fOZO55kS5m82qlHA:b-ij5eeu)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sakthisunda)

___
*[container_service_extension/client/cse_client/pks_ovdc_api.py, line 20 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lVicAdPGQSQnOBgH:-MR2eUF6-NCIIz9jUnP3:biqvcvd) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/pks_ovdc_api.py#L20)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Since `_request_page_size` is different for OVDCs in v35 ( because listing 5 ovdcs on an avg will take 10s, which is the default timeout of VCD) and it is different for other operations, hence I created a private variable `_request_page_size` in `cse_client`. This can be overridden as per requirement.
Also, shared_constants.PaginationKey.PAGE_SIZE is a key (pageSize). But we need to use an integer here.
Let me know if there is any issue with the design. We can discuss and change it.
</blockquote></details>

Thank you, Anirruddha; sorry, I meant that you could use the shared constant instead of hardcoding 'pageSize'. I think this would actually require accessing PaginationKey.PAGE_SIZE.value. 
___
*[container_service_extension/def_/ovdc_service.py, line 131 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1m1D31_Z_bvl6UJmj:-MR2f-xL1TXF6Qqpixj8:b-9q95j) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/def_/ovdc_service.py#L131)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think I didn't properly understand your question. If you are asking if  the array `ovdc_details['k8_runtime']` will contain `TKG_PLUS`, then yes, it should contain `TKG_PLUS` or else the if condition will fail
</blockquote></details>

Thank you; my bad for not seeing this.
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 119 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1mTfQ-TkzQHxLXcxz:-MR2f9OO9xd9icJ1kxXf:b-9ve6dm) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/ovdc_handler.py#L119)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Should the key be 'OvdcInfoKey'?


<!-- Sent from Reviewable.io -->

2021-01-15 17:30 UTC, rocknes requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once all comments are resolved.

> Reviewed 4 of 10 files at r2, 3 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871#-:-MR65HfU-aax78ejWz40:bbdkrbh)* status: all files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/request_handlers/ovdc_handler.py, line 104 at r4](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR64aV5EiwILU72avBH:-MR64aV72t3-feDzYwUn:bso8zoz) ([raw file](https://github.com/vmware/container-service-extension/blob/293ca465a218852080ae00433caa4f030072dadb/container_service_extension/request_handlers/ovdc_handler.py#L104)):*
> ```Python
> 
> 
> def _filter_ovdc_list(sysadmin_client: vcd_client.Client,
> ```

Should we call this method filter? I don't think we are filtering anything in this method, we are constructing the final response from info retrieved from VCD.


<!-- Sent from Reviewable.io -->

2021-01-15 19:57 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/871)* status: all files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/client/cse_client/pks_ovdc_api.py, line 20 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lVicAdPGQSQnOBgH:-MR6Xk6KD6WpSmfR75GS:bmucdl9) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/pks_ovdc_api.py#L20)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Thank you, Anirruddha; sorry, I meant that you could use the shared constant instead of hardcoding 'pageSize'. I think this would actually require accessing PaginationKey.PAGE_SIZE.value. 
</blockquote></details>

Done. My bad, I assumed it was the query param value you were talking about :-) 
___
*[container_service_extension/client/cse_client/api_33/ovdc_api.py, line 20 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lLis8uxDcW71Ho1Z:-MR6YgmlDsuZPST9ywcb:b-un1y2h) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/api_33/ovdc_api.py#L20)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Made use of PAGE_SIZE
___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 33 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1lTQ5Ebk9kMjc4V7a:-MR6YkGR1CbDZj4VW4YZ:b-un1y2h) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/client/cse_client/api_35/ovdc_api.py#L33)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Made use of PAGE_SIZE
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 119 at r3](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR1mTfQ-TkzQHxLXcxz:-MR6YrLh2u3mwF7EUyiO:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2fbab21d5f0ae3523f16234c98096e0b93b1c531/container_service_extension/request_handlers/ovdc_handler.py#L119)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: Should the key be 'OvdcInfoKey'?
</blockquote></details>

Done.
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 104 at r4](https://reviewable.io/reviews/vmware/container-service-extension/871#-MR64aV5EiwILU72avBH:-MR6aB3A3Wb_R0t5R_bh:b-hmjosx) ([raw file](https://github.com/vmware/container-service-extension/blob/293ca465a218852080ae00433caa4f030072dadb/container_service_extension/request_handlers/ovdc_handler.py#L104)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should we call this method filter? I don't think we are filtering anything in this method, we are constructing the final response from info retrieved from VCD.
</blockquote></details>

Renamed the method to `_get_cse_ovdc_list`


<!-- Sent from Reviewable.io -->

2021-01-15 21:31 UTC, merged