[VCDA-2128] Fix repetitive expensive calls to vdcComputePolicies
vmware/container-service-extension pull request #905
Opened 2021-02-09 01:45 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

- call to /vdcComputePolicies is made every time computePolicyManager is initialized. This is an expensive call as computPolicy will be created for every ovdc created in VCD.
- Initialization of compute policy manager in ovdc list code should be done only once.

For 2000 ovdcs, an average of 20s is required for fetching 10 ovdcs per page.
![Screen Shot 2021-02-08 at 5 43 55 PM](https://user-images.githubusercontent.com/16699642/107304206-785b6a80-6a35-11eb-8b46-6726894155fe.png)

@rocknes @sakthisunda @ltimothy7

2021-02-09 20:29 UTC, sakthisunda requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/905)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/compute_policy_manager.py, line 68 at r1](https://reviewable.io/reviews/vmware/container-service-extension/905#-MT7Tc0K2sC-KWG8jVK6:-MT7Tc0K2sC-KWG8jVK7:b2f0eap) ([raw file](https://github.com/vmware/container-service-extension/blob/ff4704a78c3660f70d226e2d889e570ab8b479b6/container_service_extension/compute_policy_manager.py#L68)):*
> ```Python
>             # use to us.
>             request_uri = f"{cloudapi_constants.CloudApiResource.VDC_COMPUTE_POLICIES}?"  \
>                           f"{PaginationKey.PAGE_SIZE}=1"  # noqa: E501
> ```

Did you mean PaginationKey.PAGE_SIZE  (or)  PaginationKey.PAGE_NUMBER?


<!-- Sent from Reviewable.io -->

2021-02-09 20:54 UTC, Anirudh9794 commented
___
*[container_service_extension/compute_policy_manager.py, line 68 at r1](https://reviewable.io/reviews/vmware/container-service-extension/905#-MT7Tc0K2sC-KWG8jVK6:-MT7ZX-j9iDwmFV5Urv8:b-loa1fi) ([raw file](https://github.com/vmware/container-service-extension/blob/ff4704a78c3660f70d226e2d889e570ab8b479b6/container_service_extension/compute_policy_manager.py#L68)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Did you mean PaginationKey.PAGE_SIZE  (or)  PaginationKey.PAGE_NUMBER?
</blockquote></details>

No, Since this operation is an expensive one and it just helps validate if cloudapi endpoints are working as expected, It is enough to retrieve just a single record.


<!-- Sent from Reviewable.io -->

2021-02-09 21:06 UTC, sakthisunda approved these changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)



<!-- Sent from Reviewable.io -->

2021-02-09 21:19 UTC, ltimothy7 approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/905)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 25 at r1](https://reviewable.io/reviews/vmware/container-service-extension/905#-MT7eGe3EKsJqZKvPMxr:-MT7eGe43Yyos4bv0_6w:b-9d1m73) ([raw file](https://github.com/vmware/container-service-extension/blob/ff4704a78c3660f70d226e2d889e570ab8b479b6/container_service_extension/client/cse_client/api_35/ovdc_api.py#L25)):*
> ```Python
>         # an average of 10 seconds (Default vCD timeout) if there are 5 OVDCs
>         self._request_page_size = 10
> ```

Why is the request page size being increased to 10?


<!-- Sent from Reviewable.io -->

2021-02-10 22:56 UTC, Anirudh9794 commented
___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 25 at r1](https://reviewable.io/reviews/vmware/container-service-extension/905#-MT7eGe3EKsJqZKvPMxr:-MTD8yVX8FrgpOq9Q8N-:bb0956c) ([raw file](https://github.com/vmware/container-service-extension/blob/ff4704a78c3660f70d226e2d889e570ab8b479b6/container_service_extension/client/cse_client/api_35/ovdc_api.py#L25)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Why is the request page size being increased to 10?
</blockquote></details>

The server should be able to respond with 10 ovdcs per page within VCD recommended 30s timeout. Will Change the note.


<!-- Sent from Reviewable.io -->

2021-02-16 08:51 UTC, merged