[VCDA-2175] Schema-change-for-RDE-Status-To-Reflect-Cluster-Current-state
vmware/container-service-extension pull request #920
Opened 2021-02-22 18:43 UTC by sakthisunda

- Schema and RDE change for 2.0.0  
- Requirement: To get the current state of the cluster from Cluster Status
- Update RDE Status to include template name and revision.   
- Tested manually using Postman
-------------------------------
![image](https://user-images.githubusercontent.com/5530442/108754194-7e078480-74fa-11eb-913b-dd1c9c2a47a8.png)
----------
@Anirudh9794  @rocknes @sahithi

2021-02-22 19:20 UTC, sahithi requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[cse_def_schema/schema_2_0_0.json, line 206 at r1](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUAA_1Z-QCjt0jYX1iA:-MUAA_1Z-QCjt0jYX1iB:bdvvyb4) ([raw file](https://github.com/vmware/container-service-extension/blob/103ed28a207c62930fcbebf1ce8ee5c1a6d8fbf7/cse_def_schema/schema_2_0_0.json#L206)):*
> ```
> 
>         self.ovdc_network_name = ovdc_network_name
> ```
Create a definition for "k8_distribution" under definitions and have it reference from both "spec" and "status".
Refer to  "definitions.node" .


<!-- Sent from Reviewable.io -->

2021-02-22 19:22 UTC, sahithi requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUAB3Ri9UiAxuMVVP3K:-MUAB3Ri9UiAxuMVVP3L:bwn9bkv) ([raw file](https://github.com/vmware/container-service-extension/blob/103ed28a207c62930fcbebf1ce8ee5c1a6d8fbf7/container_service_extension/rde/models/rde_2_0_0.py#L93)):*
> ```Python
>         self.ovdc_name = ovdc_name
>         self.ovdc_network_name = ovdc_network_name
>         self.k8_distribution = k8_distribution
> ```

self.k8_distribution = Distribution(**k8_distribution) \
            if isinstance(k8_distribution, dict) else k8_distribution or Distribution() 


<!-- Sent from Reviewable.io -->

2021-02-22 19:49 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUAB3Ri9UiAxuMVVP3K:-MUAHGzBD5ctztFpGi9n:b-el1zoj) ([raw file](https://github.com/vmware/container-service-extension/blob/103ed28a207c62930fcbebf1ce8ee5c1a6d8fbf7/container_service_extension/rde/models/rde_2_0_0.py#L93)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

self.k8_distribution = Distribution(**k8_distribution) \
            if isinstance(k8_distribution, dict) else k8_distribution or Distribution() 
</blockquote></details>

Done.Thx
___
*[cse_def_schema/schema_2_0_0.json, line 206 at r1](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUAA_1Z-QCjt0jYX1iA:-MUAHTRuBPhk_DGihEID:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/103ed28a207c62930fcbebf1ce8ee5c1a6d8fbf7/cse_def_schema/schema_2_0_0.json#L206)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
> 
>         self.ovdc_network_name = ovdc_network_name
> ```
Create a definition for "k8_distribution" under definitions and have it reference from both "spec" and "status".
Refer to  "definitions.node" .
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-23 01:07 UTC, sahithi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Please test the schema registration, RDE serialization, and deserialization before the submission.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920#-:-MUBPqHOAXTyzglue6YW:boqdz59)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sahithi)



<!-- Sent from Reviewable.io -->

2021-02-23 01:07 UTC, sahithi reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi)



<!-- Sent from Reviewable.io -->

2021-02-23 02:02 UTC, sakthisunda reviewed
Testing Done:
1. Created the schema
2. Created Defined entity with the updated cloud properties ( dummy values)
3. Verified using CLI using vcd cse cluster list

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920#-:-MUBbdHD9oYOJyxTXKG-:bct3li2)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi)



<!-- Sent from Reviewable.io -->

2021-02-23 15:54 UTC, rocknes requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Is storing K8s distribution enough to get rid of vApp metadata? I don;t think so,
We can't get the z version of k8s from template name.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920#-:-MUEa9gm-nsggxi87IMj:b-k34268)* status: all files reviewed, 3 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 98 at r3](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUE_V5ZCpbPQOV1Uln6:-MUE_V5b-VmM1oxulvmY:bqahk7k) ([raw file](https://github.com/vmware/container-service-extension/blob/db82f6e5a6d6edb01abe63bdb74e9eadb32626f6/container_service_extension/rde/models/rde_2_0_0.py#L98)):*
> ```Python
>         self.ovdc_network_name = ovdc_network_name
>         self.k8_distribution = Distribution(**k8_distribution) \
>             if isinstance(k8_distribution, dict) else k8_distribution or Distribution()  # noqa: E501
> ```

What is the point of making the check `isinstance`? k8_distribution has been typed as Distribution in the method signature anyways.


<!-- Sent from Reviewable.io -->

2021-02-23 17:12 UTC, sakthisunda reviewed
we also have the following properties in Status:
  cni: weave 2.6.5
  docker_version: 19.03.12
  kubernetes: upstream 1.19.3

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920#-:-MUEs33pDtw2CPrMdFOh:ben0l9r)* status: all files reviewed, 3 unresolved discussions (waiting on @sahithi and @sakthisunda)



<!-- Sent from Reviewable.io -->

2021-02-23 18:22 UTC, Anirudh9794 commented
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 98 at r3](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUE_V5ZCpbPQOV1Uln6:-MUF6LZp04TKN-j44-Dg:bjlirek) ([raw file](https://github.com/vmware/container-service-extension/blob/db82f6e5a6d6edb01abe63bdb74e9eadb32626f6/container_service_extension/rde/models/rde_2_0_0.py#L98)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

What is the point of making the check `isinstance`? k8_distribution has been typed as Distribution in the method signature anyways.
</blockquote></details>

There is a type mismatch if dict is tried to be casted into Distribution. This if condition helps the entire dict representing DefEntity to be casted recursively into smaller dataclass objects.


<!-- Sent from Reviewable.io -->

2021-02-23 18:26 UTC, Anirudh9794 commented
___
*[cse_def_schema/schema_2_0_0.json, line 23 at r3](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUF7jkn1mR13Zhp_9Mf:-MUF7jkn1mR13Zhp_9Mg:bpo1am0) ([raw file](https://github.com/vmware/container-service-extension/blob/db82f6e5a6d6edb01abe63bdb74e9eadb32626f6/cse_def_schema/schema_2_0_0.json#L23)):*
> ```JSON
>                    "template_name":  { "type": "string"},
>                    "template_revision": { "type": "integer"}
>                 }
> ```

@rocknes @sahithi should we be more explicit in definition and add the `"additionalproperties": true`.  I just thought it increases readability


<!-- Sent from Reviewable.io -->

2021-02-23 18:27 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920#-:-MUF7YxHBSaMAAK8hBIt:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)



<!-- Sent from Reviewable.io -->

2021-02-23 18:57 UTC, sahithi reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)

___
*[cse_def_schema/schema_2_0_0.json, line 23 at r3](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUF7jkn1mR13Zhp_9Mf:-MUFEnlbCeguq5B1sfHL:binun7y) ([raw file](https://github.com/vmware/container-service-extension/blob/db82f6e5a6d6edb01abe63bdb74e9eadb32626f6/cse_def_schema/schema_2_0_0.json#L23)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

@rocknes @sahithi should we be more explicit in definition and add the `"additionalproperties": true`.  I just thought it increases readability
</blockquote></details>

sure, we can do that Aniruddh. @sakthisunda 


<!-- Sent from Reviewable.io -->

2021-02-23 19:49 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[cse_def_schema/schema_2_0_0.json, line 23 at r3](https://reviewable.io/reviews/vmware/container-service-extension/920#-MUF7jkn1mR13Zhp_9Mf:-MUFR-Mm-w-dKT-8xxxn:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/db82f6e5a6d6edb01abe63bdb74e9eadb32626f6/cse_def_schema/schema_2_0_0.json#L23)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

sure, we can do that Aniruddh. @sakthisunda 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-23 22:01 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/920#-:-MUFuGzP5D9SdDekRAL-:bg7igkv)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @rocknes and @sahithi)



<!-- Sent from Reviewable.io -->

2021-02-23 22:24 UTC, merged