[VCDA-2153] cse run to load the schema based on rde_in_use
vmware/container-service-extension pull request #925
Opened 2021-02-23 22:12 UTC by Anirudh9794

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

- Introduce a map for rde version to def keys
- deprecate methods which doesn't use rde-version to get entities

Testing done:
* check if cluster create is working fine with VCD 10.2
* Check if cluster list is working from CLI

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

@sahithi @sakthisunda @sahithi @rocknes @ltimothy7

2021-02-24 16:47 UTC, sahithi requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/de_cluster.py, line 155 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJsJT34qi6pUzmhTZz:-MUJsJT34qi6pUzmhT_-:b2v30en) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster.py#L155)):*
> ```Python
>         native_def_entity = None
>         additional_entity_properties = None
>         rde_version_used = \
> ```

rde_version_used -> server_rde_version

Can this be a class or instance variable?
___
*[container_service_extension/client/de_cluster.py, line 156 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJuFEr4nAt52lwBowH:-MUJuFEr4nAt52lwBowI:b-8s23hb) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster.py#L156)):*
> ```Python
>         additional_entity_properties = None
>         rde_version_used = \
>             def_utils.get_rde_version_by_vcd_api_version(
> ```

It is getting difficult to identify which method relies on service() and which does not.
I suggest splitting the rde/def_utils.py to rde/server_utils.py and rde/common/utils.py. In the later comments, I suggested moving entity_service.py as well to "rde/common". Let us sync up if you have any other ideas or concerns.
___
*[container_service_extension/client/de_cluster.py, line 157 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJnv21ErzKZQxB-VNm:-MUJnv21ErzKZQxB-VNn:bw87b4f) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster.py#L157)):*
> ```Python
>         rde_version_used = \
>             def_utils.get_rde_version_by_vcd_api_version(
>                 float(self._cloudapi_client.get_api_version()))
> ```

Is this auto-negotiated-api-version guaranteed to be the max of the intersection of CSE server-supported API versions and VCD API versions?
CSE_server 3.1= [34, 35, 36]
VCD 10.2 = [34, 35]

After "vcd login", will the api_version be 35 in this case?
___
*[container_service_extension/client/de_cluster_native.py, line 44 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJmpGg1291Y4M2aqgB:-MUJmpGh1YeHDffDaKxm:b-gqow6m) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster_native.py#L44)):*
> ```Python
>         self._native_cluster_api = NativeClusterApi(client)
>         self._client = client
>         self._rde_version_used = \
> ```

self._server_rde_version
___
*[container_service_extension/installer/configure_cse.py, line 2411 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJvoYfBGBlLi-6IR2a:-MUJvoYfBGBlLi-6IR2b:bgmp6j9) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/installer/configure_cse.py#L2411)):*
> ```Python
>                                  tenant_org_context=org_id)
> 
>         # TODO use rde_in_use instead of 1.0.0
> ```

I think this has to remain 1.0.0 as this is a specific upgrade path we are dealing with. Please check with Aritra on this. 
@rocknes 
___
*[container_service_extension/rde/constants.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJm6EmB1EqGWZHK1jP:-MUJm6EmB1EqGWZHK1jQ:b-ybyatk) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/constants.py#L109)):*
> ```Python
>         DefKey.ENTITY_TYPE_VENDOR: DEF_CSE_VENDOR,
>         DefKey.ENTITY_TYPE_NSS: DEF_NATIVE_ENTITY_TYPE_NSS,
>         DefKey.ENTITY_TYPE_VERSION: DEF_NATIVE_ENTITY_TYPE_VERSION,
> ```

I think this resolves to 1.0.0? Please create another variable for 2.0.0
___
*[container_service_extension/rde/entity_service.py, line 294 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJihwQ22hfm57evxxS:-MUJihwQ22hfm57evxxT:b-uy78dj) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L294)):*
> ```Python
>         """
>         # TODO deprecate this method and
>         # Use get_native_rde_by_name_and_rde_version() instead
> ```

Is the reason why you did not edit this method signature - to support backward compatibility with older versions of cse-client?
I think we need to solve this problem of not being able to freely edit server code. This "common" thing is soon going to get complicated.

Either Client needs to have its own library files (or) we need to mandate that there must exist 1-1 mapping between CSE client version and CSE version.
@rocknes @anirudh9794 
___
*[container_service_extension/rde/entity_service.py, line 305 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJq-xX6ysdBr4AAoZ2:-MUJpzdKANJ0iUqoc6cM:boep4j5) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L305)):*
> ```Python
> 
>     @handle_entity_service_exception
>     def get_native_rde_by_name_and_rde_version(self, name: str, version: str,  # noqa: E501
> ```

Indicate that this method is commonly used between client and server.
Please move this file entity_service.py to "rde/common"
___
*[container_service_extension/rde/entity_service.py, line 373 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJivkIAHbSGtQmb8Kq:-MUJhNaf4T3KCFG6AQ0T:b-rgyys4) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L373)):*
> ```Python
>         :rtype: DefEntityType
>         """
>         # TODO deprecate this method
> ```

I assume the same reason here.

Please check if anything like @deprecated decorator exists in the python libraries.
___
*[container_service_extension/rde/entity_service.py, line 383 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJg89--sUYVCqgwtd3:-MUJg89--sUYVCqgwtd4:beyzvhr) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L383)):*
> ```Python
>         return schema_svc.get_entity_type(entity_type_id)
> 
>     def get_rde_type_by_rde_version(self, rde_version: str) -> DefEntityType:
> ```

You can use the existing method - container_service_extension.rde.utils.get_registered_def_entity_type.
Did you add this method so that the CSE client can also leverage it? If yes, please add it in the docstring.
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 199 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJkojq5sIFmyj3Itnx:-MUJkojr3I4GJCyJLBE0:b-4zjwds) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/backend/cluster_service_1_x.py#L199)):*
> ```Python
> 
>         # create the corresponding defined entity .
>         native_entity_type = def_utils.get_registered_def_entity_type()
> ```

please declare the type
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 199 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJmP4JA0ukv5-KkYZ1:-MUJmP4JA0ukv5-KkYZ2:b-yjaleo) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af2 [...]

2021-02-24 17:28 UTC, sahithi requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: all files reviewed, 13 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/entity_service.py, line 318 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUK4GuiAoFfUuI8y5Y0:-MUK4GuiAoFfUuI8y5Y1:bsiixk1) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L318)):*
> ```Python
>         filters[def_constants.ClusterEntityFilterKey.CLUSTER_NAME.value] = name
>         entity_type: DefEntityType = \
>             self.get_rde_type_by_rde_version(version)
> ```

We could use this container_service_extension.rde.utils.generate_entity_type_id() here.


<!-- Sent from Reviewable.io -->

2021-02-24 17:49 UTC, Anirudh9794 commented
___
*[container_service_extension/client/de_cluster.py, line 157 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJnv21ErzKZQxB-VNm:-MUK6-Cn3jl_xzkF-RCy:b-t2pxh2) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster.py#L157)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is this auto-negotiated-api-version guaranteed to be the max of the intersection of CSE server-supported API versions and VCD API versions?
CSE_server 3.1= [34, 35, 36]
VCD 10.2 = [34, 35]

After "vcd login", will the api_version be 35 in this case?

</blockquote></details>

As of now, CSE CLI auto-negotiates the API version CSE server is running with. So, if CSE server is configured with API version 36, CSE CLI will make use of API version 36 for calls
In the future, I am expecting some changes in how auto-negotiation is done. Like /system endpoint sending list of API versions supported instead of a single API version. Even in this case, the API version should be valid.


<!-- Sent from Reviewable.io -->

2021-02-24 22:31 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: all files reviewed, 13 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/client/de_cluster.py, line 155 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJsJT34qi6pUzmhTZz:-MUKnu4ICHon7imDa4xB:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster.py#L155)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

rde_version_used -> server_rde_version

Can this be a class or instance variable?
</blockquote></details>

Done.
___
*[container_service_extension/client/de_cluster.py, line 156 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJuFEr4nAt52lwBowH:-MUL6WQqE34TcGCXbGSF:bqprqmv) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster.py#L156)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

It is getting difficult to identify which method relies on service() and which does not.
I suggest splitting the rde/def_utils.py to rde/server_utils.py and rde/common/utils.py. In the later comments, I suggested moving entity_service.py as well to "rde/common". Let us sync up if you have any other ideas or concerns.
</blockquote></details>

I think this confusion is because we have the method get_registered_def_entity_type() and `get_registered_def_interface():` in rde/utils.py. These are the only two methods which are dependent on server running.
I will move the function over to `server_utils` to maintain our coding pattern.
___
*[container_service_extension/client/de_cluster_native.py, line 44 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJmpGg1291Y4M2aqgB:-MUKoLteB32TT12CwrjD:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster_native.py#L44)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

self._server_rde_version
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJm6EmB1EqGWZHK1jP:-MUKpKZu7jqMxYtbONuD:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/constants.py#L109)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think this resolves to 1.0.0? Please create another variable for 2.0.0
</blockquote></details>

Done.
___
*[container_service_extension/rde/entity_service.py, line 294 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJihwQ22hfm57evxxS:-MUK9Z7t60oCaZL0AHjf:b5sfoxf) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L294)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is the reason why you did not edit this method signature - to support backward compatibility with older versions of cse-client?
I think we need to solve this problem of not being able to freely edit server code. This "common" thing is soon going to get complicated.

Either Client needs to have its own library files (or) we need to mandate that there must exist 1-1 mapping between CSE client version and CSE version.
@rocknes @anirudh9794 
</blockquote></details>

This function is no longer used anywhere. I think I can remove this function.
___
*[container_service_extension/rde/entity_service.py, line 318 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUK4GuiAoFfUuI8y5Y0:-MUKuc408h_2pqAQ8Wev:b15zsbg) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L318)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We could use this container_service_extension.rde.utils.generate_entity_type_id() here.
</blockquote></details>

I think it can be simplified even further now since we have a mapping from RDE version to Def Framework Information.
___
*[container_service_extension/rde/entity_service.py, line 373 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJivkIAHbSGtQmb8Kq:-MUKvvkS0gMUxau2QEkH:b-34zpq5) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L373)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I assume the same reason here.

Please check if anything like @deprecated decorator exists in the python libraries.
</blockquote></details>

Again. This method is no longer needed as it is not used anywhere in the codebase. Removing the deprecated method
___
*[container_service_extension/rde/entity_service.py, line 383 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJg89--sUYVCqgwtd3:-MUKDvoE7mvwopuSprex:b-p3nhhh) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L383)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You can use the existing method - container_service_extension.rde.utils.get_registered_def_entity_type.
Did you add this method so that the CSE client can also leverage it? If yes, please add it in the docstring.
</blockquote></details>

This is a helper method for `get_native_rde_by_name_and_rde_version()`. Since the logic was changed, I don't see a need for this method anymore. Will remove this method.
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 199 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJkojq5sIFmyj3Itnx:-MUL0RZSEDLf4RucZzb_:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/backend/cluster_service_1_x.py#L199)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please declare the type
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 199 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJmP4JA0ukv5-KkYZ1:-MUL0ycaDAaqTtAy71LZ:b-xnlvw1) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/backend/cluster_service_2_x.py#L199)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is this method updated to retrieve the latest 'rde_in_use'?
</blockquote></details>

Yes. In `service.py`, entity_type_id to be loaded is determined by the `server_rde_version`


<!-- Sent from Reviewable.io -->

2021-02-25 00:42 UTC, sahithi requested changes
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/client/de_cluster_native.py, line 83 at r2](https://reviewable.io/reviews/vmware/container-service-extension/925#-MULaiak62WiQ-bG9NQ9:-MULaiak62WiQ-bG9NQA:beeud1) ([raw file](https://github.com/vmware/container-service-extension/blob/d388f0824d732253d5a91d9d336479f4c7e3b022/container_service_extension/client/de_cluster_native.py#L83)):*
> ```Python
>         entity_svc = def_entity_svc.DefEntityService(self._cloudapi_client)
>         def_entity = \
>             entity_svc.get_native_rde_by_name_and_rde_version(
> ```

I don't see any changes around listing the entities, do we use interface API to list entities?
___
*[container_service_extension/rde/constants.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJm6EmB1EqGWZHK1jP:-MULU1qe60bTnec8l6MD:b8gr6t2) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/constants.py#L109)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Aniruddh, This just occurred to me. I am going to introduce a new interface with behaviors and there are going to be behavior versions, associated with RDE, interface versions. This Map with so many keys and values can soon get out of hand as we add more versions of RDE and interfaces. With all that in mind, can you please attempt the below-mentioned Enums?

class InterfaceMetadata(Enum):
common_k8s(vmware, k8s, 1.0.0)
behavior_k8s(cse, k8s, 1.0.0)
def __init__(vendor: str, nss: str, version: str):

class RDEMetadata(Enum):
1_0_0(cse, nativeCluster, 1.0.0, InterfaceMetadata.common_k8s)
2_0_0(cse, nativeCluster, 2.0.0, InterfaceMetadata.behavior_k8s)
def __init__(vendor: str, nss: str, version: str, interface: InterfaceMetadata)


<!-- Sent from Reviewable.io -->

2021-02-25 17:22 UTC, rocknes reviewed
Please fix the flake8 errors

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925#-:-MUPCatU7UEyQMSx1Zhk:b7tcubh)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)



<!-- Sent from Reviewable.io -->

2021-02-25 17:24 UTC, rocknes reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/client/de_cluster.py, line 157 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJnv21ErzKZQxB-VNm:-MUPCith8IbpzhGOGm7F:b-60eyax) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/client/de_cluster.py#L157)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

As of now, CSE CLI auto-negotiates the API version CSE server is running with. So, if CSE server is configured with API version 36, CSE CLI will make use of API version 36 for calls
In the future, I am expecting some changes in how auto-negotiation is done. Like /system endpoint sending list of API versions supported instead of a single API version. Even in this case, the API version should be valid.
</blockquote></details>

The system end point will continue to populate the api_version field to preserve backward compatibility.
Additionally it will send a new field which will contain all the supported api versions, so the client can chose which one to use.

The only thing to be careful about is that [33,34] and [35, 36..] will be mutually exclusive, i.e. the server can support only one set at any given time.


<!-- Sent from Reviewable.io -->

2021-02-25 19:04 UTC, sahithi reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/rde/constants.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJm6EmB1EqGWZHK1jP:-MUPYLh61NGVBRb6aDQK:b-16ew9h) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/constants.py#L109)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Aniruddh, This just occurred to me. I am going to introduce a new interface with behaviors and there are going to be behavior versions, associated with RDE, interface versions. This Map with so many keys and values can soon get out of hand as we add more versions of RDE and interfaces. With all that in mind, can you please attempt the below-mentioned Enums?

class InterfaceMetadata(Enum):
common_k8s(vmware, k8s, 1.0.0)
behavior_k8s(cse, k8s, 1.0.0)
def __init__(vendor: str, nss: str, version: str):

class RDEMetadata(Enum):
1_0_0(cse, nativeCluster, 1.0.0, InterfaceMetadata.common_k8s)
2_0_0(cse, nativeCluster, 2.0.0, InterfaceMetadata.behavior_k8s)
def __init__(vendor: str, nss: str, version: str, interface: InterfaceMetadata)

</blockquote></details>

class InterfaceMetadata(Enum):
common_k8s(vmware, k8s, 1.0.0)
behavior_k8s_1X(cse, k8s, 1.0.0)
def init(vendor: str, nss: str, version: str):

class RDEMetadata(Enum):
1_0_0(cse, nativeCluster, 1.0.0, InterfaceMetadata.common_k8s)
2_0_0(cse, nativeCluster, 2.0.0, [InterfaceMetadata.common_k8s,InterfaceMetadata.behavior_k8s])
2_1_0(cse, nativeCluster, 2.0.0, [InterfaceMetadata.common_k8s,InterfaceMetadata.behavior_k8s])
def init(vendor: str, nss: str, version: str, list(interface): InterfaceMetadata)

MAP_RDE_VERSION_TO_ = {
'1_0_0 ': RDEMetadata.1_0_0
'2_0_0': 


<!-- Sent from Reviewable.io -->

2021-02-26 04:12 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/client/de_cluster_native.py, line 83 at r2](https://reviewable.io/reviews/vmware/container-service-extension/925#-MULaiak62WiQ-bG9NQ9:-MUPeU8c2qyto-1YVMT-:bt8lh5s) ([raw file](https://github.com/vmware/container-service-extension/blob/d388f0824d732253d5a91d9d336479f4c7e3b022/container_service_extension/client/de_cluster_native.py#L83)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I don't see any changes around listing the entities, do we use interface API to list entities?
</blockquote></details>

Yes. CLI configuration is of two types
1. Tkg only ; in which case, we will use the TKG swagger client
2. Native + TKG ; in which case we use get entities by interface
___
*[container_service_extension/rde/constants.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJm6EmB1EqGWZHK1jP:-MURTQsx7fd3oapQFvN1:bpzdbyg) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/constants.py#L109)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

class InterfaceMetadata(Enum):
common_k8s(vmware, k8s, 1.0.0)
behavior_k8s_1X(cse, k8s, 1.0.0)
def init(vendor: str, nss: str, version: str):

class RDEMetadata(Enum):
1_0_0(cse, nativeCluster, 1.0.0, InterfaceMetadata.common_k8s)
2_0_0(cse, nativeCluster, 2.0.0, [InterfaceMetadata.common_k8s,InterfaceMetadata.behavior_k8s])
2_1_0(cse, nativeCluster, 2.0.0, [InterfaceMetadata.common_k8s,InterfaceMetadata.behavior_k8s])
def init(vendor: str, nss: str, version: str, list(interface): InterfaceMetadata)

MAP_RDE_VERSION_TO_ = {
'1_0_0 ': RDEMetadata.1_0_0
'2_0_0': 
</blockquote></details>

Organized the code as follows to keep Enums homogeneous (it was possible to have heterogeneous Enums but using them lead to confusing implementation and object representation was affected)
MAP_RDE_VERSION_TO_DEF_METADATA = {
  '1.0.0': {
      native-entity-type-metadata: NativeEntityTypeMetadataEnum,
      interfaces-used-by-entity-type: [CommonInterfaceMetadata]
    }
...
}
___
*[container_service_extension/rde/entity_service.py, line 305 at r1](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUJq-xX6ysdBr4AAoZ2:-MURUo6hEM3Dml2RaxcF:b-eoz4d4) ([raw file](https://github.com/vmware/container-service-extension/blob/fea1b1cabc44af22b879ef06781aca6ccf28f44e/container_service_extension/rde/entity_service.py#L305)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Indicate that this method is commonly used between client and server.
Please move this file entity_service.py to "rde/common"

</blockquote></details>

Added docstring to indicate that the function is used by both client and server.
Moved the module to `rde/common` package


<!-- Sent from Reviewable.io -->

2021-02-26 16:33 UTC, sahithi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Please do address all the comments and do basic sanity testing.

> Reviewed 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925#-:-MUU8t_sElvYDPXmw9lF:biv17h2)* status: all files reviewed, 25 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/rde/constants.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4XwI-krkXxNu1Ltj:-MUU4XwI-krkXxNu1Ltk:buoybgd) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L30)):*
> ```Python
> 
> @unique
> class Vendors(str, Enum):
> ```

Vendors -> Vendor
___
*[container_service_extension/rde/constants.py, line 79 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4iREDIr-f-uRcBiY:-MUU4iREDIr-f-uRcBiZ:b-k2ijs0) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L79)):*
> ```
> NativeEntityTypeMetadata_1_x
> ```
NativeEntityTypeMetadata_1_0_0; we will need to add these for each major or minor or patch version bump ups.
___
*[container_service_extension/rde/constants.py, line 90 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4wcP1I9Mopuj2PKb:-MUU4wcP1I9Mopuj2PKc:bb3i8e5) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L90)):*
> ```Python
> 
> 
> class NativeEntityTypeMetadata_2_x(str, Enum):
> ```

NativeEntityTypeMetadata_2_0_0
___
*[container_service_extension/rde/constants.py, line 94 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4yVP47leXRA_8LfE:-MUU4yVP47leXRA_8LfF:b-fbtkn9) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L94)):*
> ```Python
>     NSS = DEF_NATIVE_ENTITY_TYPE_NSS
>     VERSION = '2.0.0'
>     SCHEMA_FILE = 'schema_1_0_0.json'
> ```

schema_2_0_0.json
___
*[container_service_extension/rde/constants.py, line 97 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU5FcA53ilMXMGDhOr:-MUU5FcB6NhtPAVBkbDa:bph9oh8) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L97)):*
> ```Python
>     NAME = 'nativeClusterEntityType'
> 
>     @classmethod
> ```

Curious to know why you have made this class method? It could be static as well.
___
*[container_service_extension/rde/constants.py, line 102 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU8dHZAehnbdp6nYFN:-MUU8dHZAehnbdp6nYFO:b1gcz9n) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L102)):*
> ```Python
> 
> 
> class TKGEntityTypeMetadata_1_x(str, Enum):
> ```

TKGEntityTypeMetadata_1_0_0
___
*[container_service_extension/rde/constants.py, line 113 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU8Kxc9J3IAIzg7g6L:-MUU8Kxc9J3IAIzg7g6M:b-r49bqt) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L113)):*
> ```Python
> 
> 
> # TODO: Remove the usage of MAP_API_VERSION_TO_KEYS
> ```

Did you mean this to be replaced by MAP_VCD_API_VERSION_TO_RDE_VERSION? Please call it out and create a Jira task in the DEF Epic.
___
*[container_service_extension/rde/constants.py, line 146 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU6p_57YZdT24Fe0qj:-MUU6p_57YZdT24Fe0qk:bfdo2qf) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L146)):*
> ```Python
> 
> 
> MAP_RDE_VERSION_TO_DEF_METADATA = {
> ```

I think this sounds simple - MAP_RDE_VERSION_TO_ITS_METADATA

Please add the description to this map:
Key: The maximum RDE version in a given major version line.
Value: Interface and EntityType Metadata of that RDE version
___
*[container_service_extension/rde/constants.py, line 152 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU6OsD8oHV1o8-FSCJ:-MUU6OsD8oHV1o8-FSCK:bb3i8e5) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L152)):*
> ```Python
>     },
>     RDESchemaVersions.RDE_2_X: {
>         RDEMetadataKey.ENTITY_TYPE_METADATA: NativeEntityTypeMetadata_1_x,
> ```

NativeEntityTypeMetadata_2_0_0
___
*[container_service_extension/rde/utils.py, line 56 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU6blY5aBJIE4VZQEU:-MUU6blY5aBJIE4VZQEV:brexvkr) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/utils.py#L56)):*
> ```Python
> 
> 
> def get_def_metadata(rde_version: str) -> dict:
> ```

Avoid using 'def' going forward. Let us use 'rde'.
___
*[container_service_extension/server/service.py, line 502 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU9vT3BQsJOcRHS4LB:-MUU9vT3BQsJOcRHS4LC:b64d5fm) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/server/service.py#L502)):*
> ```Python
> 
>             schema_svc = def_schema_svc.DefSchemaService(cloudapi_client)
>             # TODO make use of self._rde_version to load Interface and Type
> ```

You may want to remove this TODO


<!-- Sent from Reviewable.io -->

2021-02-26 20:01 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: 12 of 17 files reviewed, 25 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/rde/constants.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4XwI-krkXxNu1Ltj:-MUUohrq6F4OeaR_HnOz:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L30)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Vendors -> Vendor
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 79 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4iREDIr-f-uRcBiY:-MUUpIeL1eeFhNfTiduk:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L79)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
> NativeEntityTypeMetadata_1_x
> ```
NativeEntityTypeMetadata_1_0_0; we will need to add these for each major or minor or patch version bump ups.
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 90 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4wcP1I9Mopuj2PKb:-MUUpR3C0DcCnDltySnh:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L90)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

NativeEntityTypeMetadata_2_0_0
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 94 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU4yVP47leXRA_8LfE:-MUUpVN39kXa_ccRjPzs:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L94)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

schema_2_0_0.json
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 97 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU5FcA53ilMXMGDhOr:-MUUsGx9B79Cuhwu918t:bmndlwi) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L97)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Curious to know why you have made this class method? It could be static as well.
</blockquote></details>

It can be either. But static method cannot access the class state. So it would be a longer notation because we will have to use `NativeEntityTypeMetadata_2_0_0` for vendor, nss and version.
I just wanted to make this shorter.
___
*[container_service_extension/rde/constants.py, line 102 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU8dHZAehnbdp6nYFN:-MUUtIlW95GP6pemqyJb:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L102)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

TKGEntityTypeMetadata_1_0_0
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 113 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU8Kxc9J3IAIzg7g6L:-MUUtU_p5FE8F5fKy1Ey:bxlyota) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L113)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Did you mean this to be replaced by MAP_VCD_API_VERSION_TO_RDE_VERSION? Please call it out and create a Jira task in the DEF Epic.
</blockquote></details>

Done. I don't think another jira task is needed. Once https://jira.eng.vmware.com/browse/VCDA-2151 is complete, we should be using MAP_RDE_VERSION_TO_METADATA dict
___
*[container_service_extension/rde/constants.py, line 146 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU6p_57YZdT24Fe0qj:-MUUu3o7Cwjh8emz8s47:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L146)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think this sounds simple - MAP_RDE_VERSION_TO_ITS_METADATA

Please add the description to this map:
Key: The maximum RDE version in a given major version line.
Value: Interface and EntityType Metadata of that RDE version
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 152 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU6OsD8oHV1o8-FSCJ:-MUUuSuz6GJM45kFBO7O:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/constants.py#L152)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

NativeEntityTypeMetadata_2_0_0
</blockquote></details>

Done.
___
*[container_service_extension/rde/utils.py, line 56 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU6blY5aBJIE4VZQEU:-MUUuffeAoU-VTZm-kSh:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/rde/utils.py#L56)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Avoid using 'def' going forward. Let us use 'rde'.
</blockquote></details>

Done.
___
*[container_service_extension/server/service.py, line 502 at r3](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUU9vT3BQsJOcRHS4LB:-MUUvYsp22z04E_M0iES:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0a0300cfb0c84b373908892a87c75464bb72545b/container_service_extension/server/service.py#L502)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You may want to remove this TODO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 21:28 UTC, sakthisunda approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925)* status: 12 of 17 files reviewed, 26 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)

___
*[container_service_extension/rde/constants.py, line 135 at r4](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUV9S6G70SCPffVg5No:-MUV9S6G70SCPffVg5Np:b-2pjdhv) ([raw file](https://github.com/vmware/container-service-extension/blob/d7c7a15597e7e9957523eb70b1ca0bee4d7ebf70/container_service_extension/rde/constants.py#L135)):*
> ```
> DefKey.ENTITY_TYPE_SCHEMA_VERSION: 'api_v35'
> ```
Just checking is 'api_v35' the correct value for 36.0 ? 
___
*[container_service_extension/server/service.py, line 512 at r4](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUVE57h6E4j3SRWFxjd:-MUVE57i8pYZaaI-lnm0:b8fbf62) ([raw file](https://github.com/vmware/container-service-extension/blob/d7c7a15597e7e9957523eb70b1ca0bee4d7ebf70/container_service_extension/server/service.py#L512)):*
> ```Python
>                 # interface for CSE is added.
>                 self._kubernetesInterface = \
>                     schema_svc.get_interface(interface_metadata.get_id())
> ```

FYI: Last entry in the above for loop finally assigne vale to  self._kubernetesInterface. Is this intentional ( interface_metadata_list has only one entry?)


<!-- Sent from Reviewable.io -->

2021-02-26 21:29 UTC, sakthisunda reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (minor clarifications)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/925#-:-MUVEfjZ5UjI7qMqn9DT:b-a772tm)* status: 11 of 19 files reviewed, 26 unresolved discussions (waiting on @Anirudh9794, @deprecated, @rocknes, and @sahithi)



<!-- Sent from Reviewable.io -->

2021-02-26 21:35 UTC, Anirudh9794 commented
___
*[container_service_extension/rde/constants.py, line 135 at r4](https://reviewable.io/reviews/vmware/container-service-extension/925#-MUV9S6G70SCPffVg5No:-MUVEwQX1ALCAa2lM-4F:bpor3pc) ([raw file](https://github.com/vmware/container-service-extension/blob/d7c7a15597e7e9957523eb70b1ca0bee4d7ebf70/container_service_extension/rde/constants.py#L135)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> DefKey.ENTITY_TYPE_SCHEMA_VERSION: 'api_v35'
> ```
Just checking is 'api_v35' the correct value for 36.0 ? 
</blockquote></details>

I will make changes for cse-install to stop using this dictionary but instead use `schema_2_0_0.json` until then, we can copy `schema_2_0_0.json` to `api_v35` directory for testing.


<!-- Sent from Reviewable.io -->

2021-02-26 22:02 UTC, merged