[VCDA-2052] Get current state of cluster from Defined Entity Status
vmware/container-service-extension pull request #928
Opened 2021-02-25 17:14 UTC by sakthisunda

- Cluster operations get the current state from defined entity status  
- Change the rde usage to 2.0.0 in cluster_svc2.py
- Method to convert the status to Spec as part of Cluster Service (Logically more closer for this method to be here)
- Retrieves the current state from Status using Helper 
- Stops updating the spec while updating Status, 
- While updating the Status, update the newly added cloud_properties and storage_profile
- Sanity test done on cluster creation using rde 2.0.0 and cluster service 2_x
- Verified Status gets updated
- TODO: Get latest master code and do cluster operations
---------
![image](https://user-images.githubusercontent.com/5530442/109189991-7b4e9e80-7749-11eb-8939-be8b8cb27cd5.png)

---------------------------
![image](https://user-images.githubusercontent.com/5530442/109190074-93262280-7749-11eb-8b33-f05519839a61.png)
--------------------------------------------------------
@Anirudh9794 @sahithi @rocknes

2021-02-25 22:50 UTC, sahithi requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928)* status: all files reviewed, 9 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 300 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQEP097VS4g57w7mmX:-MUQEP097VS4g57w7mmY:b5a89b2) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L300)):*
> ```Python
>         curr_entity: common_models.DefEntity = self.entity_svc.get_entity(cluster_id)  # noqa: E501
>         cluster_name: str = curr_entity.name
>         current_spec = self.construct_cluster_spec_from_entity_status(curr_entity.entity.status)  # noqa: E501
> ```

I suggest moving this method to rde/utils.py. This can be used by validators as well.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1367 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQF5FJ9dHoRnqEsuMZ:-MUQF5FJ9dHoRnqEsuM_:bje4ffs) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L1367)):*
> ```
>             curr_entity.entity.status.cloud_properties.k8_distribution.template_name = template[LocalTemplateKey.NAME]  # noqa: E501
>             curr_entity.entity.status.cloud_properties.k8_distribution.template_revision = int(template[LocalTemplateKey.REVISION])  # noqa: E501
> ```


nit: curr_entity.entity.status.cloud_properties.k8_distribution = Distribution(t_name, t_revision)
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1578 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQNBYh45CIp2enHhMu:-MUQNBYh45CIp2enHhMv:b-2jl7vp) ([raw file](https://github.com/vmware/container-service-extension/blob/cd93a91f0d560be396866db67aa1d88e82faf89f/container_service_extension/rde/backend/cluster_service_2_x.py#L1578)):*
> ```Python
>             self.context.sysadmin_client, vapp)
>         if curr_nodes_status:
>             curr_entity.entity.spec.workers.count = len(
> ```

Can you please double-check if there are no other places we are updating the spec section? I can't recall.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1653 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQHOETBC8INhLS2ZIE:-MUQHOETBC8INhLS2ZIF:bsu8iw2) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L1653)):*
> ```Python
> 
>     @staticmethod
>     def construct_cluster_spec_from_entity_status(entity_status: Union[rde_2_0_0.Status, dict]) -> rde_2_0_0.ClusterSpec:  # noqa: E501
> ```

I did not know we could do Union like this to declare the types. Like it.

Can we create the below wrapper method?

def construct...(status, rde_version_in_use):
......if (rde_version_in_use = '2.0.0')
.............return construct_2_0_0(status)
......elif(rde_version_in_use = '2.1.0')
.............return construct_1_0_0(status)


btw, this method can be moved to rde/utils.py (or) rde/validators/utils.py. Validators can also leverage this method.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1664 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQJk2eEwkaTe83vzl6:-MUQJk2eEwkaTe83vzl7:bfzqkp9) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L1664)):*
> ```
>         cluster_spec.control_plane.count = 1
>         cluster_spec.control_plane.sizing_class = entity_status.nodes.control_plane.sizing_class  # noqa: E501
>         cluster_spec.control_plane.storage_profile = entity_status.nodes.control_plane.storage_profile  # noqa: E501
> ```

cluster_spec.control_plane = ControlPlane(1, entity_status.nodes.control_plane.sizing_class, entity_status.nodes.control_plane.storage_profile)

The same can be done for other objects like workers, nfs, k8_distribution, settings
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1728 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQLD5QCXunJ1WAnXXB:-MUQLD5QCXunJ1WAnXXC:b3um4tr) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L1728)):*
> ```Python
>                     get_cse_policy_display_name(policy_name)
>             if hasattr(vm, 'StorageProfile'):
>                 storage_profile: str = vm.StorageProfile.get('name')
> ```

Initialize 
storage_profile=None
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 52 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQLYiuERVzF4fhP-ii:-MUQLYiuERVzF4fhP-ij:bhwgylu) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/models/rde_2_0_0.py#L52)):*
> ```Python
> @dataclass()
> class Settings:
>     network: str = None
> ```

Network is a required parameter. Please revert this.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 89 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQLt-iCcZ8OoyfjtDa:-MUQLt-iCcZ8OoyfjtDb:bfypxcu) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/models/rde_2_0_0.py#L89)):*
> ```Python
>     ovdc_network_name: str = None
>     k8_distribution: Distribution = None
>     ssh_key: str = None
> ```

I am thinking if we can store ssh_key as part of cloud_properties. There is also no real need. 
If we even decide to save it here, it needs to remain hidden. 

Can you please add a #TODO here to rethink this at some point?
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 144 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQMTJ4Cfyny9YIbuJV:-MUQMTJ4Cfyny9YIbuJW:bb9nuvn) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/models/rde_2_0_0.py#L144)):*
> ```Python
>     nfs: Nfs = None
>     k8_distribution: Distribution = None
>     settings: Settings = None
> ```

Settings is a required param as it holds the required param 'network'. Please revert this.


<!-- Sent from Reviewable.io -->

2021-02-26 04:50 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 300 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQEP097VS4g57w7mmX:-MURes_wBmVA3CNfHBBX:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L300)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest moving this method to rde/utils.py. This can be used by validators as well.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1578 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQNBYh45CIp2enHhMu:-MURf4090fUaA4yDIftJ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cd93a91f0d560be396866db67aa1d88e82faf89f/container_service_extension/rde/backend/cluster_service_2_x.py#L1578)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you please double-check if there are no other places we are updating the spec section? I can't recall.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1653 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQHOETBC8INhLS2ZIE:-MURf57M21nTrQEDpsfR:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L1653)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I did not know we could do Union like this to declare the types. Like it.

Can we create the below wrapper method?

def construct...(status, rde_version_in_use):
......if (rde_version_in_use = '2.0.0')
.............return construct_2_0_0(status)
......elif(rde_version_in_use = '2.1.0')
.............return construct_1_0_0(status)


btw, this method can be moved to rde/utils.py (or) rde/validators/utils.py. Validators can also leverage this method.


</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1664 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQJk2eEwkaTe83vzl6:-MURf6Rt9w3R6oQKTK4S:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L1664)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>         cluster_spec.control_plane.count = 1
>         cluster_spec.control_plane.sizing_class = entity_status.nodes.control_plane.sizing_class  # noqa: E501
>         cluster_spec.control_plane.storage_profile = entity_status.nodes.control_plane.storage_profile  # noqa: E501
> ```

cluster_spec.control_plane = ControlPlane(1, entity_status.nodes.control_plane.sizing_class, entity_status.nodes.control_plane.storage_profile)

The same can be done for other objects like workers, nfs, k8_distribution, settings
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1728 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQLD5QCXunJ1WAnXXB:-MURf7DdCd7omJVsSakQ:bd5yf42) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/backend/cluster_service_2_x.py#L1728)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Initialize 
storage_profile=None
</blockquote></details>

Thanks. Done
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 52 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQLYiuERVzF4fhP-ii:-MURf8zq405BWlZWMcu8:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/models/rde_2_0_0.py#L52)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Network is a required parameter. Please revert this.
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 89 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQLt-iCcZ8OoyfjtDa:-MURf9ex6M7IVnqdT52A:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/models/rde_2_0_0.py#L89)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I am thinking if we can store ssh_key as part of cloud_properties. There is also no real need. 
If we even decide to save it here, it needs to remain hidden. 

Can you please add a #TODO here to rethink this at some point?
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 144 at r1](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUQMTJ4Cfyny9YIbuJV:-MURfAMwAzx_lYKucwYA:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/f6d5324f6d53a612c5034b4a7d2a876c71866bc5/container_service_extension/rde/models/rde_2_0_0.py#L144)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Settings is a required param as it holds the required param 'network'. Please revert this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 16:02 UTC, sahithi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> after addressing comments

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928#-:-MUU3xVBCUdZQsN1Qkrk:b-98fkod)* status: all files reviewed, 10 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/utils.py, line 72 at r2](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUU-tZMDkoi_Z-ftmYl:-MUU-tZMDkoi_Z-ftmYm:brs8x69) ([raw file](https://github.com/vmware/container-service-extension/blob/b3eaf2b3b48c0fee181f847b8fd6a331bfcaa3e9/container_service_extension/rde/utils.py#L72)):*
> ```Python
> 
> 
> def construct_cluster_spec_from_entity_status(entity_status: Union[rde_1_0_0.Status, rde_2_0_0.Status, dict], rde_version_in_use: str) -> Union[rde_1_0_0.ClusterSpec, rde_2_0_0.ClusterSpec]:  # noqa: E501
> ```

Looks like we need parent class for this to avoid calling out each version. We can do this later, please add a TODO.
___
*[container_service_extension/rde/utils.py, line 80 at r2](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUU0ZEECiTJAv4NFb2T:-MUU0ZEECiTJAv4NFb2U:b8r4tyr) ([raw file](https://github.com/vmware/container-service-extension/blob/b3eaf2b3b48c0fee181f847b8fd6a331bfcaa3e9/container_service_extension/rde/utils.py#L80)):*
> ```Python
>     :raises NotImplementedError
>     """
>     if rde_version_in_use == def_constants.RDESchemaVersions.RDE_2_X.value:
> ```

This is incorrect. The value of RDE_2_X  may get changed to 2.1 next release. Aniruddh is coming up with Enums to address this in a better manner. Until then compare against hardcoded value "2.0.0". Please add a TODO to refer to the right enum/constant.

@anirudh9794 please update the description of RDESchemaVersions that Enum values will be updated as RDE minor versions get bumped up and new entries will be added with a major version bump up.


<!-- Sent from Reviewable.io -->

2021-02-26 17:14 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/utils.py, line 72 at r2](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUU-tZMDkoi_Z-ftmYl:-MUUKQ5o-gHXz_HiS-fd:b-md4fsb) ([raw file](https://github.com/vmware/container-service-extension/blob/b3eaf2b3b48c0fee181f847b8fd6a331bfcaa3e9/container_service_extension/rde/utils.py#L72)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Looks like we need parent class for this to avoid calling out each version. We can do this later, please add a TODO.
</blockquote></details>

TODO added 
___
*[container_service_extension/rde/utils.py, line 80 at r2](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUU0ZEECiTJAv4NFb2T:-MUUKT7LElTua-LnYVlY:bz0lbee) ([raw file](https://github.com/vmware/container-service-extension/blob/b3eaf2b3b48c0fee181f847b8fd6a331bfcaa3e9/container_service_extension/rde/utils.py#L80)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This is incorrect. The value of RDE_2_X  may get changed to 2.1 next release. Aniruddh is coming up with Enums to address this in a better manner. Until then compare against hardcoded value "2.0.0". Please add a TODO to refer to the right enum/constant.

@anirudh9794 please update the description of RDESchemaVersions that Enum values will be updated as RDE minor versions get bumped up and new entries will be added with a major version bump up.



</blockquote></details>

Replaced with hard coded RDE versions for now


<!-- Sent from Reviewable.io -->

2021-02-26 19:20 UTC, sahithi requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928)* status: all files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 301 at r3](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUUm1KZ-41fSOOthmj4:-MUUm1KZ-41fSOOthmj5:bcprhro) ([raw file](https://github.com/vmware/container-service-extension/blob/914de26778dfc287c2fdd97b21dd020a4b0c1eba/container_service_extension/rde/backend/cluster_service_2_x.py#L301)):*
> ```Python
>         cluster_name: str = curr_entity.name
>         current_spec = def_utils.construct_cluster_spec_from_entity_status(
>             curr_entity.entity.status, "2.0.0")  # noqa: E501
> ```

Sakthi, this cannot be a constant here. This needs to be server_rde_version global variable that Aniruddh added.


<!-- Sent from Reviewable.io -->

2021-02-26 19:48 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928)* status: 4 of 5 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 301 at r3](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUUm1KZ-41fSOOthmj4:-MUUsVUi01S1fB_JrI4R:b-jkisdm) ([raw file](https://github.com/vmware/container-service-extension/blob/914de26778dfc287c2fdd97b21dd020a4b0c1eba/container_service_extension/rde/backend/cluster_service_2_x.py#L301)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Sakthi, this cannot be a constant here. This needs to be server_rde_version global variable that Aniruddh added.
</blockquote></details>

Thanks. modified the hard coded string with new method to get the version


<!-- Sent from Reviewable.io -->

2021-02-26 22:59 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (minor comments)

> Reviewed 1 of 1 files at r4, 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928#-:-MUVZJka1WvncVi7wEWo:bk4hhe9)* status: 4 of 5 files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/utils.py, line 87 at r4](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUVPo938A0yx5FVN53K:-MUVPo938A0yx5FVN53L:ba7jmya) ([raw file](https://github.com/vmware/container-service-extension/blob/0b4acb5629850b2c2524e672620b1b536fb33a7a/container_service_extension/rde/utils.py#L87)):*
> ```Python
> 
> 
> def construct_2_0_0_cluster_spec_from_entity_status(entity_status: Union[rde_2_0_0.Status, dict]) -> rde_2_0_0.ClusterSpec:  # noqa:
> ```

Can we accept only rde_2_0_0.Status because, converting dictionary to dataclass should be handled by the caller.
___
*[container_service_extension/rde/utils.py, line 88 at r4](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUV9EaSEyFU6n4gn9P8:-MUV9EaSEyFU6n4gn9P9:b1btsaa) ([raw file](https://github.com/vmware/container-service-extension/blob/0b4acb5629850b2c2524e672620b1b536fb33a7a/container_service_extension/rde/utils.py#L88)):*
> ```Python
> 
> def construct_2_0_0_cluster_spec_from_entity_status(entity_status: Union[rde_2_0_0.Status, dict]) -> rde_2_0_0.ClusterSpec:  # noqa:
>     """Construct cluster specification from entity status using rde_2_0_0 model.
> ```

i don't think there is a need to keep copies of the same function for every minor version update. This function can be renamed to `construct_2_x_cluster_spec_from_entity_status()` if there is no need to maintain multiple copies of the function.
___
*[container_service_extension/rde/utils.py, line 99 at r4](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUVY1Va5sBhcE-mOlVN:-MUVY1Va5sBhcE-mOlVO:bkw8g7z) ([raw file](https://github.com/vmware/container-service-extension/blob/0b4acb5629850b2c2524e672620b1b536fb33a7a/container_service_extension/rde/utils.py#L99)):*
> ```Python
>         sizing_class=entity_status.nodes.control_plane.sizing_class,
>         storage_profile=entity_status.nodes.control_plane.storage_profile,
>         count=1)
> ```

I think a comment indicating that the maximum possible control plane node is 1 would be helpful


<!-- Sent from Reviewable.io -->

2021-02-26 23:18 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/928)* status: 3 of 5 files reviewed, 14 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/utils.py, line 87 at r4](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUVPo938A0yx5FVN53K:-MUVckhz5SU1HllNO1Xv:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0b4acb5629850b2c2524e672620b1b536fb33a7a/container_service_extension/rde/utils.py#L87)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can we accept only rde_2_0_0.Status because, converting dictionary to dataclass should be handled by the caller.
</blockquote></details>

Done.
___
*[container_service_extension/rde/utils.py, line 88 at r4](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUV9EaSEyFU6n4gn9P8:-MUVclR0CeSczEm5uD9e:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0b4acb5629850b2c2524e672620b1b536fb33a7a/container_service_extension/rde/utils.py#L88)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

i don't think there is a need to keep copies of the same function for every minor version update. This function can be renamed to `construct_2_x_cluster_spec_from_entity_status()` if there is no need to maintain multiple copies of the function.
</blockquote></details>

Done.
___
*[container_service_extension/rde/utils.py, line 99 at r4](https://reviewable.io/reviews/vmware/container-service-extension/928#-MUVY1Va5sBhcE-mOlVN:-MUVcm0OEmOkKUtkNAW4:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0b4acb5629850b2c2524e672620b1b536fb33a7a/container_service_extension/rde/utils.py#L99)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think a comment indicating that the maximum possible control plane node is 1 would be helpful
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 23:31 UTC, merged