[VCDA-2205] V35 handler - process input and use cluster service based on runtime rde version
vmware/container-service-extension pull request #984
Opened 2021-04-02 16:17 UTC by sakthisunda

- Convert the input based on runtime rde version
- Cluster service based on runtime rde version
- Convert the new entity to input format before returning
- Tested with following endpoints
- Tests done on CSE 3.1, VCD 10.3
vcd cse cluster apply
POST api/cse/3.0/cluster/{cluster_id}/action/upgrade
POST api/cse/3.0/clusters
PUT api/cse/3.0/cluster/{cluster_id}
- TBD : CSE 3.1, VCD 10.2 

@Anirudh9794 @sahithi

2021-04-04 18:06 UTC, sahithi requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/984)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/rde/models/rde_1_0_0.py, line 210 at r1](https://reviewable.io/reviews/vmware/container-service-extension/984#-MXT2b80CBekE_CVYyNN:-MXT2b81EtxNG_W4oa4s:bs3tjxa) ([raw file](https://github.com/vmware/container-service-extension/blob/705840ec2d1670a072cc1a7ff905708a5e4052a8/container_service_extension/rde/models/rde_1_0_0.py#L210)):*
> ```Python
>             return native_entity
> 
>         if isinstance(native_entity, rde_2_0_0.NativeEntity):
> ```

This logic will fail once Aniruddh checks his PR in. Please make necessary changes once he submits.


<!-- Sent from Reviewable.io -->

2021-04-06 00:03 UTC, sakthisunda reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/984)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_1_0_0.py, line 210 at r1](https://reviewable.io/reviews/vmware/container-service-extension/984#-MXT2b80CBekE_CVYyNN:-MXZUBsd-RmLn98Z04a9:br57kcz) ([raw file](https://github.com/vmware/container-service-extension/blob/705840ec2d1670a072cc1a7ff905708a5e4052a8/container_service_extension/rde/models/rde_1_0_0.py#L210)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This logic will fail once Aniruddh checks his PR in. Please make necessary changes once he submits.
</blockquote></details>

Changed to get the right properties based on updated RDE 2.0 model


<!-- Sent from Reviewable.io -->

2021-04-06 01:10 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/984#-:-MXZihKN8B2-N7vBdmHs:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)



<!-- Sent from Reviewable.io -->

2021-04-07 17:33 UTC, sahithi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/984#-:-MXhOFumELH76nsQ0S2N:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)



<!-- Sent from Reviewable.io -->

2021-04-07 18:46 UTC, merged